<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Tbl_transactions extends CI_Controller
{
	function __construct()
	{
		parent::__construct();
		$this->load->model('Tbl_transactions_model');
		$this->load->model('Tbl_shift_model');
		$this->load->model('Tbl_ledger_model');
		$this->load->model('Tbl_openno_model');
		$this->load->model('Tbl_agent_model');
		$this->load->model('Tbl_staff_model');
		$this->load->model('CoinModel');
		$this->load->library('session');
		$this->load->helper('url');
	}


	/*
     * adding of tbl_transactions
     */
	function addtrnback()
	{
		// $data['tbl_transactions'] = $this->Tbl_transactions_model->get_all_tbl_transactions();
		$data['shifts'] = $this->Tbl_shift_model->get_all_tbl_shift();
		$data['party'] = $this->Tbl_ledger_model->get_all_tbl_ledger();
		//$data['randomf4'] = $this->Tbl_shift_model->get_all_tbl_shift();
		$data['_view'] = 'tbl_transactions/indexnewback';
		$this->load->view('layouts/main', $data);
	}

	/*
     * adding of tbl_transactions
     */
	function index()
	{
		// $data['tbl_transactions'] = $this->Tbl_transactions_model->get_all_tbl_transactions();
		$data['shifts'] = $this->Tbl_shift_model->get_all_tbl_shift();
		$data['party'] = $this->Tbl_ledger_model->get_all_tbl_ledger();
		//$data['randomf4'] = $this->Tbl_shift_model->get_all_tbl_shift();
		$data['_view'] = 'tbl_transactions/index';
		$this->load->view('layouts/main', $data);
	}
	/*
     * adding of tbl_transactions_may
     */
	function indexmay()
	{
		// $data['tbl_transactions'] = $this->Tbl_transactions_model->get_all_tbl_transactions();
		
		//echo '<pre>'; print_r($this->session->userdata['role']); echo '</pre>';
		if($this->session->userdata['role'] == 'Staff'){
				$tbl_staff = $this->Tbl_staff_model->get_tbl_staff($this->session->userdata['id']);
			//$tbl_staff = $this->Tbl_shift_model->get_ledger_shifts($this->session->userdata['id']);
			//\echo '<pre>'; print_r($tbl_staff); echo '</pre>'; die;
			$data['party'] = $this->Tbl_ledger_model->get_tbl_ledger_byupdatedbyformasters($tbl_staff['updated_by']);
			//$data['shifts'] = $this->Tbl_shift_model->get_all_tbl_shift($tbl_staff['updated_by']);
			//$data['shifts'] = $this->Tbl_shift_model->get_all_tbl_shift_master($tbl_staff['updated_by']);
			$newTimestamp = time() + (24 * 60 * 60); // Add 12 hours to the current time (12 hours * 60 minutes * 60 seconds)
			$todate = date('Y-m-d', $newTimestamp);
			$fromdate = date('Y-m-d', time());
			$data['shifts'] = $this->Tbl_shift_model->get_all_tbl_shift_master_for_trans($tbl_staff['updated_by'],$fromdate,$todate,'data_entry_operator');
		}
		else{
		$data['party'] = $this->Tbl_ledger_model->get_all_tbl_ledger_admin();
		//$data['shifts'] = $this->Tbl_shift_model->get_all_tbl_shift_admin();
		$newTimestamp = time() + (24 * 60 * 60); // Add 12 hours to the current time (12 hours * 60 minutes * 60 seconds)
		$todate = date('Y-m-d', $newTimestamp);
		$fromdate = date('Y-m-d', time());
		$data['shifts'] = $this->Tbl_shift_model->get_all_tbl_shift_master_for_trans($this->session->userdata['id'],$fromdate,$todate,'master');
		}
		//echo '<pre>'; print_r($data['shifts']); echo '</pre>';die;	
		//$data['randomf4'] = $this->Tbl_shift_model->get_all_tbl_shift();
		$data['_view'] = 'tbl_transactions/indexmay';
		if($this->session->userdata['role'] == 'Staff'){
			$this->load->view('layouts/mainold', $data);	
		}
		else{
			$this->load->view('layouts/main', $data);
		}
		
	}



	function edit_trn($id = 0)
	{
		//$data['shifts'] = $this->Tbl_shift_model->get_all_tbl_shift();
		//$data['party'] = $this->Tbl_ledger_model->get_all_tbl_ledger();
		$data['tbl_transactions'] = $this->Tbl_transactions_model->get_edit_transactions($id);
		//echo '<pre>'; print_r($data); echo '</pre>';//die;
		$data['_view'] = 'tbl_transactions/edit_transactions_may';
		$this->load->view('layouts/main', $data);
	}

	function view()
	{
		$data = array();
		//echo '<pre>'; print_r($_POST); echo '</pre>'; die;
		if (isset($_POST) && (!empty(($_POST)))) {
			$data = $_POST;
			if ($this->session->userdata['id'] == 1) {
				$data['created_by'] = '1';
				$data['tbl_transactions'] = $this->Tbl_transactions_model->view_transaction_filter_admin($data);
				//$data['tbl_transactions'] = $this->Tbl_transactions_model->get_all_transactions_admin_may($data);
			} else {
				// if($this->session->userdata['role']=='Master'){
				// 	$tbl_ledger_master = $this->Tbl_staff_model->get_tbl_ledger_master($this->session->userdata['id']);
				// 	$tbl_staff_master = $this->Tbl_staff_model->get_tbl_staff_master_view($this->session->userdata['id']);
				// 	$tbl_staff = array_merge($tbl_ledger_master,$tbl_staff_master);
				// 	//echo '<pre>';print_r($tbl_staff); echo '</pre>'; die;
					
				// 	foreach($tbl_staff as $val){
				// 		$data['created_by'][] = !empty($val['id'])?$val['id']:$this->session->userdata['id'];
				// 	}
					
				// }
				// else{
				// 	$data['created_by'] = $this->session->userid;
					
				// }
				//echo '<pre>'; print_r($data); echo '</pre>'; die;
				$data['todate'] = date('Y-m-d',strtotime($_POST['todate']));
				// echo '<pre>'; print_r($data); echo '</pre>';
				$data['tbl_transactions'] = $this->Tbl_transactions_model->view_transaction_filter($data);
				
			}
		} else {
			$data['todate'] = date('Y-m-d', time());
			// $data['tbl_transactions'] = $this->Tbl_transactions_model->get_all_transactions();
			if ($this->session->userdata['id'] == 1) {
				$data['tbl_transactions'] = $this->Tbl_transactions_model->get_all_transactions_admin_may();
			} else {
				// echo '<pre>'; print_r($data); echo '</pre>';
				$data['tbl_transactions'] = $this->Tbl_transactions_model->view_transaction_filter($data);
			}
		}
		//echo '<pre>'; print_r($data['tbl_transactions']); echo '</pre>'; die;
		// $data['shifts'] = $this->Tbl_shift_model->get_all_tbl_shift();
		// $data['party'] = $this->Tbl_ledger_model->get_all_tbl_ledger();
		$data['party'] = $this->Tbl_ledger_model->get_all_tbl_ledger_admin();
		$newTimestamp = time() + (24 * 60 * 60); // Add 12 hours to the current time (12 hours * 60 minutes * 60 seconds)
		$todate = date('Y-m-d', $newTimestamp);
		$fromdate = date('Y-m-d', time());
		$params = $this->session->userdata['id'];
		$data['shifts'] =  $this->Tbl_shift_model->get_all_tbl_shift($params);
		$data['agent'] = $this->Tbl_agent_model->get_all_tbl_agent();
		$data['default_trans'] = $this->Tbl_ledger_model->get_all_tbl_ledger();
		//echo '<pre>'; print_r($data); echo '</pre>'; die;
		//$data['randomf4'] = $this->Tbl_shift_model->get_all_tbl_shift();
		$data['_view'] = 'tbl_transactions/view';
		if($this->session->userdata['role'] == 'Staff'){
			$this->load->view('layouts/mainold', $data);	
		}
		else{
			$this->load->view('layouts/main', $data);
		}
	}
	/*
     * Listing of tbl_transactions
     */
	function view_admin()
	{
		$data = array();
		if (isset($_POST) && (!empty(($_POST)))) {
			$data = $_POST;
			$data['staff_created_by'] = '';
			if ($this->session->userdata['id'] == 1) {
				$data['created_by'] = '1';
				$data['tbl_transactions'] = $this->Tbl_transactions_model->view_transaction_filter($data);
				//echo '<pre>'; print_r($data['tbl_transactions']); echo '</pre>'; die;
			} else {
				if($_SESSION['role']=='Master'){
					$tbl_staff = $this->Tbl_staff_model->get_tbl_ledger_master($this->session->userdata['id']);
					$data['created_by'] = $this->session->userid;
					//$data['created_by'] = $this->session->userid;
				}
				else{
					$data['created_by'] = $this->session->userid;
				}
				
				$data['tbl_transactions'] = $this->Tbl_transactions_model->view_transaction_filter($data);
			}
		} else {

			// $data['tbl_transactions'] = $this->Tbl_transactions_model->get_all_transactions();
			if ($this->session->userdata['id'] == 1) {
				//$data['tbl_transactions'] = $this->Tbl_transactions_model->get_all_transactions_admin_may();
				$data['created_by'] = '1';
				$data['tbl_transactions'] = $this->Tbl_transactions_model->view_transaction_filter($data);
			} else {
				//$data['tbl_transactions'] = $this->Tbl_transactions_model->get_all_transactions_may();
				//echo '<pre>'; print_r($_SESSION['role']); echo '</pre>'; die;
				if($_SESSION['role']=='Master'){
					$tbl_staff = $this->Tbl_staff_model->get_tbl_ledger_master($this->session->userdata['id']);
					//echo '<pre>'; print_r($tbl_staff); echo '</pre>'; die;
					$data['created_by'] = !empty($tbl_staff['id'])?$tbl_staff['id']:$this->session->userdata['id'];
					//$data['created_by'] = $this->session->userid;
				}
				else{
					$data['created_by'] = $this->session->userid;
				}
				//echo '<pre>'; print_r($data); echo '</pre>'; die;
				$data['tbl_transactions'] = $this->Tbl_transactions_model->view_transaction_filter($data);
			}
		}
		$data['shifts'] = $this->Tbl_shift_model->get_all_tbl_shift();
		$data['party'] = $this->Tbl_ledger_model->get_all_tbl_ledger();
		$data['agent'] = $this->Tbl_agent_model->get_all_tbl_agent();
		$data['default_trans'] = $this->Tbl_ledger_model->get_all_tbl_ledger();
		//echo '<pre>'; print_r($data); echo '</pre>'; die;
		//$data['randomf4'] = $this->Tbl_shift_model->get_all_tbl_shift();
		$data['_view'] = 'tbl_transactions/view';
		$this->load->view('layouts/main', $data);
	}
	/*
     * Listing of tbl_transactions
     */
	function view_details($mid)
	{
		$data['tbl_transactions'] = $this->Tbl_transactions_model->get_all_detail_transactions($mid);
		$data['shifts'] = $this->Tbl_shift_model->get_all_tbl_shift();
		$data['party'] = $this->Tbl_ledger_model->get_all_tbl_ledger();
		$data['default_trans'] = $this->Tbl_ledger_model->get_all_tbl_ledger();
		//$data['randomf4'] = $this->Tbl_shift_model->get_all_tbl_shift();
		$data['_view'] = 'tbl_transactions/view';
		$this->load->view('layouts/main', $data);
	}
	/*
     * Adding a new tbl_transactions
     */

	function add_transaction_final_app()
	{ //echo '<pre>';print_r($_POST); echo '</pre>'; die; 
		if(isset($_POST) && empty($_POST['shift'])){
			echo '<script>alert("Please Select Valid Shift!!"); history.go(-1); </script>';
		}
        //$coinbal = $this->CoinModel->getUserBalance($_POST['party']);
		//$coinbal = $this->CoinModel->get_coin_balance($_POST['party']);
		$coinbal = get_client_coin_balance($_POST['party']);
		// Check if all values are integers
		$trn_amount=$_POST['trn_amount'];
//$validIntegers = array_filter($trn_amount, 'is_numeric');
//echo count($validIntegers); die;
// if (count($validIntegers) === count($trn_amount)) {
//     // All values are valid integers
//     $_POST['ttamntt'] = array_sum($trn_amount);
// } else {
//     echo '<script>alert("Please Enter Valid Amount!!"); history.go(-1); </script>';
// }
$_POST['ttamntt'] = array_sum($trn_amount);
		//echo '<pre>';print_r($_POST); echo '</pre>'; die;
		if($coinbal< $_POST['ttamntt']){
			echo '<script>alert("Insufficient Coin Balance!!"); history.go(-1); </script>';
			return false;
		}
		else{
			$receiver_id = $_POST['updated_by'];
			$amount = $_POST['ttamntt'];
			$sender_id = $_POST['party'];
			//echo $amount; die;
			
			$coin_id = $this->CoinModel->allocateCoinsapp($sender_id, $receiver_id, $amount,$_POST['shift']);
		}
		// $tbl_staff = $this->Tbl_staff_model->get_tbl_staff($this->session->userdata['userid']);
		// echo '<pre>'; print_r($tbl_staff); echo '</pre>'; die;
		// if(empty($tbl_staff)){
		// 	$tbl_ledger = $this->Tbl_ledger_model->get_tbl_ledger($this->session->userdata['userid']);
		// 	$master_id = $tbl_ledger['id'];
		// }
		// else{
		// 	$master_id = $tbl_staff['id'];
		// }
		//$master_id = $this->session->userdata['id'];
		//echo $master_id; die;
		date_default_timezone_set('Asia/Kolkata');
		foreach ($_POST as $key => $val) {
			if ($val == '') {
				$_POST[$key] = 0;
			}
		}
		//$check = $this->checkvalidshiftentry($_POST['shift'],$_POST['dateoftrn']);
		//$ledger_details = $this->Tbl_ledger_model->get_tbl_ledger($_POST['userid']);
		//echo '<pre>'; print_r($ledger_details); updated_by die;
		$all_shifts = $this->Tbl_shift_model->get_tbl_shift_usershift_bymasterid($_POST['updated_by']);
		//echo '<pre>'; print_r($all_shifts); print_r($_POST);  die;
		$time = '';
		$ttime = time();
		foreach ($all_shifts as $val) {
			if ($val['id'] == $_POST['shift']) {
				$time = strtotime(date('d-m-Y', strtotime($val['open_date'])) . ' ' . date("H:i", strtotime($val['app_time'])));
				//$time = strtotime($val['app_time']);
				if ($val['shift_id'] == 11) {
					$time = strtotime('+7 hours', $time);
				}
			}
		}
		$valid = 'true';
		//echo '<pre>'; print_r($ttime); echo $time; die;
		if (($ttime > $time)) {
			$valid = 'false';
			//echo "<script>alert('invalid Entry. Please try Again!!');</script>";
			//header("Location: https://app.555xch.live/Entry-page.php?status=0");
			//exit();
		}
		//$valid = 'true';
		//echo $time.'<br>';
		//echo $valid; die; 
		//if (($ttime > $time)) {
			////$valid = 'false';
			//echo "<script>alert('invalid Entry. Please try Again!!');</script>";
			//header("Location: https://app.555xch.live/Entry-page.php?status=0");
			//exit();
		//}
		//die;
		//$_POST = array_map('array_filter', $_POST);
		//$_POST = array_filter($_POST);
		//$_POST = array_filter(array_map('array_filter', $_POST));
		//echo '<pre>'; print_r($_POST); echo '</pre>'; die;
		if ($valid == 'true') {
			foreach ($_POST['trn_number'] as $key => $val) {
				if ($val == '') {
					unset($_POST['trn_number'][$key]);
					unset($_POST['trn_amount'][$key]);
				}
				if ($val == '100') {
					$_POST['trn_number'][$key] = '00';
				}
			}
			foreach ($_POST['trn_amount'] as $key => $val) {
				if ($val == '') {
					unset($_POST['trn_number'][$key]);
					unset($_POST['trn_amount'][$key]);
				}
			}
			//echo '<pre>'; print_r($_POST); echo '</pre>';
			/*foreach($_POST['trn_amount'] as $key => $val ){
			if($val==''){
				unset($_POST['trn_number'][$key]);
				unset($_POST['trn_amount'][$key]);
			}
			if (strpos($val, ',') !== false) {
  unset($_POST['trn_number'][$key]);
				unset($_POST['trn_amount'][$key]);
}
			//echo sprintf("%02d", $val); die;
				
		}*/
			//echo '<pre>'; print_r($_POST); echo '</pre>'; die;
			//array_pop($_POST['trn_number']);
			//array_pop($_POST['trn_amount']);
			$_SESSION['userid'] = $_POST['userid'];
			//$_POST['ttamntt'] = array_sum(explode(',',end($_POST['trn_amount'])));
			$_POST['dateoftrn'] = date('Y-m-d', strtotime($_POST['dateoftrn']));
			$ttamntt = 0;
			foreach ($_POST['trn_number'] as $key => $val) {
				if (strpos($val, ',') !== false) {
					unset($_POST['trn_number'][$key]);
					unset($_POST['trn_amount'][$key]);
				}
				if (isset($_POST['trn_amount'][$key])) {
					$ttamntt += (int)$_POST['trn_amount'][$key];
				}
			}
			$_POST['ttamntt'] = $ttamntt;
			//echo '<pre>'; print_r($_POST); echo '</pre>'; die;
			//$trn_amount = $_POST['trn_amount'];
			//echo '<pre>'; print_r($_POST); echo '</pre>';
			//$f2tno = array_sum($trn_amount);
			//$f4tno = $_POST['tamount'];
			//$tnocross = $_POST['total_amount_cross'];
			//$tnofromto = $_POST['total_amount_fromto'];
			//$f8tno = count(explode(' ',$_POST['dara_f8']))*($_POST['dara_amount_f8']);
			//	$f8akharbahartno = (strlen($_POST['akhar_bahar_f8']))* ($_POST['amount_akahr_bahar_f8']);
			//$f8akharandertno = (strlen($_POST['akahr_andar_f8']))* ($_POST['amount_akahr_andar_f8']);
			//$ttnumber = $f2tno + $f4tno + $tnofromto + $f8tno+$tnocross;
			$ttnumber = $_POST['ttamntt'];
			//$ttakharno =  $f8akharbahartno + $f8akharandertno;
			$ttakharno = '0';
			$mastr['shift_id'] = $_POST['shift'];
			$mastr['party_id'] = $_POST['party'];
			$mastr['master_id'] = $_POST['updated_by'];
			$mastr['t_date'] = date('Y-m-d', strtotime($_POST['dateoftrn']));
			$mastr['total_number_amount'] = $ttnumber;
			$mastr['total_akhar_amount'] = '';
			$mastr['coin_id'] = $coin_id;
			$tbl_ledger_elements = $this->Tbl_ledger_model->get_tbl_ledger($_POST['party']);
			//echo '<pre>'; print_r($tbl_ledger_elements); echo '</pre>'; die;
			$Tb_Date_shift_party_entry['DaraRate'] = $tbl_ledger_elements['dara_rate'];
			$Tb_Date_shift_party_entry['Commision'] = $tbl_ledger_elements['dara_commision'];
			$Tb_Date_shift_party_entry['AkarRate'] = $tbl_ledger_elements['akhar_rate'];
			$Tb_Date_shift_party_entry['Commission'] = $tbl_ledger_elements['akhar_commission'];
			$Tb_Date_shift_party_entry['Rebait'] = $tbl_ledger_elements['rebate'];
			$Tb_Date_shift_party_entry['TP_person'] = $tbl_ledger_elements['tp_party_id'];
			$Tb_Date_shift_party_entry['TP_perc'] = $tbl_ledger_elements['tppercentage'];			
			$Tb_Date_shift_party_entry['ShiftId'] = $_POST['shift'];
			$Tb_Date_shift_party_entry['PartyId'] = $_POST['party'];
			$Tb_Date_shift_party_entry['Date'] = date('Y-m-d', strtotime($_POST['dateoftrn']));
			$Tb_Date_shift_party_entry['Total_Number_amount'] = $ttnumber;
			$Tb_Date_shift_party_entry['Total_Akhar_amount'] = '';
			$Tb_Date_shift_party_entry['Total_amount'] = $ttnumber + $ttakharno;
			//echo '<pre>'; print_r($mastr);print_r($Tb_Date_shift_party_entry); echo '</pre>';die;
			/*echo '<pre>'; print_r($_POST['trn_number']); echo '</pre>';
		$_POST['trn_number'] = array_map(
    function($v) { if ($v == '00') $v = '100'; return $v; },
    $_POST['trn_number']
);
$_POST['number'] = array_map(
    function($v) { if ($v == '00') $v = '100'; return $v; },
    $_POST['number']
);
if($_POST['fromto_from']=='00'){
	$_POST['fromto_from'] = 100;
}
if($_POST['fromto_to']=='00'){
	$_POST['fromto_to'] = 100;
} 
	//	$num_f2 = $_POST['trn_number'];
			//$num_f2 = array_map($this->replaceHundreds, $num_f2);
		echo '<pre>'; print_r($_POST['trn_number']); echo '</pre>'; die;*/
			$tbl_transactions_id = $this->Tbl_transactions_model->add_tbl_transaction($mastr); //die;
			$tbl_transactions_only_id = $this->Tbl_transactions_model->add_tbl_only_transaction_may($tbl_transactions_id, $_POST);
			/*added later*/	//$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->add_Tb_Date_shift_party_entry($tbl_transactions_id,$Tb_Date_shift_party_entry);	

			/* //commented for only number amount entry//	$tbl_transactions_rndomf4 = $this->Tbl_transactions_model->add_tbl_randomf4($tbl_transactions_id,$_POST);
		$tbl_transactions_cross = $this->Tbl_transactions_model->add_cross($tbl_transactions_id,$_POST);
		$tbl_transactions_add_fromto = $this->Tbl_transactions_model->add_fromto($tbl_transactions_id,$_POST);
		$tbl_transactions_random_f8 = $this->Tbl_transactions_model->random_f8($tbl_transactions_id,$_POST);*/
			$if_trn_exist = $this->Tbl_transactions_model->get_Date_shift_party_entry($_POST['shift'], $_POST['party'], date('d-m-Y', strtotime($_POST['dateoftrn'])));
			//echo '<pre>';print_r($if_trn_exist);die;
			if (!empty($if_trn_exist)) { //echo  'there';die;
				$odata = $this->Tbl_transactions_model->get_transaction_result_total($if_trn_exist[0]['id']);
				//echo '<pre>';print_r($odata); die;
				$uTb_Date_shift_party_entry['Total_Number_amount'] = $ttnumber + $odata['Total_Number_amount'];
				$uTb_Date_shift_party_entry['Total_Akhar_amount'] = $ttakharno + $odata['Total_Akhar_amount'];
				$uTb_Date_shift_party_entry['Total_amount'] = $ttnumber + $ttakharno + $odata['Total_amount'];
				$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->update_Tb_Date_shift_party_entry($if_trn_exist[0]['id'], $uTb_Date_shift_party_entry);
			} else {  //echo  'here';die;
				$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->add_Tb_Date_shift_party_entry($Tb_Date_shift_party_entry);
				//echo $Tb_Date_shift_party_entry_id;	die;
			}
			$qry = 'status=1';
		}else { $qry = 'status=0';
			?>
			<script>
				alert('Time Expired. Please try again.');
				window.history.go(-1)
			</script>
<?php
		}
		

		//header("Location: https://app.555xch.live/Entry-page.php?$qry=".$Tb_Date_shift_party_entry_id);
		header("Location: https://check.555xch.live/appdemo/" . $_POST['entryval'] . "&$qry&entry_id=" . $Tb_Date_shift_party_entry_id);
	}
	function add()
	{
		$this->load->library('form_validation');

		$this->form_validation->set_rules('transactions_name', 'transactions Name', 'max_length[255]');
		$this->form_validation->set_rules('real_name', 'Real Name', 'max_length[255]');
		//$this->form_validation->set_rules('group','Group','integer');
		//$this->form_validation->set_rules('dara_rate','Dara Rate','integer');
		//$this->form_validation->set_rules('akhar_rate','Akhar Rate','integer');
		//$this->form_validation->set_rules('owner_name','Owner Name','max_length[255]');
		$this->form_validation->set_rules('mobile', 'Mobile', 'integer');
		$this->form_validation->set_rules('updated_by', 'Updated By', 'integer');

		if ($this->form_validation->run()) {
			$params = array(
				'transactions_name' => $this->input->post('transactions_name'),
				'real_name' => $this->input->post('real_name'),
				'group' => $this->input->post('group'),
				'dara_rate' => $this->input->post('dara_rate'),
				'akhar_rate' => $this->input->post('akhar_rate'),
				'owner_name' => $this->input->post('owner_name'),
				'mobile' => $this->input->post('mobile'),
				'updated_by' => $this->session->userdata['id'],
				//'updated_date' => $this->input->post('updated_date'),
				'dara_commision' => $this->input->post('dara_commision'),
				'akhar_commission' => $this->input->post('akhar_commission'),
				//'tp_akhar_commission' => $this->input->post('tp_akhar_commission'),
				'rebate' => $this->input->post('rebate'),
				'tp_r' => $this->input->post('tp_r'),
				'hissa' => $this->input->post('hissa'),
				'address' => $this->input->post('address'),
			);

			$tbl_transactions_id = $this->Tbl_transactions_model->add_tbl_transactions($params);
			$this->session->set_flashdata('msg', 'Transaction Added');
			redirect('/transactions_master');
		} else {
			$data['tbl_transactions'] = $this->Tbl_transactions_model->get_all_tbl_transactions();
			$data['_view'] = 'tbl_transactions/add';
			$this->load->view('layouts/main', $data);
		}
	}

	function add_trn()
	{
		//print_r($_POST);die;
		$tbl_transactions_ledger = $this->Tbl_transactions_model->add_tbl_transaction_ledger($_POST);
		$tbl_transactions_id = $this->Tbl_transactions_model->add_tbl_transaction($_POST);
		if ($tbl_transactions_id) { // echo $tbl_transactions_id; die; 
			$tbl_master_transactions_id = $this->Tbl_transactions_model->add_tbl_only_transaction($tbl_transactions_id, $_POST);
			//echo '<pre>'; print_r($tbl_master_transactions_id);  echo '</pre>'; die;
			if ($tbl_master_transactions_id['master_id']) {
				return $tbl_master_transactions_id;
			}
		} else {
			return false;
		}
	}



	private function replaceHundreds($value)
	{
		return str_replace('00', '100', $value);
	}

	function add_transaction_final_may_master()
	{

		foreach ($_POST as $key => $val) {
			if ($val == '') {
				$_POST[$key] = 0;
			}
		}

		//$_POST = array_map('array_filter', $_POST);
		//$_POST = array_filter($_POST);
		//$_POST = array_filter(array_map('array_filter', $_POST));
		//echo '<pre>'; print_r($_POST); echo '</pre>'; die;
		foreach ($_POST['trn_number'] as $key => $val) {
			if ($val == '') {
				unset($_POST['trn_number'][$key]);
				unset($_POST['trn_amount'][$key]);
			}
		}
		foreach ($_POST['trn_amount'] as $key => $val) {
			if ($val == '') {
				unset($_POST['trn_number'][$key]);
				unset($_POST['trn_amount'][$key]);
			}
		}
		$updateopening = $this->crontoupdateclosing($_POST['party'], $_POST['dateoftrn']);
		//echo $updateopening; die;	
		//echo $Tb_Date_shift_party_entry_id; 
		// die;
		$closing = $this->Tbl_transactions_model->updateclosing($updateopening, $_POST['party'], $_POST['dateoftrn']);
		//echo '<pre>'; print_r($_POST); echo '</pre>'; die;
		$trn_amount = $_POST['trn_amount'];
		//echo '<pre>'; print_r($_POST); echo '</pre>';
		$f2tno = array_sum($trn_amount);
		$f4tno = $_POST['tamount'];
		$tnocross = $_POST['total_amount_cross'];
		$tnofromto = $_POST['total_amount_fromto'];
		$f8tno = count(explode(' ', $_POST['dara_f8'])) * ($_POST['dara_amount_f8']);
		$f8akharbahartno = (strlen($_POST['akhar_bahar_f8'])) * ($_POST['amount_akahr_bahar_f8']);
		$f8akharandertno = (strlen($_POST['akahr_andar_f8'])) * ($_POST['amount_akahr_andar_f8']);
		//$ttnumber = $f2tno + $f4tno + $tnofromto + $f8tno+$tnocross;
		$ttnumber = $_POST['ttamntt'];
		$ttakharno =  $f8akharbahartno + $f8akharandertno;
		$mastr['shift_id'] = $_POST['shift'];
		$mastr['party_id'] = $_POST['party'];
		$mastr['t_date'] = date('Y-m-d', strtotime($_POST['dateoftrn']));
		$mastr['total_number_amount'] = $ttnumber;
		$mastr['total_akhar_amount'] = $ttakharno;

		$tbl_ledger_elements = $this->Tbl_ledger_model->get_tbl_ledger($_POST['party']);
		//echo '<pre>'; print_r($tbl_ledger_elements); echo '</pre>'; die;
		$Tb_Date_shift_party_entry['DaraRate'] = $tbl_ledger_elements['dara_rate'];
		$Tb_Date_shift_party_entry['Commision'] = $tbl_ledger_elements['dara_commision'];
		$Tb_Date_shift_party_entry['AkarRate'] = $tbl_ledger_elements['akhar_rate'];
		$Tb_Date_shift_party_entry['Commission'] = $tbl_ledger_elements['akhar_commission'];
		$Tb_Date_shift_party_entry['Rebait'] = $tbl_ledger_elements['rebate'];
		$Tb_Date_shift_party_entry['TP_person'] = $tbl_ledger_elements['tp_party_id'];
		$Tb_Date_shift_party_entry['TP_perc'] = $tbl_ledger_elements['tppercentage'];
		$Tb_Date_shift_party_entry['ShiftId'] = $_POST['shift'];
		$Tb_Date_shift_party_entry['PartyId'] = $_POST['party'];
		$Tb_Date_shift_party_entry['Date'] = date('Y-m-d', strtotime($_POST['dateoftrn']));
		$Tb_Date_shift_party_entry['Total_Number_amount'] = $ttnumber;
		$Tb_Date_shift_party_entry['Total_Akhar_amount'] = $ttakharno;
		$Tb_Date_shift_party_entry['Total_amount'] = $ttnumber + $ttakharno;
		/*echo '<pre>'; print_r($_POST['trn_number']); echo '</pre>';
		$_POST['trn_number'] = array_map(
    function($v) { if ($v == '00') $v = '100'; return $v; },
    $_POST['trn_number']
);
$_POST['number'] = array_map(
    function($v) { if ($v == '00') $v = '100'; return $v; },
    $_POST['number']
);
if($_POST['fromto_from']=='00'){
	$_POST['fromto_from'] = 100;
}
if($_POST['fromto_to']=='00'){
	$_POST['fromto_to'] = 100;
}
	//	$num_f2 = $_POST['trn_number'];
			//$num_f2 = array_map($this->replaceHundreds, $num_f2);
		echo '<pre>'; print_r($_POST['trn_number']); echo '</pre>'; die;*/
		$tbl_transactions_id = $this->Tbl_transactions_model->add_tbl_transaction($mastr); //die;
		$tbl_transactions_only_id = $this->Tbl_transactions_model->add_tbl_only_transaction_may($tbl_transactions_id, $_POST);
		/*added later*/	//$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->add_Tb_Date_shift_party_entry($tbl_transactions_id,$Tb_Date_shift_party_entry);	

		/* //commented for only number amount entry//	$tbl_transactions_rndomf4 = $this->Tbl_transactions_model->add_tbl_randomf4($tbl_transactions_id,$_POST);
		$tbl_transactions_cross = $this->Tbl_transactions_model->add_cross($tbl_transactions_id,$_POST);
		$tbl_transactions_add_fromto = $this->Tbl_transactions_model->add_fromto($tbl_transactions_id,$_POST);
		$tbl_transactions_random_f8 = $this->Tbl_transactions_model->random_f8($tbl_transactions_id,$_POST);*/
		$if_trn_exist = $this->Tbl_transactions_model->get_Date_shift_party_entry($_POST['shift'], $_POST['party'], $_POST['dateoftrn']);
		//echo '<pre>';print_r($if_trn_exist);die;
		if (!empty($if_trn_exist)) { //echo  'there';die;
			$odata = $this->Tbl_transactions_model->get_transaction_result_total($if_trn_exist[0]['id']);
			//echo '<pre>';print_r($odata); die;
			$uTb_Date_shift_party_entry['Total_Number_amount'] = $ttnumber + $odata['Total_Number_amount'];
			$uTb_Date_shift_party_entry['Total_Akhar_amount'] = $ttakharno + $odata['Total_Akhar_amount'];
			$uTb_Date_shift_party_entry['Total_amount'] = $ttnumber + $ttakharno + $odata['Total_amount'];
			$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->update_Tb_Date_shift_party_entry($if_trn_exist[0]['id'], $uTb_Date_shift_party_entry);
		} else {  //echo  'here';die;
			$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->add_Tb_Date_shift_party_entry($Tb_Date_shift_party_entry);
			//echo $Tb_Date_shift_party_entry_id;	die;
		}

		/*$this->session->set_flashdata('msg', 'Transactions Added');
				 redirect(site_url('/transactions'));*/
		$this->session->set_flashdata('message', 'Transactions Added');
		redirect('/transactions');
		// redirect('/tbl_transactions/edit_trn/'.$tbl_transactions_id);

	}
	function sendjantri()
	{ //echo '<pre>'; print_r($_POST); die;
		if(isset($_POST) && empty($_POST['shift'])){
			echo '<script>alert("Please Select Valid Shift!!"); history.go(-1); </script>';
		}
		$_POST['party'] = $this->session->userid;
        $coinbal = $this->CoinModel->get_coin_balance($_POST['party']);
		if($coinbal< $_POST['ttamntt']){
			echo '<script>alert("Insufficient Coin Balance!!"); history.go(-1); </script>';
			return false;
		}
		else{
			$receiver_id = 1;
			$amount = $_POST['ttamntt'];
			$sender_id = $_POST['party'];
			$this->CoinModel->allocateCoins($sender_id, $receiver_id, $amount);
		}
		unset($_POST['row_0']);
		unset($_POST['row_1']); unset($_POST['row_2']);unset($_POST['row_3']);
		unset($_POST['row_4']);unset($_POST['row_5']);unset($_POST['row_6']);
		unset($_POST['row_7']);unset($_POST['row_8']);unset($_POST['row_9']);
		//echo '<pre>'; print_r($_POST); echo '</pre>'; die;
		foreach ($_POST as $key => $val) {
			if ($val == 0) {
				unset($_POST[$key]) ;
			} 
			if($key !='ttamntt' && $key !='dateoftrn' && $key !='shift' && $key !='party' && $val!=0){
				//echo $key.'<br>';	//$_POST['trn_number'][] = $
				$num = explode('_',$key);
				if($num[1] == '100'){
					$num[1] = '00';
				}
				$_POST['trn_number'][] = $num[1];
				$_POST['trn_amount'][] = $val;
			}
		}
		
		//echo '<pre>'; print_r($_POST); echo '</pre>'; die;
		foreach ($_POST['trn_number'] as $key => $val) {
			if ($val == '') {
				unset($_POST['trn_number'][$key]);
				unset($_POST['trn_amount'][$key]);
			}
		}
		foreach ($_POST['trn_amount'] as $key => $val) {
			if ($val == '') {
				unset($_POST['trn_number'][$key]);
				unset($_POST['trn_amount'][$key]);
			}
		}
		$updateopening = $this->crontoupdateclosing($_POST['party'], $_POST['dateoftrn']);
		//echo $updateopening; die;	
		//echo $Tb_Date_shift_party_entry_id; 
		// die;
		$closing = $this->Tbl_transactions_model->updateclosing($updateopening, $_POST['party'], $_POST['dateoftrn']);
		//echo '<pre>'; print_r($_POST); echo '</pre>'; die;
		$trn_amount = $_POST['trn_amount'];
		//echo '<pre>'; print_r($_POST); echo '</pre>';
		//$f2tno = array_sum($trn_amount);
		//$f4tno = $_POST['tamount'];
		//$tnocross = $_POST['total_amount_cross'];
		//$tnofromto = $_POST['total_amount_fromto'];
		//$f8tno = count(explode(' ', $_POST['dara_f8'])) * ($_POST['dara_amount_f8']);
		$_POST['akhar_bahar_f8'] = !empty($_POST['akhar_bahar_f8'])?$_POST['akhar_bahar_f8']:'0';
		$_POST['amount_akahr_bahar_f8'] = !empty($_POST['amount_akahr_bahar_f8'])?$_POST['amount_akahr_bahar_f8']:'0';
		$_POST['akahr_andar_f8'] = !empty($_POST['akahr_andar_f8'])?$_POST['akahr_andar_f8']:'0';
		$_POST['amount_akahr_andar_f8'] = !empty($_POST['amount_akahr_andar_f8'])?$_POST['amount_akahr_andar_f8']:'0';
		$f8akharbahartno = (strlen($_POST['akhar_bahar_f8'])) * ($_POST['amount_akahr_bahar_f8']);
		$f8akharandertno = (strlen($_POST['akahr_andar_f8'])) * ($_POST['amount_akahr_andar_f8']);
		//$ttnumber = $f2tno + $f4tno + $tnofromto + $f8tno+$tnocross;
		$ttnumber = $_POST['ttamntt'];
		$ttakharno =  $f8akharbahartno + $f8akharandertno;
		$mastr['shift_id'] = $_POST['shift'];
		$mastr['party_id'] = $_POST['party'];
		$mastr['master_id'] = $this->session->userdata['id'];
		$mastr['t_date'] = date('Y-m-d', strtotime($_POST['dateoftrn']));
		$mastr['total_number_amount'] = $ttnumber;
		$mastr['total_akhar_amount'] = $ttakharno;
		$mastr['show_to_admin'] = '1';
		$tbl_ledger_elements = $this->Tbl_ledger_model->get_tbl_ledger($_POST['party']);
		//echo '<pre>'; print_r($tbl_ledger_elements); echo '</pre>'; die;
		$Tb_Date_shift_party_entry['master_id'] = 1;
		$Tb_Date_shift_party_entry['DaraRate'] = $tbl_ledger_elements['dara_rate'];
		$Tb_Date_shift_party_entry['Commision'] = $tbl_ledger_elements['dara_commision'];
		$Tb_Date_shift_party_entry['AkarRate'] = $tbl_ledger_elements['akhar_rate'];
		$Tb_Date_shift_party_entry['Commission'] = $tbl_ledger_elements['akhar_commission'];
		$Tb_Date_shift_party_entry['Rebait'] = $tbl_ledger_elements['rebate'];
		$Tb_Date_shift_party_entry['TP_person'] = $tbl_ledger_elements['tp_party_id'];
		$Tb_Date_shift_party_entry['TP_perc'] = $tbl_ledger_elements['tppercentage'];
		$Tb_Date_shift_party_entry['ShiftId'] = $_POST['shift'];
		$Tb_Date_shift_party_entry['PartyId'] = $_POST['party'];
		$Tb_Date_shift_party_entry['Date'] = date('Y-m-d', strtotime($_POST['dateoftrn']));
		$Tb_Date_shift_party_entry['Total_Number_amount'] = $ttnumber;
		$Tb_Date_shift_party_entry['Total_Akhar_amount'] = $ttakharno;
		$Tb_Date_shift_party_entry['Total_amount'] = $ttnumber + $ttakharno;
		/*echo '<pre>'; print_r($_POST['trn_number']); echo '</pre>';
		$_POST['trn_number'] = array_map(
    function($v) { if ($v == '00') $v = '100'; return $v; },
    $_POST['trn_number']
);
$_POST['number'] = array_map(
    function($v) { if ($v == '00') $v = '100'; return $v; },
    $_POST['number']
);
if($_POST['fromto_from']=='00'){
	$_POST['fromto_from'] = 100;
}
if($_POST['fromto_to']=='00'){
	$_POST['fromto_to'] = 100;
}
	//	$num_f2 = $_POST['trn_number'];
			//$num_f2 = array_map($this->replaceHundreds, $num_f2);
		echo '<pre>'; print_r($_POST['trn_number']); echo '</pre>'; die;*/
		$tbl_transactions_id = $this->Tbl_transactions_model->add_tbl_transaction($mastr); //die;
		$tbl_transactions_only_id = $this->Tbl_transactions_model->add_tbl_only_transaction_may($tbl_transactions_id, $_POST);
		/*added later*/	//$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->add_Tb_Date_shift_party_entry($tbl_transactions_id,$Tb_Date_shift_party_entry);	

		/* //commented for only number amount entry//	$tbl_transactions_rndomf4 = $this->Tbl_transactions_model->add_tbl_randomf4($tbl_transactions_id,$_POST);
		$tbl_transactions_cross = $this->Tbl_transactions_model->add_cross($tbl_transactions_id,$_POST);
		$tbl_transactions_add_fromto = $this->Tbl_transactions_model->add_fromto($tbl_transactions_id,$_POST);
		$tbl_transactions_random_f8 = $this->Tbl_transactions_model->random_f8($tbl_transactions_id,$_POST);*/
		$if_trn_exist = $this->Tbl_transactions_model->get_Date_shift_party_entry($_POST['shift'], $_POST['party'], $_POST['dateoftrn']);
		//echo '<pre>';print_r($if_trn_exist);die;
		if (!empty($if_trn_exist)) { //echo  'there';die;
			$odata = $this->Tbl_transactions_model->get_transaction_result_total($if_trn_exist[0]['id']);
			//echo '<pre>';print_r($odata); die;
			$uTb_Date_shift_party_entry['Total_Number_amount'] = $ttnumber + $odata['Total_Number_amount'];
			$uTb_Date_shift_party_entry['Total_Akhar_amount'] = $ttakharno + $odata['Total_Akhar_amount'];
			$uTb_Date_shift_party_entry['Total_amount'] = $ttnumber + $ttakharno + $odata['Total_amount'];
			$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->update_Tb_Date_shift_party_entry($if_trn_exist[0]['id'], $uTb_Date_shift_party_entry);
		} else {  //echo  'here';die;
			$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->add_Tb_Date_shift_party_entry($Tb_Date_shift_party_entry);
			//echo $Tb_Date_shift_party_entry_id;	die;
		}

		/*$this->session->set_flashdata('msg', 'Transactions Added');
				 redirect(site_url('/transactions'));*/
		$this->session->set_flashdata('message', 'Transactions Added');
		redirect('/transactions');
	}
	function add_transaction_final_may()
	{
		date_default_timezone_set('Asia/Kolkata');
		$coinbal = $this->CoinModel->get_coin_balance($_POST['party']);
			// Check if all values are integers
			$trn_amount=$_POST['trn_amount'];
	
	$_POST['ttamntt'] = array_sum($trn_amount);
			//echo '<pre>';print_r($_POST); echo '</pre>'; die;
			if($coinbal< $_POST['ttamntt']){
				echo '<script>alert("Insufficient Coin Balance!!"); history.go(-1); </script>';
				return false;
			}
			else{
				$receiver_id = '9999999999';
				$amount = $_POST['ttamntt'];
				$sender_id = $_POST['party'];
				//echo $amount; die;
				$this->CoinModel->allocateCoinsapp($sender_id, $receiver_id, $amount,$_POST['shift']);
			}
	//echo $master_id; die;
		foreach ($_POST as $key => $val) {
			if ($val == '') {
				$_POST[$key] = 0;
			}
		}

		//$_POST = array_map('array_filter', $_POST);
		//$_POST = array_filter($_POST);
		//$_POST = array_filter(array_map('array_filter', $_POST));
		
		foreach ($_POST['trn_number'] as $key => $val) {
			if ($val == '') {
				unset($_POST['trn_number'][$key]);
				unset($_POST['trn_amount'][$key]);
			}
		}
		foreach ($_POST['trn_amount'] as $key => $val) {
			if ($val == '') {
				unset($_POST['trn_number'][$key]);
				unset($_POST['trn_amount'][$key]);
			}
		}
		$updateopening = $this->crontoupdateclosing($_POST['party'], $_POST['dateoftrn']);
		//echo $updateopening; die;	
		//echo $Tb_Date_shift_party_entry_id; 
		// die;
		$closing = $this->Tbl_transactions_model->updateclosing($updateopening, $_POST['party'], $_POST['dateoftrn']);
		//echo '<pre>'; print_r($_POST); echo '</pre>'; die;
		$trn_amount = $_POST['trn_amount'];
		//echo '<pre>'; print_r($_POST); echo '</pre>';
		$f2tno = array_sum($trn_amount);
		$f4tno = $_POST['tamount'];
		$tnocross = $_POST['total_amount_cross'];
		$tnofromto = $_POST['total_amount_fromto'];
		$f8tno = count(explode(' ', $_POST['dara_f8'])) * ($_POST['dara_amount_f8']);
		$f8akharbahartno = (strlen($_POST['akhar_bahar_f8'])) * ($_POST['amount_akahr_bahar_f8']);
		$f8akharandertno = (strlen($_POST['akahr_andar_f8'])) * ($_POST['amount_akahr_andar_f8']);
		//$ttnumber = $f2tno + $f4tno + $tnofromto + $f8tno+$tnocross;
		$ttnumber = $_POST['ttamntt'];
		$ttakharno =  $f8akharbahartno + $f8akharandertno;
		$mastr['shift_id'] = $_POST['shift'];
		$mastr['party_id'] = $_POST['party'];
		$mastr['master_id'] = $_POST['updated_by'];
		$mastr['t_date'] = date('Y-m-d', strtotime($_POST['dateoftrn']));
		$mastr['total_number_amount'] = $ttnumber;
		$mastr['total_akhar_amount'] = $ttakharno;

		$tbl_ledger_elements = $this->Tbl_ledger_model->get_tbl_ledger($_POST['party']);
		//echo '<pre>'; print_r($tbl_ledger_elements); echo '</pre>'; die;
		$Tb_Date_shift_party_entry['master_id'] = $_POST['updated_by'];
		$Tb_Date_shift_party_entry['DaraRate'] = $tbl_ledger_elements['dara_rate'];
		$Tb_Date_shift_party_entry['Commision'] = $tbl_ledger_elements['dara_commision'];
		$Tb_Date_shift_party_entry['AkarRate'] = $tbl_ledger_elements['akhar_rate'];
		$Tb_Date_shift_party_entry['Commission'] = $tbl_ledger_elements['akhar_commission'];
		$Tb_Date_shift_party_entry['Rebait'] = $tbl_ledger_elements['rebate'];
		$Tb_Date_shift_party_entry['TP_person'] = $tbl_ledger_elements['tp_party_id'];
		$Tb_Date_shift_party_entry['TP_perc'] = $tbl_ledger_elements['tppercentage'];
		
		$Tb_Date_shift_party_entry['ShiftId'] = $_POST['shift'];
		$Tb_Date_shift_party_entry['PartyId'] = $_POST['party'];
		$Tb_Date_shift_party_entry['Date'] = date('Y-m-d', strtotime($_POST['dateoftrn']));
		$Tb_Date_shift_party_entry['Total_Number_amount'] = $ttnumber;
		$Tb_Date_shift_party_entry['Total_Akhar_amount'] = $ttakharno;
		$Tb_Date_shift_party_entry['Total_amount'] = $ttnumber + $ttakharno;
		//echo '<pre>'; print_r($Tb_Date_shift_party_entry); echo '</pre>'; die;
		/*
		$_POST['trn_number'] = array_map(
    function($v) { if ($v == '00') $v = '100'; return $v; },
    $_POST['trn_number']
);
$_POST['number'] = array_map(
    function($v) { if ($v == '00') $v = '100'; return $v; },
    $_POST['number']
);
if($_POST['fromto_from']=='00'){
	$_POST['fromto_from'] = 100;
}
if($_POST['fromto_to']=='00'){
	$_POST['fromto_to'] = 100;
}
	//	$num_f2 = $_POST['trn_number'];
			//$num_f2 = array_map($this->replaceHundreds, $num_f2);
		echo '<pre>'; print_r($_POST['trn_number']); echo '</pre>'; die;*/
		$tbl_transactions_id = $this->Tbl_transactions_model->add_tbl_transaction($mastr); //die;
		$tbl_transactions_only_id = $this->Tbl_transactions_model->add_tbl_only_transaction_may($tbl_transactions_id, $_POST);
		/*added later*/	//$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->add_Tb_Date_shift_party_entry($tbl_transactions_id,$Tb_Date_shift_party_entry);	

		/* //commented for only number amount entry//	$tbl_transactions_rndomf4 = $this->Tbl_transactions_model->add_tbl_randomf4($tbl_transactions_id,$_POST);
		$tbl_transactions_cross = $this->Tbl_transactions_model->add_cross($tbl_transactions_id,$_POST);
		$tbl_transactions_add_fromto = $this->Tbl_transactions_model->add_fromto($tbl_transactions_id,$_POST);
		$tbl_transactions_random_f8 = $this->Tbl_transactions_model->random_f8($tbl_transactions_id,$_POST);*/
		$if_trn_exist = $this->Tbl_transactions_model->get_Date_shift_party_entry($_POST['shift'], $_POST['party'], $_POST['dateoftrn']);
		//echo '<pre>';print_r($if_trn_exist);die;
		if (!empty($if_trn_exist)) { //echo  'there';die;
			$odata = $this->Tbl_transactions_model->get_transaction_result_total($if_trn_exist[0]['id']);
			//echo '<pre>';print_r($odata); die;
			$uTb_Date_shift_party_entry['Total_Number_amount'] = $ttnumber + $odata['Total_Number_amount'];
			$uTb_Date_shift_party_entry['Total_Akhar_amount'] = $ttakharno + $odata['Total_Akhar_amount'];
			$uTb_Date_shift_party_entry['Total_amount'] = $ttnumber + $ttakharno + $odata['Total_amount'];
			$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->update_Tb_Date_shift_party_entry($if_trn_exist[0]['id'], $uTb_Date_shift_party_entry);
		} else {  //echo  'here';die;
			$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->add_Tb_Date_shift_party_entry($Tb_Date_shift_party_entry);
			//echo $Tb_Date_shift_party_entry_id;	die;
		}

		/*$this->session->set_flashdata('msg', 'Transactions Added');
				 redirect(site_url('/transactions'));*/
		$this->session->set_flashdata('message', 'Transactions Added');
		redirect('/transactions');
		// redirect('/tbl_transactions/edit_trn/'.$tbl_transactions_id);

	}
	function crontoupdate()
	{
		date_default_timezone_set('Asia/Kolkata');
		$param['limit'] = '50';
		$param['offset'] = '0';
		$tbl_ledgers = $this->Tbl_ledger_model->get_all_tbl_ledger_limit($param);
		$date = '2023-02-01';
		foreach ($tbl_ledgers as $key => $val) {
			$hisab = $this->crontoupdateclosingtest($val['id'], $date);
		}
	}
	function crontoupdateclosingtest($mid, $date)
	{
		date_default_timezone_set('Asia/Kolkata');
		//$data['tdledger'] = $this->Tbl_openno_model->updateclosingcron();
		//$arr = [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166];
		//$arr = [2,3,4];
		$count = '';
		//foreach($arr as $key => $aval){		
		$post['ledger_id'] = $mid;
		$post['date'] = $date;
		if ($post['ledger_id'] == '9') {
			$data['tdledger'] = $this->Tbl_openno_model->ledger_till_date_result_today($post);
		} else {
			$data['tdledger'] = $this->Tbl_openno_model->ledger_till_date_result_todaytest($post);
		}
		//echo '<pre>'; print_r($data['tdledger']); echo '</pre>'; die;
		$bta = $btb = 0;
		$finalsum = 0;
		foreach ($data['tdledger']['before'] as $key => $val) {

			$data['shift_name'] = $val['ShiftId'];
			$data['search_party'] = $val['PartyId'];
			$data['todate'] = $val['Date'];
			$data['created_by'] = $this->session->userdata['id'];
			$tdata = $this->Tbl_transactions_model->view_transaction_filter($data);
			//echo '<pre>'; print_r($tdata); echo '</pre>'; //die;
			foreach ($tdata as $keyy => $vall) {

				$finalsum += array_sum(explode(',', $vall['trn_amt']));
				//echo $finalsum.' tt ';
			}
			$bta = $bta + $val['oamnt'];
			$btb = $btb + $val['akmnt'];
			$data['tdledger']['before'][$key]['finalsum'] = $finalsum;
			$data['tdledger']['before'][$key]['tamnt'] = $finalsum;
			//echo '<pre>'; print_r($data['tdledger']['before']); echo '</pre>';
			//$tamnt = explode(',',$val['trn_amt']);
		}
		$bcommission = ceil($finalsum * ($data['tdledger']['today'][0]['Commision'] / 100));

		$bdamount = ceil($bta * $data['tdledger']['today'][0]['DaraRate']);
		$baamount = ceil($btb * $data['tdledger']['today'][0]['AkarRate']);
		if ($data['tdledger']['today'][0]['hissa_select'] == 'y') {
			$bpattiamnt = (($finalsum - ($bcommission + $baamount + $bdamount)) * $data['tdledger']['today'][0]['pattiperc']) / 100;
		} else {
			$bpattiamnt = 0;
		}
		echo ' btamount ' . $finalsum . ' bcommission ' . $bcommission . ' baamount ' . $baamount . ' bdamount ' . $bdamount . ' bpattiamnt ' . $bpattiamnt . '<br>';
		$nbopening = ($finalsum - ($bcommission + $baamount + $bdamount + $bpattiamnt));
		echo $nbopening;
		die;

		//echo $finalsum; die;
		/* 
		foreach($tdledger['before'] as $key => $vall){
	$btamount = $btamount+ $vall['finalsum'];
	$bta = $bta + $vall['oamnt'];
	$btb = $btb + $vall['akmnt'];
	$bcommission = ceil($btamount*($vall['ledgerdara_commision']/100));

$bdamount = ceil($bta*$vall['ledgerdara_rate']);
$baamount = ceil($btb*$vall['ledgerakhar_rate']);
if($vall['hissa_select']=='y'){
	$bpattiamnt = (($btamount-($bcommission+$baamount+$bdamount))*$vall['pattiperc'])/100;
	}
	else{
	$bpattiamnt = 0 ;	 
	}
	//echo 'Date '.$vall['Date'].' btamount '.$btamount.' bcommission '.$bcommission.' baamount '.$baamount.' bdamount '.$bdamount.' bpattiamnt '.$bpattiamnt.'<br>';
	//die;
	$nbopening = ($btamount-($bcommission+$baamount+$bdamount+$bpattiamnt));
echo $vall['Date'].'Date '.$nbopening.' nopening '; echo $bopening.' bopening ';echo $backvoucher.' backvoucher <br>'; 
}
		foreach($data['tdledger']['today'] as $key => $val){
			 $finalsum=0;
		$data['shift_name'] = $val['ShiftId'];
		$data['search_party'] = $val['PartyId'];
		$data['todate'] = $val['Date'];
		$tdata = $this->Tbl_transactions_model->view_transaction_filter_calculate($data);
		//echo '<pre>'; print_r($tdata); echo '</pre>'; //die;
		foreach($tdata as $keyy => $vall){
			
			$finalsum += array_sum(explode(',',$vall['trn_amt']));
			//echo $finalsum.' tt ';
		}
		$data['tdledger']['today'][$key]['finalsum'] = $finalsum;
		$data['tdledger']['today'][$key]['tamnt'] = $finalsum;
		//echo '<pre>'; print_r($tdata); echo '</pre>';
		//$tamnt = explode(',',$val['trn_amt']);
		} */

		//echo '<pre>'; print_r($data['tdledger']); echo '</pre>';
		//die;
		$data['kist'] = $this->Tbl_openno_model->ledger_get_kist($post);
		$netprofit = $this->Tbl_openno_model->ledger_get_netprofit($post);
		$voucher = $this->Tbl_openno_model->ledger_get_voucher($post);
		$backvoucher = $this->Tbl_openno_model->ledger_get_back_voucher($post);
		$tpamnt = $this->Tbl_openno_model->ledger_get_tpamnt($post);
		//echo '<pre>'; print_r($data['kist']); die;
		$np = 0;
		foreach ($netprofit as $key => $val) {
			$np = $np + $val['Net_profit'];
		}
		$tpamntt = 0;
		foreach ($tpamnt as $key => $val) {
			$tpamntt = $tpamntt + (($val['Net_profit'] * $val['TP_perc']) / 100);
		}
		$vc = 0;

		//	echo '<pre>'; print_r($voucher); echo '</pre>'; die;
		foreach ($voucher as $key => $val) {
			if ($post['ledger_id'] == $val['PartyId']) {
				$vc = $vc - $val['Amount'];
			}
			if ($post['ledger_id'] == $val['Collect_By']) {
				$vc = $vc + $val['Amount'];
			}
		}
		$bvc = 0;
		//echo '<pre>'; print_r($post['ledger_id']);print_r($backvoucher); echo '</pre>'; die;
		foreach ($backvoucher as $key => $val) {
			if ($post['ledger_id'] == $val['PartyId']) {
				$bvc = $bvc - $val['Amount'];
			}
			if ($post['ledger_id'] == $val['Collect_By']) {
				$bvc = $bvc + $val['Amount'];
			}
		}
		//echo '<pre>'; print_r($bvc); echo '</pre>'; die;
		//echo $np.' net profit '; echo $vc.' voucher '; echo $tpamntt.' tp amount '; die;
		//$data['ob'] = $np - $vc + $tpamntt;
		//$data['ob'] = $vc;
		//$data['backvoucher'] = $bvc;

		if ((isset($data['kist']) && (!empty($data['kist'])))) {
			$date1 = new DateTime(date('Y-m-d', strtotime($data['kist'][0]['frdate'])));
			$date2 = new DateTime(date('Y-m-d', strtotime($data['tdledger']['today'][0]['Date'])));
			$interval = $date1->diff($date2);
			//echo "difference " . $interval->y . " years, " . $interval->m." months, ".$interval->d." days "; 

			// shows the total amount of days (not divided into years, months and days like above)
			//echo "difference " . $interval->days . " days ";
			if ($interval->days) {
				$kamnt = ($interval->days) * ($data['kist'][0]['kist']);
			} else {
				$kamnt = 0;
			}
		} else {
			$kamnt = 0;
		}

		$tamount = $btamount = 0;
		$ta = $bta = 0;
		$tb = $btb = 0;
		$pattiamnt = $bpattiamnt = 0;
		$opening = $nbopening = $bopening = 0;
		//echo '<pre>'; print_r($data['tdledger']); echo '</pre>'; die;
		if (!empty($data['tdledger']['today'][0]['openingbalance'])) {
			$bopening = $data['tdledger']['today'][0]['openingbalance'];
		}
		/* if(!empty($tdledger['before'][0]['openingbalance'])){
	$bopening = $tdledger['before'][0]['openingbalance'];
}
else{
	$bopening = $tdledger['today'][0]['openingbalance']; 
} */
		//echo $bopening.' ttp ';

		foreach ($data['tdledger']['before'] as $key => $vall) {
			$finalsum = 0;
			$data['shift_name'] = $vall['ShiftId'];
			$data['search_party'] = $vall['PartyId'];
			$data['todate'] = $vall['Date'];
			$data['created_by'] = $this->session->userdata['id'];
			$tdata = $this->Tbl_transactions_model->view_transaction_filter_calculate($data);
			//echo '<pre>'; print_r($tdata); echo '</pre>'; //die;
			foreach ($tdata as $keyy => $valll) {

				$finalsum += array_sum(explode(',', $valll['trn_amt']));
				//echo $finalsum.' tt ';
			}
			$btamount = $btamount + $finalsum;
			$bta = $bta + $vall['oamnt'];
			$btb = $btb + $vall['akmnt'];
			$bcommission = ceil($btamount * ($vall['ledgerdara_commision'] / 100));

			$bdamount = ceil($bta * $vall['ledgerdara_rate']);
			$baamount = ceil($btb * $vall['ledgerakhar_rate']);
			if ($vall['hissa_select'] == 'y') {
				$bpattiamnt = (($btamount - ($bcommission + $baamount + $bdamount)) * $vall['pattiperc']) / 100;
			} else {
				$bpattiamnt = 0;
			}
			//echo 'Date '.$vall['Date'].' btamount '.$btamount.' bcommission '.$bcommission.' baamount '.$baamount.' bdamount '.$bdamount.' bpattiamnt '.$bpattiamnt.'<br>';
			//die;
			$nbopening = ($btamount - ($bcommission + $baamount + $bdamount + $bpattiamnt));
		}
		//echo '<pre>';  print_r($bopening); print_r($bvc); echo '</pre>'; die;
		$bopening = $nbopening + $bopening;
		$first_day_this_month = date('Y-m-01');
		//echo $first_day_this_month.'  '.date('Y-m-d',time()).'<br>'; 
		if ($first_day_this_month ==  date('Y-m-d', time())) {
			$bopening = $data['tdledger']['today'][0]['openingbalance'];
		}
		//echo $nbopening.' nopening '; echo $bopening.' bopening ';echo $bvc.' backvoucher <br>'; die;
		return $bopening;
		//}
	}

	function crontoupdateclosing($mid, $date)
	{
		if ($mid == '168') {
			$getlastclosing = $this->crontoupdateclosingback($mid, $date);
		} else {
			//$getlastclosing = $this->Tbl_openno_model->getopeningbalfinal($date,$mid);
			$getlastclosing = $this->crontoupdateclosingback($mid, $date);
		}
		//echo '<pre>'; print_r($getlastclosing); echo '</pre>'; die;
		/* if(isset($getlastclosing[0]['opening'])){
		return $getlastclosing[0]['opening'];
		}
		else{ */
		return $getlastclosing;
		/* } */
	}

	function crontoupdateclosingback($mid, $date)
	{
		date_default_timezone_set('Asia/Kolkata');
		//$data['tdledger'] = $this->Tbl_openno_model->updateclosingcron();
		//$arr = [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166];
		//$arr = [2,3,4];
		$count = '';
		//foreach($arr as $key => $aval){		
		$post['ledger_id'] = $mid;
		$post['date'] = $date;
		if ($post['ledger_id'] == '135') { //echo 'tt'; die;
			$data['tdledger'] = $this->Tbl_openno_model->ledger_till_date_result_today($post);
		} else {
			$data['tdledger'] = $this->Tbl_openno_model->ledger_till_date_result_today($post);
		}
		//echo '<pre>'; print_r($data['tdledger']); echo '</pre>'; die;
		$finalsum = 0;
		/* foreach($data['tdledger']['before'] as $key => $val){
			 
		$data['shift_name'] = $val['ShiftId'];
		$data['search_party'] = $val['PartyId'];
		$data['todate'] = $val['Date'];
		$data['created_by'] = $this->session->userdata['id'];
		$tdata = $this->Tbl_transactions_model->view_transaction_filter($data);
		//echo '<pre>'; print_r($tdata); echo '</pre>'; //die;
		foreach($tdata as $keyy => $vall){
			
			$finalsum += array_sum(explode(',',$vall['trn_amt']));
			//echo $finalsum.' tt ';
		}
		$data['tdledger']['before'][$key]['finalsum'] = $finalsum;
		$data['tdledger']['before'][$key]['tamnt'] = $finalsum;
		//echo '<pre>'; print_r($data['tdledger']['before']); echo '</pre>';
		//$tamnt = explode(',',$val['trn_amt']);
		} */
		$finalsum = 0;
		foreach ($data['tdledger']['today'] as $key => $val) {

			$data['shift_name'] = $val['ShiftId'];
			$data['search_party'] = $val['PartyId'];
			$data['todate'] = $val['Date'];
			$tdata = $this->Tbl_transactions_model->view_transaction_filter_calculate($data);
			//echo '<pre>'; print_r($tdata); echo '</pre>'; //die;
			foreach ($tdata as $keyy => $vall) {

				$finalsum += array_sum(explode(',', $vall['trn_amt']));
				//echo $finalsum.' tt ';
			}
			$data['tdledger']['today'][$key]['finalsum'] = $finalsum;
			$data['tdledger']['today'][$key]['tamnt'] = $finalsum;
			//echo '<pre>'; print_r($tdata); echo '</pre>';
			//$tamnt = explode(',',$val['trn_amt']);
		}

		//echo '<pre>'; print_r($data); echo '</pre>';
		//die;
		$data['kist'] = $this->Tbl_openno_model->ledger_get_kist($post);
		$netprofit = $this->Tbl_openno_model->ledger_get_netprofit($post);
		$voucher = $this->Tbl_openno_model->ledger_get_voucher($post);
		$backvoucher = $this->Tbl_openno_model->ledger_get_back_voucher($post);
		$tpamnt = $this->Tbl_openno_model->ledger_get_tpamnt($post);
		//echo '<pre>'; print_r($data['kist']); die;
		$np = 0;
		foreach ($netprofit as $key => $val) {
			$np = $np + $val['Net_profit'];
		}
		$tpamntt = 0;
		foreach ($tpamnt as $key => $val) {
			$tpamntt = $tpamntt + (($val['Net_profit'] * $val['TP_perc']) / 100);
		}
		$vc = 0;

		//	echo '<pre>'; print_r($voucher); echo '</pre>'; die;
		foreach ($voucher as $key => $val) {
			if ($post['ledger_id'] == $val['PartyId']) {
				$vc = $vc - $val['Amount'];
			}
			if ($post['ledger_id'] == $val['Collect_By']) {
				$vc = $vc + $val['Amount'];
			}
		}
		$bvc = 0;
		//echo '<pre>'; print_r($post['ledger_id']);print_r($backvoucher); echo '</pre>'; die;
		foreach ($backvoucher as $key => $val) {
			if ($post['ledger_id'] == $val['PartyId']) {
				$bvc = $bvc - $val['Amount'];
			}
			if ($post['ledger_id'] == $val['Collect_By']) {
				$bvc = $bvc + $val['Amount'];
			}
		}
		//echo '<pre>'; print_r($bvc); echo '</pre>'; die;
		//echo $np.' net profit '; echo $vc.' voucher '; echo $tpamntt.' tp amount '; die;
		//$data['ob'] = $np - $vc + $tpamntt;
		//$data['ob'] = $vc;
		//$data['backvoucher'] = $bvc;

		if ((isset($data['kist']) && (!empty($data['kist'])))) {
			$date1 = new DateTime(date('Y-m-d', strtotime($data['kist'][0]['frdate'])));
			$date2 = new DateTime(date('Y-m-d', strtotime($data['tdledger']['today'][0]['Date'])));
			$interval = $date1->diff($date2);
			//echo "difference " . $interval->y . " years, " . $interval->m." months, ".$interval->d." days "; 

			// shows the total amount of days (not divided into years, months and days like above)
			//echo "difference " . $interval->days . " days ";
			if ($interval->days) {
				$kamnt = ($interval->days) * ($data['kist'][0]['kist']);
			} else {
				$kamnt = 0;
			}
		} else {
			$kamnt = 0;
		}

		$tamount = $btamount = 0;
		$ta = $bta = 0;
		$tb = $btb = 0;
		$pattiamnt = $bpattiamnt = 0;
		$opening = $nbopening = $bopening = 0;
		//echo '<pre>'; print_r($data['tdledger']); echo '</pre>'; die;
		if (!empty($data['tdledger']['today'][0]['openingbalance'])) {
			$bopening = $data['tdledger']['today'][0]['openingbalance'];
		}
		/* if(!empty($tdledger['before'][0]['openingbalance'])){
	$bopening = $tdledger['before'][0]['openingbalance'];
}
else{
	$bopening = $tdledger['today'][0]['openingbalance']; 
} */
		//echo $bopening.' ttp ';

		foreach ($data['tdledger']['before'] as $key => $vall) {
			$finalsum = 0;
			$data['shift_name'] = $vall['ShiftId'];
			$data['search_party'] = $vall['PartyId'];
			$data['todate'] = $vall['Date'];
			$data['created_by'] = $this->session->userdata['id'];
			$tdata = $this->Tbl_transactions_model->view_transaction_filter($data);
			//echo '<pre>'; print_r($this->Tbl_transactions_model->view_transaction_filter($data)); echo '</pre>'; die;
			foreach ($tdata as $keyy => $valll) {

				$finalsum += array_sum(explode(',', $valll['trn_amt']));
				//echo $finalsum.' tt ';
			}
			$btamount = $btamount + $finalsum;
			$bta = $bta + $vall['oamnt'];
			$btb = $btb + $vall['akmnt'];
			$bcommission = ceil($btamount * ((float)$vall['ledgerdara_commision'] / 100));

			$bdamount = ceil($bta * $vall['ledgerdara_rate']);
			$baamount = ceil($btb * $vall['ledgerakhar_rate']);
			if ($vall['hissa_select'] == 'y') {
				$bpattiamnt = (($btamount - ($bcommission + $baamount + $bdamount)) * $vall['pattiperc']) / 100;
			} else {
				$bpattiamnt = 0;
			}
			//echo 'Date '.$vall['Date'].' btamount '.$btamount.' bcommission '.$bcommission.' baamount '.$baamount.' bdamount '.$bdamount.' bpattiamnt '.$bpattiamnt.'<br>';
			//die;
			$nbopening = ($btamount - ($bcommission + $baamount + $bdamount + $bpattiamnt));
		}
		//echo '<pre>';  print_r($bopening); print_r($bvc); echo '</pre>'; die;
		$bopening = $nbopening + $bopening + $bvc;
		$first_day_this_month = date('Y-m-01');
		//echo $first_day_this_month.'  '.date('Y-m-d',time()).'<br>'; 
		if ($first_day_this_month ==  date('Y-m-d', time())) { //echo 'ttp';
			//$bopening = $data['tdledger']['today'][0]['openingbalance'];
			$ledgerbal = $this->Tbl_transactions_model->thirdpartydetails($post['ledger_id']);
			//echo '<pre>'; print_r($ledgerbal); echo '</pre>'; die;
			$bopening = $ledgerbal['openingbalance'];
		}
		//echo $bopening; die;
		//die;
		//echo $nbopening.' nopening '; echo $bopening.' bopening ';echo $bvc.' backvoucher'.$vc.' voucher <br>'; die;
		return $bopening;
		//}
	}

	function add_transaction_final()
	{
		//echo '<pre>'; print_r($_POST); echo '</pre>'; die;
		foreach ($_POST as $key => $val) {
			if ($val == '') {
				$_POST[$key] = 0;
			}
		}
		$trn_amount = $_POST['trn_amount'];
		//echo '<pre>'; print_r($_POST); echo '</pre>';
		$f2tno = array_sum($trn_amount);
		$f4tno = $_POST['tamount'];
		$tnocross = $_POST['total_amount_cross'];
		$tnofromto = $_POST['total_amount_fromto'];
		$f8tno = count(explode(' ', $_POST['dara_f8'])) * ($_POST['dara_amount_f8']);
		$f8akharbahartno = (strlen($_POST['akhar_bahar_f8'])) * ($_POST['amount_akahr_bahar_f8']);
		$f8akharandertno = (strlen($_POST['akahr_andar_f8'])) * ($_POST['amount_akahr_andar_f8']);
		$ttnumber = $f2tno + $f4tno + $tnofromto + $f8tno + $tnocross;
		$ttakharno =  $f8akharbahartno + $f8akharandertno;
		$mastr['shift_id'] = $_POST['shift'];
		$mastr['party_id'] = $_POST['party'];
		$mastr['t_date'] = date('Y-m-d', strtotime($_POST['dateoftrn']));
		$mastr['total_number_amount'] = $ttnumber;
		$mastr['total_akhar_amount'] = $ttakharno;

		$tbl_ledger_elements = $this->Tbl_ledger_model->get_tbl_ledger($_POST['party']);
		//echo '<pre>'; print_r($tbl_ledger_elements); echo '</pre>'; die;
		$Tb_Date_shift_party_entry['DaraRate'] = $tbl_ledger_elements['dara_rate'];
		$Tb_Date_shift_party_entry['Commision'] = $tbl_ledger_elements['dara_commision'];
		$Tb_Date_shift_party_entry['AkarRate'] = $tbl_ledger_elements['akhar_rate'];
		$Tb_Date_shift_party_entry['Commission'] = $tbl_ledger_elements['akhar_commission'];
		$Tb_Date_shift_party_entry['Rebait'] = $tbl_ledger_elements['rebate'];
		$Tb_Date_shift_party_entry['TP_person'] = $tbl_ledger_elements['tp_party_id'];
		$Tb_Date_shift_party_entry['TP_perc'] = $tbl_ledger_elements['tppercentage'];
		$Tb_Date_shift_party_entry['ShiftId'] = $_POST['shift'];
		$Tb_Date_shift_party_entry['PartyId'] = $_POST['party'];
		$Tb_Date_shift_party_entry['Date'] = date('Y-m-d', strtotime($_POST['dateoftrn']));
		$Tb_Date_shift_party_entry['Total_Number_amount'] = $ttnumber;
		$Tb_Date_shift_party_entry['Total_Akhar_amount'] = $ttakharno;
		$Tb_Date_shift_party_entry['Total_amount'] = $ttnumber + $ttakharno;
		/*echo '<pre>'; print_r($_POST['trn_number']); echo '</pre>';
		$_POST['trn_number'] = array_map(
    function($v) { if ($v == '00') $v = '100'; return $v; },
    $_POST['trn_number']
);
$_POST['number'] = array_map(
    function($v) { if ($v == '00') $v = '100'; return $v; },
    $_POST['number']
);
if($_POST['fromto_from']=='00'){
	$_POST['fromto_from'] = 100;
}
if($_POST['fromto_to']=='00'){
	$_POST['fromto_to'] = 100;
}
	//	$num_f2 = $_POST['trn_number'];
			//$num_f2 = array_map($this->replaceHundreds, $num_f2);
		echo '<pre>'; print_r($_POST['trn_number']); echo '</pre>'; die;*/
		$tbl_transactions_id = $this->Tbl_transactions_model->add_tbl_transaction($mastr); //die;
		$tbl_transactions_only_id = $this->Tbl_transactions_model->add_tbl_only_transaction($tbl_transactions_id, $_POST);
		$tbl_transactions_rndomf4 = $this->Tbl_transactions_model->add_tbl_randomf4($tbl_transactions_id, $_POST);
		$tbl_transactions_cross = $this->Tbl_transactions_model->add_cross($tbl_transactions_id, $_POST);
		$tbl_transactions_add_fromto = $this->Tbl_transactions_model->add_fromto($tbl_transactions_id, $_POST);
		$tbl_transactions_random_f8 = $this->Tbl_transactions_model->random_f8($tbl_transactions_id, $_POST);
		$if_trn_exist = $this->Tbl_transactions_model->get_Date_shift_party_entry($_POST['shift'], $_POST['party'], $_POST['dateoftrn']);
		//echo '<pre>';print_r($if_trn_exist);die;
		if (!empty($if_trn_exist)) { //echo  'there';die;
			$odata = $this->Tbl_transactions_model->get_transaction_result_total($if_trn_exist[0]['id']);
			//echo '<pre>';print_r($odata); die;
			$uTb_Date_shift_party_entry['Total_Number_amount'] = $ttnumber + $odata['Total_Number_amount'];
			$uTb_Date_shift_party_entry['Total_Akhar_amount'] = $ttakharno + $odata['Total_Akhar_amount'];
			$uTb_Date_shift_party_entry['Total_amount'] = $ttnumber + $ttakharno + $odata['Total_amount'];
			$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->update_Tb_Date_shift_party_entry($if_trn_exist[0]['id'], $uTb_Date_shift_party_entry);
		} else {  //echo  'here';die;
			$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->add_Tb_Date_shift_party_entry($Tb_Date_shift_party_entry);
		}

		/*$this->session->set_flashdata('msg', 'Transactions Added');
				 redirect(site_url('/transactions'));*/
		$this->session->set_flashdata('message', 'Transactions Added');
		redirect('/transactions');
		// redirect('/tbl_transactions/edit_trn/'.$tbl_transactions_id);

	}

	function edit_transaction_final_may($id)
	{
		//echo '<pre>'; print_r($_POST); echo '</pre>'; die;
		foreach ($_POST as $key => $val) {
			if ($val == '') {
				$_POST[$key] = 0;
			}
		}
		$trn_amount = $_POST['trn_amount'];
		//echo '<pre>'; print_r($_POST); echo '</pre>';
		$f2tno = array_sum($trn_amount);
		$f4tno = $_POST['tamount'];
		$tnocross = $_POST['total_amount_cross'];
		$tnofromto = $_POST['total_amount_fromto'];
		$f8tno = count(explode(' ', $_POST['dara_f8'])) * ($_POST['dara_amount_f8']);
		$f8akharbahartno = (strlen($_POST['akhar_bahar_f8'])) * ($_POST['amount_akahr_bahar_f8']);
		$f8akharandertno = (strlen($_POST['akahr_andar_f8'])) * ($_POST['amount_akahr_andar_f8']);
		//$ttnumber = $f2tno + $f4tno + $tnofromto + $f8tno+$tnocross;
		$ttnumber = $_POST['ttamntt'];
		$ttakharno =  $f8akharbahartno + $f8akharandertno;
		//$updateopening = $this->crontoupdateclosing($_POST['party'],$_POST['dateoftrn']);
		//echo $updateopening; die;	
		//echo $Tb_Date_shift_party_entry_id; 
		// die;
		//$closing = $this->Tbl_transactions_model->updateclosing($updateopening,$_POST['party'],$_POST['dateoftrn']);
		//$mastr['shift_id']= $_POST['shift'];
		//$mastr['party_id']= $_POST['party'];
		//$mastr['t_date']= date('Y-m-d',strtotime($_POST['dateoftrn']));
		$mastr['total_number_amount'] = $ttnumber;
		$mastr['total_akhar_amount'] = $ttakharno;

		$tbl_ledger_elements = $this->Tbl_ledger_model->get_tbl_ledger($_POST['party']);
		//echo '<pre>'; print_r($tbl_ledger_elements); echo '</pre>'; die;
		$Tb_Date_shift_party_entry['DaraRate'] = $tbl_ledger_elements['dara_rate'];
		$Tb_Date_shift_party_entry['Commision'] = $tbl_ledger_elements['dara_commision'];
		$Tb_Date_shift_party_entry['AkarRate'] = $tbl_ledger_elements['akhar_rate'];
		$Tb_Date_shift_party_entry['Commission'] = $tbl_ledger_elements['akhar_commission'];
		$Tb_Date_shift_party_entry['Rebait'] = $tbl_ledger_elements['rebate'];
		$Tb_Date_shift_party_entry['TP_person'] = $tbl_ledger_elements['tp_party_id'];
		$Tb_Date_shift_party_entry['TP_perc'] = $tbl_ledger_elements['tppercentage'];
		$Tb_Date_shift_party_entry['ShiftId'] = $_POST['shift'];
		$Tb_Date_shift_party_entry['PartyId'] = $_POST['party'];
		$Tb_Date_shift_party_entry['Date'] = date('Y-m-d', strtotime($_POST['dateoftrn']));
		$Tb_Date_shift_party_entry['Total_Number_amount'] = $ttnumber;
		$Tb_Date_shift_party_entry['Total_Akhar_amount'] = $ttakharno;
		$Tb_Date_shift_party_entry['Total_amount'] = $ttnumber + $ttakharno;

		$tbl_transactions_id = $this->Tbl_transactions_model->edit_tbl_transaction($mastr); //die;
		//$tbl_transactions_only_id = $this->Tbl_transactions_model->add_tbl_only_transaction_may($tbl_transactions_id,$_POST);
		/* //commented for only number amount entry//	$tbl_transactions_rndomf4 = $this->Tbl_transactions_model->add_tbl_randomf4($tbl_transactions_id,$_POST);
		$tbl_transactions_cross = $this->Tbl_transactions_model->add_cross($tbl_transactions_id,$_POST);
		$tbl_transactions_add_fromto = $this->Tbl_transactions_model->add_fromto($tbl_transactions_id,$_POST);
		$tbl_transactions_random_f8 = $this->Tbl_transactions_model->random_f8($tbl_transactions_id,$_POST);*/
		$if_trn_exist = $this->Tbl_transactions_model->get_Date_shift_party_entry($_POST['shift'], $_POST['party'], $_POST['dateoftrn']);
		//echo '<pre>';print_r($if_trn_exist);die;
		if (!empty($if_trn_exist)) { //echo  'there';die;
			$odata = $this->Tbl_transactions_model->get_transaction_result_total($if_trn_exist[0]['id']);
			//echo '<pre>';print_r($odata); die;
			$uTb_Date_shift_party_entry['Total_Number_amount'] = $ttnumber + $odata['Total_Number_amount'];
			$uTb_Date_shift_party_entry['Total_Akhar_amount'] = $ttakharno + $odata['Total_Akhar_amount'];
			$uTb_Date_shift_party_entry['Total_amount'] = $ttnumber + $ttakharno + $odata['Total_amount'];
			$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->update_Tb_Date_shift_party_entry($if_trn_exist[0]['id'], $uTb_Date_shift_party_entry);
		} else {  //echo  'here';die;
			$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->add_Tb_Date_shift_party_entry($Tb_Date_shift_party_entry);
		}
		/*$this->session->set_flashdata('msg', 'Transactions Added');
				 redirect(site_url('/transactions'));*/
		$this->session->set_flashdata('message', 'Transactions Updated');
		redirect('/transactions');
		// redirect('/tbl_transactions/edit_trn/'.$tbl_transactions_id);

	}
	function updateallclosing($date)
	{
		//echo $date;
		$prevdate = date('Y-m-d', (strtotime('0 day', strtotime($date))));
		$prevdayopening = $this->Tbl_openno_model->get_all_opening_by_date($prevdate);
		echo '<pre>';
		print_r($prevdayopening);
		echo '</pre>';
		//$updateopening = $this->crontoupdateclosing($_POST['party'],$_POST['dateoftrn']);

		//$closing = $this->Tbl_transactions_model->updateclosing($updateopening,$_POST['party'],$_POST['dateoftrn']);
	}

	function edit_transaction_final($id)
	{
		//echo '<pre>'; echo $id;  print_r($_POST); echo '</pre>'; die;
		foreach ($_POST as $key => $val) {
			if ($val == '') {
				$_POST[$key] = 0;
			}
		}
		foreach ($_POST['trn_number'] as $key => $val) {
			if ($val == '') {
				unset($_POST['trn_number'][$key]);
				unset($_POST['trn_amount'][$key]);
			}
		}
		foreach ($_POST['trn_amount'] as $key => $val) {
			if ($val == '') {
				unset($_POST['trn_number'][$key]);
				unset($_POST['trn_amount'][$key]);
			}
		}
		$updateopening = $this->crontoupdateclosing($_POST['party'], $_POST['dateoftrn']);
		//echo $updateopening; die;	
		//echo $Tb_Date_shift_party_entry_id; 
		// die;
		$closing = $this->Tbl_transactions_model->updateclosing($updateopening, $_POST['party'], $_POST['dateoftrn']);
		$trn_amount = $_POST['trn_amount'] =  array_filter($_POST['trn_amount']);
		$_POST['trn_number'] = array_filter($_POST['trn_number']);
		//echo '<pre>'; print_r($_POST); echo '</pre>'; die;
		$f2tno = array_sum($trn_amount);
		$f4tno = $_POST['tamount'];
		$tnocross = $_POST['total_amount_cross'];
		$tnofromto = $_POST['total_amount_fromto'];
		$f8tno = count(explode(' ', $_POST['dara_f8'])) * ($_POST['dara_amount_f8']);
		$f8akharbahartno = (strlen($_POST['akhar_bahar_f8'])) * ($_POST['amount_akahr_bahar_f8']);
		$f8akharandertno = (strlen($_POST['akahr_andar_f8'])) * ($_POST['amount_akahr_andar_f8']);
		$ttnumber = $f2tno + $f4tno + $tnofromto + $f8tno + $tnocross;
		$ttakharno =  $f8akharbahartno + $f8akharandertno;
		$mastr['shift_id'] = $_POST['shift'];
		$mastr['party_id'] = $_POST['party'];
		$mastr['t_date'] = date('Y-m-d', strtotime($_POST['dateoftrn']));
		$mastr['total_number_amount'] = $ttnumber;
		$mastr['total_akhar_amount'] = $ttakharno;

		$tbl_ledger_elements = $this->Tbl_ledger_model->get_tbl_ledger($_POST['party']);
		//echo '<pre>'; print_r($tbl_ledger_elements); echo '</pre>'; die;
		$Tb_Date_shift_party_entry['DaraRate'] = $tbl_ledger_elements['dara_rate'];
		$Tb_Date_shift_party_entry['Commision'] = $tbl_ledger_elements['dara_commision'];
		$Tb_Date_shift_party_entry['AkarRate'] = $tbl_ledger_elements['akhar_rate'];
		$Tb_Date_shift_party_entry['Commission'] = $tbl_ledger_elements['akhar_commission'];
		$Tb_Date_shift_party_entry['Rebait'] = $tbl_ledger_elements['rebate'];
		$Tb_Date_shift_party_entry['TP_person'] = $tbl_ledger_elements['tp_party_id'];
		$Tb_Date_shift_party_entry['TP_perc'] = $tbl_ledger_elements['tppercentage'];
		$Tb_Date_shift_party_entry['ShiftId'] = $_POST['shift'];
		$Tb_Date_shift_party_entry['PartyId'] = $_POST['party'];
		$Tb_Date_shift_party_entry['Date'] = date('Y-m-d', strtotime($_POST['dateoftrn']));
		$Tb_Date_shift_party_entry['Total_Number_amount'] = $ttnumber;
		$Tb_Date_shift_party_entry['Total_Akhar_amount'] = $ttakharno;
		$Tb_Date_shift_party_entry['Total_amount'] = $ttnumber + $ttakharno;

		//echo '<pre>'; print_r($mastr); echo '</pre>'; die;
		$tbl_transactions_id = $this->Tbl_transactions_model->edit_tbl_transaction($id, $mastr); //die;
		$tbl_transactions_only_id = $this->Tbl_transactions_model->edit_tbl_only_transaction_may($id, $_POST);
		//$tbl_transactions_only_id = $this->Tbl_transactions_model->edit_tbl_only_transaction($id,$_POST);
		//$tbl_transactions_rndomf4 = $this->Tbl_transactions_model->edit_tbl_randomf4($id,$_POST);
		//$tbl_transactions_cross = $this->Tbl_transactions_model->edit_cross($id,$_POST);
		//$tbl_transactions_add_fromto = $this->Tbl_transactions_model->edit_fromto($id,$_POST);
		//$tbl_transactions_random_f8 = $this->Tbl_transactions_model->edit_random_f8($id,$_POST);
		//$if_trn_exist = $this->Tbl_transactions_model->get_Date_shift_party_entry($_POST['shift'],$_POST['party'],$_POST['dateoftrn']);
		//echo '<pre>';print_r($if_trn_exist);die;
		//if(!empty($if_trn_exist)){ //echo  'there';die;
		$if_trn_exist = $this->Tbl_transactions_model->get_Date_shift_party_entry($_POST['shift'], $_POST['party'], $_POST['dateoftrn']);
		//echo '<pre>';print_r($if_trn_exist);//die;
		if (!empty($if_trn_exist)) { //echo  'there';die;
			$odata = $this->Tbl_transactions_model->get_transaction_result_total($if_trn_exist[0]['id']);
			//echo '<pre>';print_r($odata); die;
			//$uTb_Date_shift_party_entry['Total_Number_amount']=$ttnumber+$odata['Total_Number_amount'];
			//$uTb_Date_shift_party_entry['Total_Akhar_amount']=$ttakharno+$odata['Total_Akhar_amount'];
			//$uTb_Date_shift_party_entry['Total_amount']=$ttnumber+$ttakharno+$odata['Total_amount'];
			$uTb_Date_shift_party_entry['Total_Number_amount'] = $ttnumber;
			$uTb_Date_shift_party_entry['Total_Akhar_amount'] = $ttakharno;
			$uTb_Date_shift_party_entry['Total_amount'] = $ttnumber + $ttakharno;
			//echo '<pre>'; print_r($uTb_Date_shift_party_entry); echo '</pre>'; die;
			$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->update_Tb_Date_shift_party_entry($if_trn_exist[0]['id'], $uTb_Date_shift_party_entry);
		} else {  //echo  'here';die;
			$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->add_Tb_Date_shift_party_entry($Tb_Date_shift_party_entry);
		}

		//$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->update_Tb_Date_shift_party_entry($id,$uTb_Date_shift_party_entry);
		//	}

		/*$this->session->set_flashdata('msg', 'Transactions Added');
				 redirect(site_url('/transactions'));*/
		$this->session->set_flashdata('message', 'Transaction Changed!!');
		redirect('/view_transactions');
		//$data['_view'] = 'tbl_transactions/index';
		// $this->load->view('layouts/main',$data);
		/*echo $tbl_transactions_id .'<br>';
		echo $tbl_transactions_only_id .'<br>';
		echo $tbl_transactions_rndomf4 .'<br>';
		echo $Tb_Date_shift_party_entry_id.'<br>';
		echo $this->db->last_query();*/
		//echo $ttnumber.'<br>';
		//echo $ttakharno.'<br>';
		//echo '<pre>';print_r($_POST);die;


	}
	function edit_transaction_final_master($id)
	{
		//echo '<pre>'; echo $id;  print_r($_POST); echo '</pre>'; die;
		foreach ($_POST as $key => $val) {
			if ($val == '') {
				$_POST[$key] = 0;
			}
		}
		foreach ($_POST['trn_number'] as $key => $val) {
			if ($val == '') {
				unset($_POST['trn_number'][$key]);
				unset($_POST['trn_amount'][$key]);
			}
		}
		foreach ($_POST['trn_amount'] as $key => $val) {
			if ($val == '') {
				unset($_POST['trn_number'][$key]);
				unset($_POST['trn_amount'][$key]);
			}
		}
		$updateopening = $this->crontoupdateclosing($_POST['party'], $_POST['dateoftrn']);
		//echo $updateopening; die;	
		//echo $Tb_Date_shift_party_entry_id; 
		// die;
		$closing = $this->Tbl_transactions_model->updateclosing($updateopening, $_POST['party'], $_POST['dateoftrn']);
		$trn_amount = $_POST['trn_amount'] =  array_filter($_POST['trn_amount']);
		$_POST['trn_number'] = array_filter($_POST['trn_number']);
		//echo '<pre>'; print_r($_POST); echo '</pre>'; die;
		$f2tno = array_sum($trn_amount);
		$f4tno = $_POST['tamount'];
		$tnocross = $_POST['total_amount_cross'];
		$tnofromto = $_POST['total_amount_fromto'];
		$f8tno = count(explode(' ', $_POST['dara_f8'])) * ($_POST['dara_amount_f8']);
		$f8akharbahartno = (strlen($_POST['akhar_bahar_f8'])) * ($_POST['amount_akahr_bahar_f8']);
		$f8akharandertno = (strlen($_POST['akahr_andar_f8'])) * ($_POST['amount_akahr_andar_f8']);
		$ttnumber = $f2tno + $f4tno + $tnofromto + $f8tno + $tnocross;
		$ttakharno =  $f8akharbahartno + $f8akharandertno;
		$mastr['shift_id'] = $_POST['shift'];
		$mastr['party_id'] = $_POST['party'];
		$mastr['t_date'] = date('Y-m-d', strtotime($_POST['dateoftrn']));
		$mastr['total_number_amount'] = $ttnumber;
		$mastr['total_akhar_amount'] = $ttakharno;

		$tbl_ledger_elements = $this->Tbl_ledger_model->get_tbl_ledger($_POST['party']);
		//echo '<pre>'; print_r($tbl_ledger_elements); echo '</pre>'; die;
		$Tb_Date_shift_party_entry['DaraRate'] = $tbl_ledger_elements['dara_rate'];
		$Tb_Date_shift_party_entry['Commision'] = $tbl_ledger_elements['dara_commision'];
		$Tb_Date_shift_party_entry['AkarRate'] = $tbl_ledger_elements['akhar_rate'];
		$Tb_Date_shift_party_entry['Commission'] = $tbl_ledger_elements['akhar_commission'];
		$Tb_Date_shift_party_entry['Rebait'] = $tbl_ledger_elements['rebate'];
		$Tb_Date_shift_party_entry['TP_person'] = $tbl_ledger_elements['tp_party_id'];
		$Tb_Date_shift_party_entry['TP_perc'] = $tbl_ledger_elements['tppercentage'];
		$Tb_Date_shift_party_entry['ShiftId'] = $_POST['shift'];
		$Tb_Date_shift_party_entry['PartyId'] = $_POST['party'];
		$Tb_Date_shift_party_entry['Date'] = date('Y-m-d', strtotime($_POST['dateoftrn']));
		$Tb_Date_shift_party_entry['Total_Number_amount'] = $ttnumber;
		$Tb_Date_shift_party_entry['Total_Akhar_amount'] = $ttakharno;
		$Tb_Date_shift_party_entry['Total_amount'] = $ttnumber + $ttakharno;

		//echo '<pre>'; print_r($mastr); echo '</pre>'; die;
		$tbl_transactions_id = $this->Tbl_transactions_model->edit_tbl_transaction($id, $mastr); //die;
		$tbl_transactions_only_id = $this->Tbl_transactions_model->edit_tbl_only_transaction_may($id, $_POST);
		//$tbl_transactions_only_id = $this->Tbl_transactions_model->edit_tbl_only_transaction($id,$_POST);
		//$tbl_transactions_rndomf4 = $this->Tbl_transactions_model->edit_tbl_randomf4($id,$_POST);
		//$tbl_transactions_cross = $this->Tbl_transactions_model->edit_cross($id,$_POST);
		//$tbl_transactions_add_fromto = $this->Tbl_transactions_model->edit_fromto($id,$_POST);
		//$tbl_transactions_random_f8 = $this->Tbl_transactions_model->edit_random_f8($id,$_POST);
		//$if_trn_exist = $this->Tbl_transactions_model->get_Date_shift_party_entry($_POST['shift'],$_POST['party'],$_POST['dateoftrn']);
		//echo '<pre>';print_r($if_trn_exist);die;
		//if(!empty($if_trn_exist)){ //echo  'there';die;
		$if_trn_exist = $this->Tbl_transactions_model->get_Date_shift_party_entry($_POST['shift'], $_POST['party'], $_POST['dateoftrn']);
		//echo '<pre>';print_r($if_trn_exist);//die;
		if (!empty($if_trn_exist)) { //echo  'there';die;
			$odata = $this->Tbl_transactions_model->get_transaction_result_total($if_trn_exist[0]['id']);
			//echo '<pre>';print_r($odata); die;
			//$uTb_Date_shift_party_entry['Total_Number_amount']=$ttnumber+$odata['Total_Number_amount'];
			//$uTb_Date_shift_party_entry['Total_Akhar_amount']=$ttakharno+$odata['Total_Akhar_amount'];
			//$uTb_Date_shift_party_entry['Total_amount']=$ttnumber+$ttakharno+$odata['Total_amount'];
			$uTb_Date_shift_party_entry['Total_Number_amount'] = $ttnumber;
			$uTb_Date_shift_party_entry['Total_Akhar_amount'] = $ttakharno;
			$uTb_Date_shift_party_entry['Total_amount'] = $ttnumber + $ttakharno;
			//echo '<pre>'; print_r($uTb_Date_shift_party_entry); echo '</pre>'; die;
			$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->update_Tb_Date_shift_party_entry($if_trn_exist[0]['id'], $uTb_Date_shift_party_entry);
		} else {  //echo  'here';die;
			$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->add_Tb_Date_shift_party_entry($Tb_Date_shift_party_entry);
		}

		//$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->update_Tb_Date_shift_party_entry($id,$uTb_Date_shift_party_entry);
		//	}

		/*$this->session->set_flashdata('msg', 'Transactions Added');
				 redirect(site_url('/transactions'));*/
		$this->session->set_flashdata('message', 'Transaction Changed!!');
		redirect('/view_transactions');
		//$data['_view'] = 'tbl_transactions/index';
		// $this->load->view('layouts/main',$data);
		/*echo $tbl_transactions_id .'<br>';
		echo $tbl_transactions_only_id .'<br>';
		echo $tbl_transactions_rndomf4 .'<br>';
		echo $Tb_Date_shift_party_entry_id.'<br>';
		echo $this->db->last_query();*/
		//echo $ttnumber.'<br>';
		//echo $ttakharno.'<br>';
		//echo '<pre>';print_r($_POST);die;


	}
	function update_trn()
	{
		//print_r($_POST);die;
		$tbl_transactions_id = $_POST['master_id'];
		if ($tbl_transactions_id) { // echo $tbl_transactions_id; die; 
			$tbl_master_transactions_id = $this->Tbl_transactions_model->update_tbl_only_transaction($tbl_transactions_id, $_POST);
			//echo '<pre>'; print_r($tbl_master_transactions_id);  echo '</pre>'; die;
			if ($tbl_master_transactions_id['master_id']) {
				return $tbl_master_transactions_id;
			}
		} else {
			return false;
		}
	}

	function add_randomf4()
	{
		//print_r($_POST);die;
		//$_POST['shift']='';
		$tbl_transactions_id = $this->Tbl_transactions_model->add_tbl_transaction($_POST);
		//unset($_POST['shift']);
		if ($tbl_transactions_id) { // echo $tbl_transactions_id; die;
			//echo '<pre>'; print_r($_POST); echo '</pre>'; die;
			$tbl_master_transactions_id = $this->Tbl_transactions_model->add_tbl_randomf4($tbl_transactions_id, $_POST);
			if ($tbl_master_transactions_id) {
				$this->session->set_flashdata('msg', 'Random Form Added');
				redirect('/transactions#profile');
			}
		} else {
			return false;
		}
	}
	function update_randomf4()
	{
		//print_r($_POST);die;
		//$_POST['shift']='';
		$tbl_transactions_id = $_POST['master_id'];
		//unset($_POST['shift']);
		if ($tbl_transactions_id) { // echo $tbl_transactions_id; die; 
			$tbl_master_transactions_id = $this->Tbl_transactions_model->add_tbl_randomf4($tbl_transactions_id, $_POST);
			if ($tbl_master_transactions_id) {
				$this->session->set_flashdata('msg', 'Random Form Added');
				redirect('/transactions#profile');
			}
		} else {
			return false;
		}
	}
	function add_cross()
	{
		//print_r($_POST);die;
		//$_POST['shift']='';
		$tbl_transactions_id = $this->Tbl_transactions_model->add_tbl_transaction($_POST);
		//unset($_POST['shift']);
		if ($tbl_transactions_id) { // echo $tbl_transactions_id; die; 
			$tbl_master_transactions_id = $this->Tbl_transactions_model->add_cross($tbl_transactions_id, $_POST);
			if ($tbl_master_transactions_id) {
				$this->session->set_flashdata('msg', 'Cross Form Added');
				redirect('/transactions#cross');
			}
		} else {
			return false;
		}
	}
	function update_cross()
	{
		//print_r($_POST);die;
		//$_POST['shift']='';
		$tbl_transactions_id = $_POST['master_id'];
		//unset($_POST['shift']);
		if ($tbl_transactions_id) { // echo $tbl_transactions_id; die; 
			$tbl_master_transactions_id = $this->Tbl_transactions_model->add_cross($tbl_transactions_id, $_POST);
			if ($tbl_master_transactions_id) {
				$this->session->set_flashdata('msg', 'Cross Form Added');
				redirect('/transactions#cross');
			}
		} else {
			return false;
		}
	}
	function add_fromto()
	{
		//print_r($_POST);die;
		//$_POST['shift']='';
		$tbl_transactions_id = $this->Tbl_transactions_model->add_tbl_transaction($_POST);
		//unset($_POST['shift']);
		if ($tbl_transactions_id) { // echo $tbl_transactions_id; die; 
			$tbl_master_transactions_id = $this->Tbl_transactions_model->add_fromto($tbl_transactions_id, $_POST);
			if ($tbl_master_transactions_id) {
				//$this->session->set_flashdata('msg', 'From To Form Added');
				redirect('/transactions#From-To');
			}
		} else {
			return false;
		}
	}
	function update_fromto()
	{
		//print_r($_POST);die;
		//$_POST['shift']='';
		$tbl_transactions_id = $_POST['master_id'];
		//unset($_POST['shift']);
		if ($tbl_transactions_id) { // echo $tbl_transactions_id; die; 
			$tbl_master_transactions_id = $this->Tbl_transactions_model->add_fromto($tbl_transactions_id, $_POST);
			if ($tbl_master_transactions_id) {
				//$this->session->set_flashdata('msg', 'From To Form Added');
				redirect('/transactions#From-To');
			}
		} else {
			return false;
		}
	}
	function random_f8()
	{
		//print_r($_POST);die;
		//$_POST['shift']='';
		$tbl_transactions_id = $this->Tbl_transactions_model->add_tbl_transaction($_POST);
		//unset($_POST['shift']);
		if ($tbl_transactions_id) { // echo $tbl_transactions_id; die; 
			$tbl_master_transactions_id = $this->Tbl_transactions_model->random_f8($tbl_transactions_id, $_POST);
			if ($tbl_master_transactions_id) {
				$this->session->set_flashdata('msg', 'Random Form Added');
				redirect('/transactions');
			}
		} else {
			return false;
		}
	}
	function update_random_f8()
	{
		//print_r($_POST);die;
		//$_POST['shift']='';
		$tbl_transactions_id = $_POST['master_id'];
		//unset($_POST['shift']);
		if ($tbl_transactions_id) { // echo $tbl_transactions_id; die; 
			$tbl_master_transactions_id = $this->Tbl_transactions_model->random_f8($tbl_transactions_id, $_POST);
			if ($tbl_master_transactions_id) {
				$this->session->set_flashdata('msg', 'Random Form Added');
				redirect('/transactions');
			}
		} else {
			return false;
		}
	}

	// function sendjantri()
	// {
	// 	$pid = $this->input->post('pid');
	// 	$date = $this->input->post('dateofjantri');
	// 	if (empty($pid) || empty($date)) {
	// 		//$this->session->set_flashdata('message', 'Error occured in sending jantri. Please try again.');
	// 		//$this->data['json'] = array('error' => 'Some error occured. Please contact to administrator!');	
	// 		$msg = 0;
	// 	} else {
	// 		$send_jantri = $this->Tbl_transactions_model->send_jantri($pid, $date);
	// 		if($send_jantri)
	// 		$msg = 1;		
	// 	}
    //     echo $msg;
	// }
	/*
     * Editing a tbl_transactions
     */
	function edit($id)
	{
		// check if the tbl_transactions exists before trying to edit it
		$data['tbl_transactions'] = $this->Tbl_transactions_model->get_tbl_transactions($id);
		
		if (isset($data['tbl_transactions']['id'])) {
			$this->load->library('form_validation');

			$this->form_validation->set_rules('transactions_name', 'transactions Name', 'max_length[255]');
			$this->form_validation->set_rules('real_name', 'Real Name', 'max_length[255]');
			$this->form_validation->set_rules('group', 'Group', 'integer');
			$this->form_validation->set_rules('dara_rate', 'Dara Rate', 'integer');
			$this->form_validation->set_rules('akhar_rate', 'Akhar Rate', 'integer');
			$this->form_validation->set_rules('owner_name', 'Owner Name', 'max_length[255]');
			$this->form_validation->set_rules('mobile', 'Mobile', 'integer');
			$this->form_validation->set_rules('updated_by', 'Updated By', 'integer');

			if ($this->form_validation->run()) {
				$params = array(
					'transactions_name' => $this->input->post('transactions_name'),
					'real_name' => $this->input->post('real_name'),
					'group' => $this->input->post('group'),
					'dara_rate' => $this->input->post('dara_rate'),
					'akhar_rate' => $this->input->post('akhar_rate'),
					'owner_name' => $this->input->post('owner_name'),
					'mobile' => $this->input->post('mobile'),
					'updated_by' => $this->input->post('updated_by'),
					'updated_date' => $this->input->post('updated_date'),
					'dara_commision' => $this->input->post('dara_commision'),
					'akhar_commission' => $this->input->post('akhar_commission'),
					'tp_akhar_commission' => $this->input->post('tp_akhar_commission'),
					'rebate' => $this->input->post('rebate'),
					'tp_r' => $this->input->post('tp_r'),
					'hissa' => $this->input->post('hissa'),
					'address' => $this->input->post('address'),
				);

				$this->Tbl_transactions_model->update_tbl_transactions($id, $params);
				redirect('tbl_transactions/index');
			} else {
				$data['_view'] = 'tbl_transactions/edit';
				$this->load->view('layouts/main', $data);
			}
		} else
			show_error('The tbl_transactions you are trying to edit does not exist.');
	}

	/*
     * Deleting tbl_transactions
     */
	function remove($id)
	{
		$tbl_transactions = $this->Tbl_transactions_model->get_tbl_transactions($id);
		$amount = $tbl_transactions['total_number_amount']; 
		$shift = $tbl_transactions['shift_id'];
		$party = $tbl_transactions['party_id'];
		$date = date('Y-m-d', strtotime($tbl_transactions['t_date']));
		$tdate = date('d-m-Y', strtotime($tbl_transactions['t_date']));
		$master_id = $this->session->userdata['id']; // Master ID from request
			$shift_id = $shift;   // Shift ID from request
			//$date = date('Y-m-d',strtotime($this->input->post('date')));           // Date (YYYY-MM-DD)
	
			if (!$master_id || !$shift_id || !$date) {
				echo json_encode(['status' => false, 'message' => 'Invalid input parameters']);
				return;
			}
			//echo 'here'; die;
			$updated = $this->CoinModel->updateStaffTransactionsapp($party,$amount, $shift_id, $date);
			//echo $updated; die;
			if (!$updated) {
				//echo json_encode(['status' => false, 'message' => 'No staff transactions found or updated']); die;
			}

		$tbl_transaction = $this->Tbl_transactions_model->get_Date_shift_party_entry($shift, $party, $tdate);
		// check if the tbl_transactions exists before trying to delete it
		//echo '<pre>'; print_r($tbl_transactions);print_r($tbl_transaction); echo '</pre>'; die;
		if (isset($tbl_transactions['id'])) {
			$hisab_delete = $this->Tbl_transactions_model->delete_hisab_transaction($tbl_transaction,$tbl_transactions, $id);
			//if($hisab_delete){
			//	print_r($hisab_delete); die;
			if ($hisab_delete) {
				redirect('/view_transactions');
			} else {
				show_error('Cannot delete.!!');
			}
			//$this->Tbl_transactions_model->delete_tbl_transactions($id);

			//}
		} else
			show_error('The tbl_transactions you are trying to delete does not exist.');
	}
	function remove_app($id,$user_id)
	{
		$tbl_transactions = $this->Tbl_transactions_model->get_tbl_transactions($id);
		//echo '<pre>'; print_r($tbl_transactions); echo '</pre>'; die;
		$shift = $tbl_transactions['shift_id'];
		$party = $tbl_transactions['party_id'];
		$date = date('Y-m-d', strtotime($tbl_transactions['t_date']));
		$tdate = date('d-m-Y', strtotime($tbl_transactions['t_date']));
		$master_id = $user_id; // Master ID from request
			$shift_id = $shift;   // Shift ID from request
			//$date = date('Y-m-d',strtotime($this->input->post('date')));           // Date (YYYY-MM-DD)
	
			if (!$master_id || !$shift_id || !$date) {
				echo json_encode(['status' => false, 'message' => 'Invalid input parameters']);
				return;
			}
			$amount = $tbl_transactions['total_number_amount'];
			//echo $master_id.' '.$shift_id.' '.$date; die; 
			$updated = $this->CoinModel->updateStaffTransactionsapp($master_id,$amount, $shift_id, $date);
			//echo $updated; die;
			if (!$updated) {
				echo json_encode(['status' => false, 'message' => 'No staff transactions found or updated']); die;
			}
		$tbl_transaction = $this->Tbl_transactions_model->get_Date_shift_party_entry($shift, $party, $tdate);
		$all_shifts = $this->Tbl_shift_model->get_all_tbl_shift_app($user_id);
		//echo '<pre>'; print_r($tbl_transaction); echo $shift; die;
		$ttime = time();
		foreach ($all_shifts as $val) {
			if ($val['ushiftid'] == $shift) {
				$time = strtotime(date('d-m-Y', strtotime($val['open_date'])) . ' ' . date("H:i", strtotime($val['app_time'])));
				//$time = strtotime($val['app_time']);
				// if ($val['shiftid'] == 11) {
				// 	$time = strtotime('+7 hours', $time);
				// }
			}
		}
		$valid = 'true';
		
		//echo '<pre>'; print_r($ttime); echo $time; die;
		if (($ttime > $time)) {
			$valid = 'false';
			echo "<script>alert('invalid Entry. Please try Again!!');</script>";
			header("Location: https://app.555xch.live/Entry-page.php?status=0");
			exit();
		}

		// check if the tbl_transactions exists before trying to delete it
		//echo '<pre>'; print_r(count($tbl_transaction)); echo '</pre>'; die;
		if ($valid == 'true') {
			if (isset($tbl_transactions['id'])) {
				$hisab_delete = $this->Tbl_transactions_model->delete_hisab_transaction($tbl_transaction,$tbl_transactions, $id);
				//if($hisab_delete){
				//	print_r($hisab_delete); die;
				if ($hisab_delete) {
					//header("Location: https://app.555xch.live/Date-shift.php");
?>
					<script>
						window.history.go(-1)
					</script>
				<?php
				} else {
					show_error('Cannot delete.!!');
				}
				//$this->Tbl_transactions_model->delete_tbl_transactions($id);

				//}
			} else {
				?>
				<script>
					alert('Invalid Action. Please try again.');
					window.history.go(-1)
				</script>
			<?php
			}
		} else {
			?>
			<script>
				alert('Time Expired. Please try again.');
				window.history.go(-1)
			</script>
<?php
		}
	}
}
