<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_transactions extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_transactions_model');
		$this->load->model('Tbl_shift_model');
		$this->load->model('Tbl_ledger_model');
		$this->load->library('session');
		$this->load->helper('url'); 
    } 

    /*
     * adding of tbl_transactions
     */
    function index()
    {
       // $data['tbl_transactions'] = $this->Tbl_transactions_model->get_all_tbl_transactions();
        $data['shifts'] = $this->Tbl_shift_model->get_all_tbl_shift();
		$data['party'] = $this->Tbl_ledger_model->get_all_tbl_ledger();
		//$data['randomf4'] = $this->Tbl_shift_model->get_all_tbl_shift();
        $data['_view'] = 'tbl_transactions/index';
        $this->load->view('layouts/main',$data);
    }
	
	function edit_trn($id=0)
    {
	$data['shifts'] = $this->Tbl_shift_model->get_all_tbl_shift();
		$data['party'] = $this->Tbl_ledger_model->get_all_tbl_ledger();
       $data['tbl_transactions'] = $this->Tbl_transactions_model->get_custom_transactions($id);
	   $data['_view'] = 'tbl_transactions/edit_transactions';
        $this->load->view('layouts/main',$data);
    }
	/*
     * Listing of tbl_transactions
     */
    function view()
    {
       $data['tbl_transactions'] = $this->Tbl_transactions_model->get_all_transactions();
        $data['shifts'] = $this->Tbl_shift_model->get_all_tbl_shift();
		$data['party'] = $this->Tbl_ledger_model->get_all_tbl_ledger();
		$data['default_trans'] = $this->Tbl_ledger_model->get_all_tbl_ledger();
		//$data['randomf4'] = $this->Tbl_shift_model->get_all_tbl_shift();
        $data['_view'] = 'tbl_transactions/view';
        $this->load->view('layouts/main',$data);
    }
/*
     * Listing of tbl_transactions
     */
    function view_details($mid)
    {
       $data['tbl_transactions'] = $this->Tbl_transactions_model->get_all_detail_transactions($mid);
        $data['shifts'] = $this->Tbl_shift_model->get_all_tbl_shift();
		$data['party'] = $this->Tbl_ledger_model->get_all_tbl_ledger();
		$data['default_trans'] = $this->Tbl_ledger_model->get_all_tbl_ledger();
		//$data['randomf4'] = $this->Tbl_shift_model->get_all_tbl_shift();
        $data['_view'] = 'tbl_transactions/view';
        $this->load->view('layouts/main',$data);
    }
    /*
     * Adding a new tbl_transactions
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('transactions_name','transactions Name','max_length[255]');
		$this->form_validation->set_rules('real_name','Real Name','max_length[255]');
		//$this->form_validation->set_rules('group','Group','integer');
		//$this->form_validation->set_rules('dara_rate','Dara Rate','integer');
		//$this->form_validation->set_rules('akhar_rate','Akhar Rate','integer');
		//$this->form_validation->set_rules('owner_name','Owner Name','max_length[255]');
		$this->form_validation->set_rules('mobile','Mobile','integer');
		$this->form_validation->set_rules('updated_by','Updated By','integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'transactions_name' => $this->input->post('transactions_name'),
				'real_name' => $this->input->post('real_name'),
				'group' => $this->input->post('group'),
				'dara_rate' => $this->input->post('dara_rate'),
				'akhar_rate' => $this->input->post('akhar_rate'),
				'owner_name' => $this->input->post('owner_name'),
				'mobile' => $this->input->post('mobile'),
				'updated_by' => $this->session->userdata['id'],
				//'updated_date' => $this->input->post('updated_date'),
				'dara_commision' => $this->input->post('dara_commision'),
				'akhar_commission' => $this->input->post('akhar_commission'),
				//'tp_akhar_commission' => $this->input->post('tp_akhar_commission'),
				'rebate' => $this->input->post('rebate'),
				'tp_r' => $this->input->post('tp_r'),
				'hissa' => $this->input->post('hissa'),
				'address' => $this->input->post('address'),
            );
            
            $tbl_transactions_id = $this->Tbl_transactions_model->add_tbl_transactions($params);
			 $this->session->set_flashdata('msg', 'Transaction Added');
            redirect('/transactions_master');
        }
        else
        {     $data['tbl_transactions'] = $this->Tbl_transactions_model->get_all_tbl_transactions();       
            $data['_view'] = 'tbl_transactions/add';
            $this->load->view('layouts/main',$data);
        }
    }  

	function add_trn(){
		//print_r($_POST);die;
		$tbl_transactions_ledger = $this->Tbl_transactions_model->add_tbl_transaction_ledger($_POST);
		$tbl_transactions_id = $this->Tbl_transactions_model->add_tbl_transaction($_POST);
		if($tbl_transactions_id){// echo $tbl_transactions_id; die; 
			$tbl_master_transactions_id = $this->Tbl_transactions_model->add_tbl_only_transaction($tbl_transactions_id,$_POST);
			//echo '<pre>'; print_r($tbl_master_transactions_id);  echo '</pre>'; die;
			if($tbl_master_transactions_id['master_id']){
			return $tbl_master_transactions_id;
			}
		}
		else{
			return false;
		}
	}
	
	function update_trn(){
		//print_r($_POST);die;
		$tbl_transactions_id = $_POST['master_id'];
		if($tbl_transactions_id){// echo $tbl_transactions_id; die; 
			$tbl_master_transactions_id = $this->Tbl_transactions_model->update_tbl_only_transaction($tbl_transactions_id,$_POST);
			//echo '<pre>'; print_r($tbl_master_transactions_id);  echo '</pre>'; die;
			if($tbl_master_transactions_id['master_id']){
			return $tbl_master_transactions_id;
			}
		}
		else{
			return false;
		}
	}
	
	function add_randomf4(){
		//print_r($_POST);die;
		//$_POST['shift']='';
		$tbl_transactions_id = $this->Tbl_transactions_model->add_tbl_transaction($_POST);
		//unset($_POST['shift']);
		if($tbl_transactions_id){// echo $tbl_transactions_id; die;
			//echo '<pre>'; print_r($_POST); echo '</pre>'; die;
			$tbl_master_transactions_id = $this->Tbl_transactions_model->add_tbl_randomf4($tbl_transactions_id,$_POST);
			if($tbl_master_transactions_id){
				 $this->session->set_flashdata('msg', 'Random Form Added');
				 redirect('/transactions#profile');
			}
		}
		else{
			return false;
		}
	}
	function update_randomf4(){
		//print_r($_POST);die;
		//$_POST['shift']='';
		$tbl_transactions_id = $_POST['master_id'];
		//unset($_POST['shift']);
		if($tbl_transactions_id){// echo $tbl_transactions_id; die; 
			$tbl_master_transactions_id = $this->Tbl_transactions_model->add_tbl_randomf4($tbl_transactions_id,$_POST);
			if($tbl_master_transactions_id){
				 $this->session->set_flashdata('msg', 'Random Form Added');
				 redirect('/transactions#profile');
			}
		}
		else{
			return false;
		}
	}
	function add_cross(){
		//print_r($_POST);die;
		//$_POST['shift']='';
		$tbl_transactions_id = $this->Tbl_transactions_model->add_tbl_transaction($_POST);
		//unset($_POST['shift']);
		if($tbl_transactions_id){// echo $tbl_transactions_id; die; 
			$tbl_master_transactions_id = $this->Tbl_transactions_model->add_cross($tbl_transactions_id,$_POST);
			if($tbl_master_transactions_id){
				$this->session->set_flashdata('msg', 'Cross Form Added');
				 redirect('/transactions#cross');
			}
		}
		else{
			return false;
		}
	}
	function update_cross(){
		//print_r($_POST);die;
		//$_POST['shift']='';
		$tbl_transactions_id = $_POST['master_id'];
		//unset($_POST['shift']);
		if($tbl_transactions_id){// echo $tbl_transactions_id; die; 
			$tbl_master_transactions_id = $this->Tbl_transactions_model->add_cross($tbl_transactions_id,$_POST);
			if($tbl_master_transactions_id){
				$this->session->set_flashdata('msg', 'Cross Form Added');
				 redirect('/transactions#cross');
			}
		}
		else{
			return false;
		}
	}
	function add_fromto(){
		//print_r($_POST);die;
		//$_POST['shift']='';
		$tbl_transactions_id = $this->Tbl_transactions_model->add_tbl_transaction($_POST);
		//unset($_POST['shift']);
		if($tbl_transactions_id){// echo $tbl_transactions_id; die; 
			$tbl_master_transactions_id = $this->Tbl_transactions_model->add_fromto($tbl_transactions_id,$_POST);
			if($tbl_master_transactions_id){
				//$this->session->set_flashdata('msg', 'From To Form Added');
				 redirect('/transactions#From-To');
			}
		}
		else{
			return false;
		}
	}
	function update_fromto(){
		//print_r($_POST);die;
		//$_POST['shift']='';
		$tbl_transactions_id = $_POST['master_id'];
		//unset($_POST['shift']);
		if($tbl_transactions_id){// echo $tbl_transactions_id; die; 
			$tbl_master_transactions_id = $this->Tbl_transactions_model->add_fromto($tbl_transactions_id,$_POST);
			if($tbl_master_transactions_id){
				//$this->session->set_flashdata('msg', 'From To Form Added');
				 redirect('/transactions#From-To');
			}
		}
		else{
			return false;
		}
	}
	function random_f8(){
		//print_r($_POST);die;
		//$_POST['shift']='';
		$tbl_transactions_id = $this->Tbl_transactions_model->add_tbl_transaction($_POST);
		//unset($_POST['shift']);
		if($tbl_transactions_id){// echo $tbl_transactions_id; die; 
			$tbl_master_transactions_id = $this->Tbl_transactions_model->random_f8($tbl_transactions_id,$_POST);
			if($tbl_master_transactions_id){
				$this->session->set_flashdata('msg', 'Random Form Added');
				 redirect('/transactions');
			}
		}
		else{
			return false;
		}
	}
	function update_random_f8(){
		//print_r($_POST);die;
		//$_POST['shift']='';
		$tbl_transactions_id = $_POST['master_id'];
		//unset($_POST['shift']);
		if($tbl_transactions_id){// echo $tbl_transactions_id; die; 
			$tbl_master_transactions_id = $this->Tbl_transactions_model->random_f8($tbl_transactions_id,$_POST);
			if($tbl_master_transactions_id){
				$this->session->set_flashdata('msg', 'Random Form Added');
				 redirect('/transactions');
			}
		}
		else{
			return false;
		}
	}
    /*
     * Editing a tbl_transactions
     */
    function edit($id)
    {   
        // check if the tbl_transactions exists before trying to edit it
        $data['tbl_transactions'] = $this->Tbl_transactions_model->get_tbl_transactions($id);
        
        if(isset($data['tbl_transactions']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('transactions_name','transactions Name','max_length[255]');
			$this->form_validation->set_rules('real_name','Real Name','max_length[255]');
			$this->form_validation->set_rules('group','Group','integer');
			$this->form_validation->set_rules('dara_rate','Dara Rate','integer');
			$this->form_validation->set_rules('akhar_rate','Akhar Rate','integer');
			$this->form_validation->set_rules('owner_name','Owner Name','max_length[255]');
			$this->form_validation->set_rules('mobile','Mobile','integer');
			$this->form_validation->set_rules('updated_by','Updated By','integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'transactions_name' => $this->input->post('transactions_name'),
					'real_name' => $this->input->post('real_name'),
					'group' => $this->input->post('group'),
					'dara_rate' => $this->input->post('dara_rate'),
					'akhar_rate' => $this->input->post('akhar_rate'),
					'owner_name' => $this->input->post('owner_name'),
					'mobile' => $this->input->post('mobile'),
					'updated_by' => $this->input->post('updated_by'),
					'updated_date' => $this->input->post('updated_date'),
					'dara_commision' => $this->input->post('dara_commision'),
					'akhar_commission' => $this->input->post('akhar_commission'),
					'tp_akhar_commission' => $this->input->post('tp_akhar_commission'),
					'rebate' => $this->input->post('rebate'),
					'tp_r' => $this->input->post('tp_r'),
					'hissa' => $this->input->post('hissa'),
					'address' => $this->input->post('address'),
                );

                $this->Tbl_transactions_model->update_tbl_transactions($id,$params);            
                redirect('tbl_transactions/index');
            }
            else
            {
                $data['_view'] = 'tbl_transactions/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_transactions you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_transactions
     */
    function remove($id)
    {
        $tbl_transactions = $this->Tbl_transactions_model->get_tbl_transactions($id);

        // check if the tbl_transactions exists before trying to delete it
        if(isset($tbl_transactions['id']))
        {
            $this->Tbl_transactions_model->delete_tbl_transactions($id);
            redirect('tbl_transactions/index');
        }
        else
            show_error('The tbl_transactions you are trying to delete does not exist.');
    }
    
}
