<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_shift extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_shift_model');
		$this->load->library('session');
    } 

   function getallshifts(){
	   $shifts = $this->Tbl_shift_model->get_all_tbl_shift();
	   echo '<pre>'; print_r($shifts); echo '</pre>'; die;
	   echo json_encode($shifts);
   }

    /*
     * Listing of tbl_shift 
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
		$params['admin_id'] = $this->session->userdata['id'];
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tbl_shift/index?');
        $config['total_rows'] = $this->Tbl_shift_model->get_all_tbl_shift_count();
        $this->pagination->initialize($config);

        $data['tbl_shift'] = $this->Tbl_shift_model->get_all_tbl_shift($params);
        
        $data['_view'] = 'tbl_shift/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_shift
     */
    function add()
    {   
        $this->load->library('form_validation');
		$data['error'] = '';
		$this->form_validation->set_rules('shift_name','Shift Name','max_length[255]');
		$this->form_validation->set_rules('next_day','Next Day','max_length[255]');
		$this->form_validation->set_rules('shift_working_for','Shift Working For','max_length[255]');
		$this->form_validation->set_rules('is_active','Is Active','integer');
		$this->form_validation->set_rules('updated_by','Updated By','integer');
		//echo '<pre>';print_r($this->session->userdata); die;
		
		if($this->form_validation->run())     
        {
			if($this->Tbl_shift_model->checkDuplicate($this->input->post('shift_name'),$this->session->userdata['id'])=='1'){
				$data['error']="Duplicate Entry Found.Please try with other name.";
			}	
		else{			
            $params = array(
				'shift_name' => $this->input->post('shift_name'),
				'open_date' => date('Y-m-d',strtotime($this->input->post('open_date'))),
				'next_day' => $this->input->post('next_day'),
				'shift_working_for' => $this->input->post('shift_working_for'),
				//'owner' => $this->input->post('owner'),
				'super_admin' => $this->input->post('master'),
				//'fanter' => $this->input->post('fanter'),
				//'cash_agent' => $this->input->post('cash_agent'),
				//'admin' => $this->input->post('admin'),
                'app_time' => $this->input->post('app_time'),
				'data_entry_operator' => $this->input->post('data_entry_operator'),
				'is_active' => '1',
				'updated_by' => $this->session->userdata['id'],
				//'updated_date' => $this->input->post('updated_date'),
            );
            $tbl_shift_id = $this->Tbl_shift_model->add_tbl_shift($params);
            $tbl_user_shift = $this->Tbl_shift_model->add_tbl_shift_time($tbl_shift_id,$params);
            if($tbl_shift_id){
            //    $set_time_id = $this->set_access_time($params);
            //    if($set_time_id)
               redirect('/shift_master');
            // else
            // $data['error']="time set error.";
            }
            
        }
		}  
		$data['tbl_shift'] = $this->Tbl_shift_model->get_all_tbl_shift($this->session->userdata['id']);
		// echo '<pre>'; print_r($params); echo '</pre>'; die;
            $data['_view'] = 'tbl_shift/add';
            $this->load->view('layouts/main',$data);
    }  


    /*check user access shift */
    public function check_access($user_id) {
        $access_times = $this->Tbl_shift_model->get_access_time($user_id);

        if ($access_times) {
            foreach ($access_times as $access_time) {
                $shifts = array(
                    (object) array('shift_start_time' => $access_time->shift_start_time, 'shift_end_time' => $access_time->shift_end_time)
                );

                if (check_access_time($access_time->start_date, $access_time->end_date, $shifts)) {
                    echo "Access granted";
                    return;
                }
            }
        }

        echo "Access denied";
    }

    public function set_access_time($data) { //echo '<pre>';print_r($data); die;
        $admin_id = $this->input->post('admin_id');
        $start_date = $this->input->post('start_date');
        $end_date = $this->input->post('end_date');
        $start_time = $this->input->post('start_time');
        $end_time = $this->input->post('end_time');

        $result = $this->AccessTime_model->set_access_time($admin_id, $start_date, $end_date, $start_time, $end_time);

        if ($result) {
            echo "Access time set successfully";
        } else {
            echo "Failed to set access time";
        }
        
    }

    /*
     * Editing a tbl_shift
     */
    function edit($id)
    {   
        // check if the tbl_shift exists before trying to edit it
        $data['tbl_shift'] = $this->Tbl_shift_model->get_tbl_shift($id);
        $data['error'] = '';
        if(isset($data['tbl_shift']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('shift_name','Shift Name','max_length[255]');
			$this->form_validation->set_rules('next_day','Next Day','max_length[255]');
			$this->form_validation->set_rules('shift_working_for','Shift Working For','max_length[255]');
			$this->form_validation->set_rules('is_active','Is Active','integer');
			$this->form_validation->set_rules('updated_by','Updated By','integer');
		
			if($this->form_validation->run())     
            {
//echo $this->Tbl_shift_model->checkDuplicate($this->input->post('shift_name'),$this->session->userdata['id']); die;				
				
                $params = array(
					'shift_name' => $this->input->post('shift_name'),
					'open_date' => date('Y-m-d',strtotime($this->input->post('open_date'))),
					'next_day' => $this->input->post('next_day'),
					'shift_working_for' => $this->input->post('shift_working_for'),
					//'owner' => $this->input->post('owner'),
					'super_admin' => $this->input->post('super_admin'),
					//'fanter' => $this->input->post('fanter'),
					//'cash_agent' => $this->input->post('cash_agent'),
					//'admin' => $this->input->post('admin'),
                    'app_time' => $this->input->post('app_time'),
					'data_entry_operator' => $this->input->post('data_entry_operator'),
					'is_active' => $this->input->post('is_active'),
					'updated_by' => $this->session->userdata['id'],
					'updated_date' => $this->input->post('updated_date'),
                );

                $master_params = array(
					'shift_id' => $id,
					'master_id' => 0,
					'party_time' => $this->input->post('super_admin'),
					//'fanter' => $this->input->post('fanter'),
					//'cash_agent' => $this->input->post('cash_agent'),
					//'admin' => $this->input->post('admin'),
                    'app_time' => $this->input->post('app_time'),
					'staff_time' => $this->input->post('data_entry_operator'),
					'is_active' => $this->input->post('is_active'),
					'updated_by' => $this->session->userdata['id'],
					'updated_date' => $this->input->post('updated_date'),
                );

                $this->Tbl_shift_model->update_tbl_shift($id,$params);            
                redirect('/shift_master');
            
			}
           // else
           // {
                $data['_view'] = 'tbl_shift/edit';
                $this->load->view('layouts/main',$data);
           // }
        }
        else
            show_error('The tbl_shift you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_shift
     */
    function remove($id)
    {
        $tbl_shift = $this->Tbl_shift_model->get_tbl_shift($id);

        // check if the tbl_shift exists before trying to delete it
        if(isset($tbl_shift['id']))
        {
            $this->Tbl_shift_model->delete_tbl_shift($id);
            redirect('shift_master');
        }
        else
            show_error('The tbl_shift you are trying to delete does not exist.');
    }
    
}
