<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_shift extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_shift_model');
		$this->load->library('session');
    } 

   function getallshifts(){
	   $shifts = $this->Tbl_shift_model->get_all_tbl_shift();
	   //echo '<pre>'; print_r($shifts); echo '</pre>'; die;
	   echo json_encode($shifts);
   }

    /*
     * Listing of tbl_shift 
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
		$params['admin_id'] = $this->session->userdata['id'];
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tbl_shift/index?');
        $config['total_rows'] = $this->Tbl_shift_model->get_all_tbl_shift_count();
        $this->pagination->initialize($config);

        $data['tbl_shift'] = $this->Tbl_shift_model->get_all_tbl_shift($params);
        
        $data['_view'] = 'tbl_shift/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_shift
     */
    function add()
    {   
        $this->load->library('form_validation');
		$data['error'] = '';
		$this->form_validation->set_rules('shift_name','Shift Name','max_length[255]');
		$this->form_validation->set_rules('next_day','Next Day','max_length[255]');
		$this->form_validation->set_rules('shift_working_for','Shift Working For','max_length[255]');
		$this->form_validation->set_rules('is_active','Is Active','integer');
		$this->form_validation->set_rules('updated_by','Updated By','integer');
		//echo '<pre>';print_r($this->session->userdata); die;
		
		if($this->form_validation->run())     
        {
			if($this->Tbl_shift_model->checkDuplicate($this->input->post('shift_name'),$this->session->userdata['id'])>'0'){
				$data['error']="Duplicate Entry Found.Please try with other name.";
			}	
		else{			
            $params = array(
				'shift_name' => $this->input->post('shift_name'),
				'open_date' => date('Y-m-d',strtotime($this->input->post('open_date'))),
				'next_day' => $this->input->post('next_day'),
				//'shift_working_for' => $this->input->post('shift_working_for'),
				//'owner' => $this->input->post('owner'),
				'master' => $this->input->post('master'),
				//'fanter' => $this->input->post('fanter'),
				//'cash_agent' => $this->input->post('cash_agent'),
				//'admin' => $this->input->post('admin'),
                'app_time' => $this->input->post('app_time'),
				'data_entry_operator' => $this->input->post('data_entry_operator'),
				'is_active' => '1',
				'updated_by' => $this->session->userdata['id'],
				//'updated_date' => $this->input->post('updated_date'),
            );
            $tbl_shift_id = $this->Tbl_shift_model->add_tbl_shift($params);
            $master_params = array(
                'shift_id' => $tbl_shift_id,
                'open_date' => date('Y-m-d',strtotime($this->input->post('open_date'))),
                'updated_by' => $this->session->userdata['id'],
                'is_active' => '1'
                
            );
            $tbl_shift_masterid = $this->Tbl_shift_model->insert_tbl_shift_timing($master_params); 
            if($tbl_shift_id){
               redirect('/shift_master');
            }
            
       }
		}  
		$data['tbl_shift'] = $this->Tbl_shift_model->get_all_tbl_shift_master($this->session->userdata['id']);
       //echo '<pre>'; print_r($data['tbl_shift']); echo '</pre>'; die;
        if(empty($data['tbl_shift'])){
            $data['tbl_shift'] = $this->Tbl_shift_model->get_all_tbl_shift(1);
        }
		 
            $data['_view'] = 'tbl_shift/add';
            $this->load->view('layouts/main',$data);
    } 
    public function change_status($id) {
        // Call model function to toggle status
        $this->Tbl_shift_model->toggle_status($id);

        // Redirect back to the previous page or any specific URL
        redirect($_SERVER['HTTP_REFERER']);
    }
 function add_master($shift_name,$shift_id)
    { $data['error'] = '';
        $data['shift_name'] = $shift_name;
        $data['shift_id'] = $shift_id;
        $data['tbl_shift'] = $this->Tbl_shift_model->get_all_tbl_shift_master($this->session->userdata['id']);
        // echo '<pre>'; print_r($data['tbl_shift']); echo '</pre>'; die;
         if(empty($data['tbl_shift'])){
             $data['tbl_shift'] = $this->Tbl_shift_model->get_all_tbl_shift(1);
         }
          
             $data['_view'] = 'tbl_shift/add_master';
             $this->load->view('layouts/main',$data);
    }
    function add_master_submit()
    {  
        $this->load->library('form_validation');
		
        
		$this->form_validation->set_rules('shift_name','Shift Name','max_length[255]');
		$this->form_validation->set_rules('next_day','Next Day','max_length[255]');
		$this->form_validation->set_rules('shift_working_for','Shift Working For','max_length[255]');
		$this->form_validation->set_rules('is_active','Is Active','integer');
		$this->form_validation->set_rules('updated_by','Updated By','integer');
		//echo '<pre>';print_r($this->session->userdata); die;
		
		if($this->form_validation->run())     
        {					
            $params = array(
				'shift_name' => $this->input->post('shift_name'),
				'open_date' => date('Y-m-d',strtotime($this->input->post('open_date'))),
				'next_day' => $this->input->post('next_day'),
				//'shift_working_for' => $this->input->post('shift_working_for'),
				//'owner' => $this->input->post('owner'),
				'master' => $this->input->post('master'),
				//'fanter' => $this->input->post('fanter'),
				//'cash_agent' => $this->input->post('cash_agent'),
				//'admin' => $this->input->post('admin'),
                'app_time' => $this->input->post('app_time'),
				'data_entry_operator' => $this->input->post('data_entry_operator'),
				'is_active' => '1',
				'updated_by' => $this->session->userdata['id'],
				//'updated_date' => $this->input->post('updated_date'),
            );
            //$tbl_shift_id = $this->Tbl_shift_model->add_tbl_shift($params);
            $master_params = array(
                'shift_id' => $this->input->post('shift_id'),
                'open_date' => date('Y-m-d',strtotime($this->input->post('open_date'))),
                'updated_by' => $this->session->userdata['id'],
                'is_active' => '1'
                
            );
            $tbl_shift_masterid = $this->Tbl_shift_model->insert_tbl_shift_timing($master_params); 
            if($tbl_shift_masterid){
               redirect('/shift_master');
            }
            
      // }
		}  
		else
            show_error('Some Error Occured.');
    } 

    /*
     * Adding a new tbl_shift for admin
     */
    function add_admin()
    {   
        
		$data['error'] = '';
        
		if(!empty($this->input->post('shift_name'))){			
            $params = array(
				'shift_name' => $this->input->post('shift_name'),
				'open_date' => date('Y-m-d',strtotime($this->input->post('open_date'))),
				'super_admin' => $this->input->post('super_admin'),
				'is_active' => '1',
				'updated_by' => $this->session->userdata['id']
            );
            $tbl_shift_id = $this->Tbl_shift_model->add_tbl_shift($params);
            
            $master_params = array(
                'shift_id' => $tbl_shift_id,
                'open_date' => date('Y-m-d',strtotime($this->input->post('open_date'))),
                'master' => $this->input->post('super_admin'),
                'master_id' => 1,
                'updated_by' => 1,
                'is_active' => '1'
                
            );
            $tbl_shift_masterid = $this->Tbl_shift_model->insert_tbl_shift_timing($master_params);   
            if($tbl_shift_masterid){
               redirect('/shift_master_admin');
            }
        }
		 
		$data['tbl_shift'] = $this->Tbl_shift_model->get_all_tbl_shift($this->session->userdata['id']);
		
            $data['_view'] = 'tbl_shift/add_admin';
            $this->load->view('layouts/main',$data);
    }  


    /*check user access shift */
    public function check_access($user_id) {
        $access_times = $this->Tbl_shift_model->get_access_time($user_id);

        if ($access_times) {
            foreach ($access_times as $access_time) {
                $shifts = array(
                    (object) array('shift_start_time' => $access_time->shift_start_time, 'shift_end_time' => $access_time->shift_end_time)
                );

                if (check_access_time($access_time->start_date, $access_time->end_date, $shifts)) {
                    echo "Access granted";
                    return;
                }
            }
        }

        echo "Access denied";
    }

    public function set_access_time($data) { //echo '<pre>';print_r($data); die;
        $admin_id = $this->input->post('admin_id');
        $start_date = $this->input->post('start_date');
        $end_date = $this->input->post('end_date');
        $start_time = $this->input->post('start_time');
        $end_time = $this->input->post('end_time');

        $result = $this->AccessTime_model->set_access_time($admin_id, $start_date, $end_date, $start_time, $end_time);

        if ($result) {
            echo "Access time set successfully";
        } else {
            echo "Failed to set access time";
        }
        
    }

    /*
     * Editing a tbl_shift
     */
    function edit($id)
    { 
        $data['tbl_shift_time'] = $this->Tbl_shift_model->get_tbl_shift_time($id,$this->session->userdata['id']);
        $data['post_shift_id'] = $id;
      // echo '<pre>'; print_r($data);die;
        $data['error'] = '';
        if(isset($_POST) && !empty($_POST))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('shift_name','Shift Name','max_length[255]');
			$this->form_validation->set_rules('next_day','Next Day','max_length[255]');
			$this->form_validation->set_rules('shift_working_for','Shift Working For','max_length[255]');
			$this->form_validation->set_rules('is_active','Is Active','integer');
			$this->form_validation->set_rules('updated_by','Updated By','integer');
		
			if($this->input->method() == 'post')     
            { 
                $params = array(
					'shift_name' => $this->input->post('shift_name'),
					'open_date' => date('Y-m-d',strtotime($this->input->post('open_date'))),
					'next_day' => $this->input->post('next_day'),
					'shift_working_for' => $this->input->post('shift_working_for'),
					'master' => $this->input->post('master'),
					'app_time' => $this->input->post('app_time'),
					'data_entry_operator' => $this->input->post('data_entry_operator'),
					'is_active' => '1',
					'updated_by' => $this->session->userdata['id'],
                );
                $master_params = array(
					
					'master_id' => $this->session->userdata['id'],
                    'open_date' => date('Y-m-d',strtotime($this->input->post('open_date'))),
					'master' => $this->input->post('master'),
					'app_time' => $this->input->post('app_time'),
					'data_entry_operator' => $this->input->post('data_entry_operator'),
					'is_active' => '1',
					'updated_by' => $this->session->userdata['id'],
					
                );
                if($this->session->userdata['id'] == 1){
            $shift_id = $data['tbl_shift_time']['shift_id'];
            $id = $data['tbl_shift_time']['id'];
                }
                else{
                    $shift_id = $id;
                }
//echo '<pre>'.$id; print_r($data['tbl_shift_time']);  die;
                if(empty($data['tbl_shift_time'])){ //echo 'there'; die;
                   $master_paramss = array(
                       'shift_id' => $shift_id,
                       
                       'open_date' => date('Y-m-d',strtotime($this->input->post('open_date'))),
                       'master' => $this->input->post('master'),
                       'app_time' => $this->input->post('app_time'),
                       'updated_by' => $this->session->userdata['id'],
                       'master_id' => $this->session->userdata['id'],
                       'is_active' => '1'
                       
                   );
                   $tbl_shift_masterid = $this->Tbl_shift_model->insert_tbl_shift_timing($master_paramss);
                }
                else {
                   $tbl_shift_masterid = $this->Tbl_shift_model->update_tbl_shift_timing($id,$master_params); 
                }
                
                redirect('/shift_master');
            
			}
        }
        if(!empty($data['tbl_shift_time']['id'])){
            $data['_view'] = 'tbl_shift/edit';
            $this->load->view('layouts/main',$data);
        }
        else if(empty($data['tbl_shift_time'])){ 
            $data['tbl_shift_time'] = $this->Tbl_shift_model->get_tbl_shift_from_usershift($id);  
//echo '<pre>';print_r($data['tbl_shift_time']); die;
            $data['_view'] = 'tbl_shift/edit';
            $this->load->view('layouts/main',$data);    
        }
        else
            show_error('The tbl_shift you are trying to edit does not exist.');
    } 

     /*
     * Editing a tbl_shift for admin
     */
    function edit_admin($id)
    {   
       
       $data['tbl_shift'] = $this->Tbl_shift_model->get_tbl_shift($id);        
        //$data['tbl_shift_time'] = $this->Tbl_shift_model->get_tbl_shift_time($id,$this->session->userdata['id']);
      
        $data['error'] = '';
        if(isset($data['tbl_shift']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('shift_name','Shift Name','max_length[255]');
			
		
			if($this->form_validation->run())     
            {			
				
                $params = array(
					'shift_name' => $this->input->post('shift_name'),
					'open_date' => date('Y-m-d',strtotime($this->input->post('open_date'))),
					'super_admin' => $this->input->post('super_admin'),
					'is_active' => ($this->input->post('is_active'))?$this->input->post('is_active'):1,
					'updated_by' => $this->session->userdata['id'],
					'updated_date' => $this->input->post('updated_date'),
                );
                $master_params = array(
					'shift_id' => $id,
					'master_id' => $this->session->userdata['id'],
                    'open_date' => date('Y-m-d',strtotime($this->input->post('open_date'))),
					'master' => $this->input->post('super_admin'),
					'app_time' => $this->input->post('app_time'),
					'data_entry_operator' => $this->input->post('data_entry_operator'),
					'is_active' => '1',
					'updated_by' => $this->session->userdata['id'],
					
                );
                //$this->Tbl_shift_model->update_tbl_shift($id,$params);            
                //$this->Tbl_shift_model->update_tbl_shift_timing($data['tbl_shift_time']['id'],$master_params); 
                if(empty($data['tbl_shift'])){
                    //echo '<pre>'; print_r($id);print_r($master_params); die;
                    $tbl_shift_id = $this->Tbl_shift_model->add_tbl_shift($params);       
                    $master_params = array(
                        'shift_id' => $tbl_shift_id,
                        'open_date' => date('Y-m-d',strtotime($this->input->post('open_date'))),
                        'master' => $this->input->post('super_admin'),
                        'updated_by' => $this->session->userdata['id'],
                        'is_active' => '1'
                        
                    );
                    $tbl_shift_masterid = $this->Tbl_shift_model->insert_tbl_shift_timing($master_params); 
                }
                else{ //print_r($_POST); die;
                    //$this->Tbl_shift_model->update_tbl_shift_timing($data['tbl_shift_time']['id'],$master_params);        
                    $this->Tbl_shift_model->update_tbl_shift($id,$params);
                    //$tbl_shift_id = $id;
                    //update_tbl_shift_timing
                    $master_params = array(
                      'master_id' =>  $this->session->userdata['id'],
                        'open_date' => date('Y-m-d',strtotime($this->input->post('open_date'))),
                        'master' => $this->input->post('super_admin'),
                        
                        
                    );
                     // check here if usershifttiming exist
                     $update_by = 1;
                      
                     $usershifttiming = $this->Tbl_shift_model->check_usershifttiming($id,$update_by,$master_params['open_date']);
                     //echo '<pre>'; print_r($usershifttiming); die;
                     if(empty($usershifttiming)){
                        $master_params = array(
                            'shift_id' => $id,
                            'open_date' => date('Y-m-d',strtotime($this->input->post('open_date'))),
                            'master' => $this->input->post('super_admin'),
                            'updated_by' => $this->session->userdata['id'],
                            'master_id' => $this->session->userdata['id'],
                            'is_active' => '1'
                            
                        );
                        $tbl_shift_masterid = $this->Tbl_shift_model->insert_tbl_shift_timing($master_params);
                     }
                     else{
                        $tbl_shift_masterid = $this->Tbl_shift_model->update_tbl_shift_timing_by_shiftid($usershifttiming['id'],$master_params); 
                     }
                    
                }  
                
                redirect('/shift_master_admin');
            
			}
           // else
           // {
                $data['_view'] = 'tbl_shift/edit_admin';
                $this->load->view('layouts/main',$data);
           // }
        }
        else
            show_error('The tbl_shift you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_shift
     */
    function remove($id)
    {
        // $tbl_shift = $this->Tbl_shift_model->get_tbl_shift($id);

        // // check if the tbl_shift exists before trying to delete it
        // if(isset($tbl_shift['id']))
        // {
        //     $this->Tbl_shift_model->delete_tbl_shift($id);
        //     redirect('shift_master');
        // }
        // else
        //     show_error('The tbl_shift you are trying to delete does not exist.');

         // Call the model function to delete the shift and its timing
         $result = $this->Tbl_shift_model->delete_shift_with_timing($id);

         if ($result) {
             // If successful, set success message
             $this->session->set_flashdata('message', 'Shift and timing deleted successfully.');
         } else {
             // If failed, set error message
             $this->session->set_flashdata('error', 'Failed to delete shift and timing.');
         }
         redirect('shift_master');
    }
    
}
