<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Tbl_coin extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->load->model('CoinModel');
        $this->load->library('session');
    }

    public function allocateCredits()
    {   // Get POST data
        $ledger_id = $this->input->post('ledger_id', true); // true for XSS filtering
        $credit_balance = $this->input->post('credit_balance', true);
        $master_id = $this->session->userdata('id');
        // echo '<pre>'; print_r($_POST); die;
        // Optional: Validate input (recommended)
        // Validate input correctly
        if (!isset($ledger_id) || !isset($credit_balance)) {
            echo "<script>alert('Ledger ID and Credit Balance are required.'); window.history.back();</script>";
            return;
        }


        // Example: You can call your insertOrUpdateCredit function here
        $result = $this->CoinModel->insertOrUpdateCredit($ledger_id, $credit_balance, $master_id,  1); // assuming master_id = 0 and credit_type = 1

        if ($result == 'updated') {
            echo "<script>alert('Credit updated successfully.'); window.location.href='" . base_url('ledger') . "';</script>";
        } else {
            echo "<script>alert('Credit allocated successfully.'); window.location.href='" . base_url('ledger') . "';</script>";
        }
    }

    // View Allocation Page
    public function allocateCoins()
    {
        $role = $this->session->userdata('role'); // Fetch role from session

        if ($role === 'Super Admin') {
            $data['users'] = $this->CoinModel->getMasters(); // Get Masters for Super Admin
        } elseif ($role === 'Master') {
            $data['users'] = $this->CoinModel->getStaff(); // Get Staff for Master
        } else {
            show_error('Unauthorized access.', 403);
        }
        // Load the database library if not already loaded
        $this->load->database();

        $this->db->select('ct.id, ct.amount, ct.type, ct.created_at, ct.sender_id, ct.receiver_id, 
                   sender_ledger.ledger_name AS sender_name, 
                   receiver_ledger.ledger_name AS receiver_name');
        $this->db->from('coin_transactions ct');
        $this->db->join('tbl_ledger sender_ledger', 'ct.sender_id = sender_ledger.id', 'left');
        $this->db->join('tbl_ledger receiver_ledger', 'ct.receiver_id = receiver_ledger.id', 'left');

        $this->db->where('ct.shift_id', NULL); // Ensure only NULL shift_id records

        $this->db->group_start(); // Start grouping conditions
        $this->db->where('ct.sender_id', $this->session->userdata('id'));

        // if ($this->session->userdata['role'] == 'Master') {
        //     $this->db->or_where('ct.receiver_id', $this->session->userdata('id'));
        // }
        $this->db->group_end(); // End grouping conditions

        $this->db->order_by('ct.id', 'desc');

        $query = $this->db->get();

        // Fetch the results as an array
        $data['transactions'] = $query->result_array();

        // Example: Printing the result
        //echo '<pre>';print_r($transactions); die;
        //$this->load->view('coin/allocate_coins', $data);
        $data['_view'] = 'coin/allocate_coins';
        $this->load->view('layouts/main', $data);
    }

    //    public function processAllocationMaster() {
    //     // Get form data
    //     $receiver_id = $this->input->post('receiver_id', true);
    //     $master_id = $this->session->userdata('id');
    //     $amount = $this->input->post('amount', true);
    //     $transaction_type = $this->input->post('transactiontype', true);

    //     // Basic validation
    //     if (empty($receiver_id) || empty($amount) || empty($transaction_type)) {
    //         echo "<script>alert('All fields are required.'); window.history.back();</script>";
    //         return;
    //     }

    //     // Prepare transaction data
    //     $transaction_data = array(
    //         'receiver_id' => $receiver_id,
    //         'amount' => $amount,
    //         'created_at' => date('Y-m-d H:i:s'),
    //         'status' => 1 // Assuming 1 is active/successful
    //     );

    //     if ($transaction_type == 'D') {
    //         // Deposit
    //         $transaction_data['sender_id'] = $master_id;
    //         $transaction_data['type'] = 'allocation';
    //     } elseif ($transaction_type == 'W') {
    //         // Withdraw
    //         $transaction_data['sender_id'] = $receiver_id;
    //         $transaction_data['receiver_id'] = $master_id;
    //         $transaction_data['type'] = 'spend';
    //         $transaction_data['amount'] = -$amount;
    //     } else {
    //         echo "<script>alert('Invalid transaction type.'); window.history.back();</script>";
    //         return;
    //     }

    //     // Insert the transaction
    //     $this->db->insert('coin_transactions', $transaction_data);

    //     // Fetch latest record from tbl_final_hisab for this ledger
    //     $this->db->order_by('id', 'DESC');
    //     $latestHisab = $this->db->get_where('tbl_final_hisab', ['ledger_id' => $receiver_id])->row();

    //     if ($latestHisab) {
    //         $final_hisab = (float)$latestHisab->final_hisab;

    //         if ($transaction_type == 'D') {
    //             $final_hisab -= $amount;
    //         } elseif ($transaction_type == 'W') {
    //             $final_hisab += $amount;
    //         }

    //         // Prepare update data
    //         $updateData = [
    //             'final_hisab' => $final_hisab,
    //             'today_hisab' => $final_hisab,
    //             'updated_at' => date('Y-m-d H:i:s')
    //         ];

    //         // Update the latest entry
    //         $this->db->where('id', $latestHisab->id);
    //         $this->db->update('tbl_final_hisab', $updateData);
    //     }

    //     // Success message and redirect
    //     echo "<script>alert('Transaction successful.'); window.location.href='" . base_url('ledger') . "';</script>";
    // }

    //     public function processAllocationMaster()
    // {
    //     $receiver_id = $this->input->post('receiver_id', true);
    //     $master_id = $this->session->userdata('id');
    //     $amount = (float) $this->input->post('amount', true);
    //     $transaction_type = $this->input->post('transactiontype', true);
    //     $remarks = trim($this->input->post('remarks', true)) ?: 'Cash transaction';

    //     // Basic validation
    //     if (empty($receiver_id) || empty($amount) || empty($transaction_type) || $amount <= 0) {
    //         echo "<script>alert('All fields are required and amount must be positive.'); window.history.back();</script>";
    //         return;
    //     }

    //     // Prepare voucher data based on transaction type
    //     $voucher_data = [
    //         'Date' => date('Y-m-d'),
    //         'Amount' => $amount,
    //         'Remarks' => $remarks,
    //         'updated_at' => date('Y-m-d H:i:s'),
    //     ];

    //     if ($transaction_type == 'D') {
    //         // Deposit → client gives cash → collected by admin
    //         $voucher_data['PartyId'] = $receiver_id;
    //         $voucher_data['Collect_By'] = $master_id;
    //     } elseif ($transaction_type == 'W') {
    //         // Withdraw → admin gives cash → collected by client
    //         $voucher_data['PartyId'] = $master_id;
    //         $voucher_data['Collect_By'] = $receiver_id;
    //     } else {
    //         echo "<script>alert('Invalid transaction type.'); window.history.back();</script>";
    //         return;
    //     }

    //     // Insert into tbl_voucher
    //     $insert = $this->db->insert('tbl_voucher', $voucher_data);

    //     if ($insert) {
    //         echo "<script>alert('Transaction successful.'); window.location.href='" . base_url('ledger') . "';</script>";
    //     } else {
    //         echo "<script>alert('Transaction failed. Please try again.'); window.history.back();</script>";
    //     }
    // }
    // public function processAllocationMaster()
    // {
    //     $receiver_id = $this->input->post('receiver_id', true);
    //     $master_id = $this->session->userdata('id');
    //     $amount = (int) $this->input->post('amount', true);
    //     $transaction_type = $this->input->post('transactiontype', true);
    //     $remarks = trim($this->input->post('remarks', true)) ?: 'Cash transaction';

    //     // Basic validation
    //     if (empty($receiver_id) || empty($amount) || empty($transaction_type) || $amount <= 0) {
    //         echo "<script>alert('All fields are required and amount must be positive.'); window.history.back();</script>";
    //         return;
    //     }

    //     // Set base transaction data
    //     $coin_data = [
    //         'amount' => $amount,
    //         'status' => 1,
    //         'created_at' => date('Y-m-d H:i:s'),
    //     ];

    //     // Set sender/receiver and type based on transaction type
    //     if ($transaction_type == 'D') {
    //         // Deposit: admin → client
    //         $coin_data['type'] = 'allocation';
    //         $coin_data['sender_id'] = $master_id;
    //         $coin_data['receiver_id'] = $receiver_id;
    //         $coin_data['deposite_byto_master'] = 1;
    //     } elseif ($transaction_type == 'W') {
    //         // Withdraw: client → admin
    //         $coin_data['type'] = 'spend';
    //         $coin_data['sender_id'] = $receiver_id;
    //         $coin_data['receiver_id'] = $master_id;
    //         $coin_data['deposite_byto_master'] = 1;
    //     } else {
    //         echo "<script>alert('Invalid transaction type.'); window.history.back();</script>";
    //         return;
    //     }

    //     // Insert into coin_transactions
    //     $insert = $this->db->insert('coin_transactions', $coin_data);

    //     if ($insert) {
    //         echo "<script>alert('Transaction successful.'); window.location.href='" . base_url('ledger') . "';</script>";
    //     } else {
    //         echo "<script>alert('Transaction failed. Please try again.'); window.history.back();</script>";
    //     }
    // }

    public function processAllocationMaster()
    {
        $receiver_id = $this->input->post('receiver_id', true);
        $master_id = $this->session->userdata('id');
        $amount = (int) $this->input->post('amount', true);
        $transaction_type = $this->input->post('transactiontype', true);
        $remarks = trim($this->input->post('remarks', true)) ?: 'Cash transaction';

        if (empty($receiver_id) || empty($amount) || empty($transaction_type) || $amount <= 0) {
            echo "<script>alert('All fields are required and amount must be positive.'); window.history.back();</script>";
            return;
        }

        $coin_data = [
            'amount' => $amount,
            'status' => 1,
            'created_at' => date('Y-m-d H:i:s')
        ];
        $total_received = $this->db->select_sum('amount')
            ->from('coin_transactions')
            ->where('receiver_id', $master_id)
            ->where('deposite_byto_master', 0)
            ->get()->row()->amount ?? 0;

        $total_allocated = $this->db->select_sum('amount')
            ->from('coin_transactions')
            ->where('sender_id', $master_id)
            ->where('deposite_byto_master', 1)
            ->get()->row()->amount ?? 0;
        //echo $total_received. '  '.$total_allocated; die; 
        $master_balance = (int)$total_received - (int)$total_allocated;
        if ($transaction_type == 'D') {
            // Step 1: Calculate master's available balance


            if ($master_balance < $amount) {
                echo "<script>alert('Insufficient master balance to allocate this amount.'); window.history.back();</script>";
                return;
            }

            // Deposit: admin → client
            $coin_data['type'] = 'allocation';
            $coin_data['sender_id'] = $master_id;
            $coin_data['receiver_id'] = $receiver_id;
            $coin_data['deposite_byto_master'] = 1;

            // Update ledger: Set coin_balance to given amount
            $this->db->set('coin_balance', $amount);
            $this->db->where('id', $receiver_id);
            $this->db->update('tbl_ledger');
        } elseif ($transaction_type == 'W') {
            // 1. Validate client has enough balance
            //$ledgercoinbal = (int) $this->CoinModel->get_coin_balance($receiver_id);
            $ledgercoinbal = get_client_coin_balance($receiver_id);
            //echo $ledgercoinbal; die;
            if ($ledgercoinbal < $amount) {
                echo "<script>alert('Client has insufficient balance.'); window.history.back();</script>";
                return;
            }
            // Withdraw: client → admin
            $coin_data['type'] = 'spend';
            $coin_data['sender_id'] = $receiver_id;
            $coin_data['receiver_id'] = $master_id;
            $coin_data['deposite_byto_master'] = 1;
            // Optional: Master must also be allowed to receive (have balance capacity)

            // Check current balance first
            $ledger = $this->db->get_where('tbl_ledger', ['id' => $receiver_id])->row();
            $ledgercoinbal = $this->CoinModel->get_coin_balance($receiver_id);
            // echo $ledger->coin_balance .' '. $amount; die; 
            if ($ledger && $ledgercoinbal >= $amount) {
                // Deduct amount from receiver's balance
                $this->db->set('coin_balance', 'coin_balance - ' . $amount, false);
                $this->db->where('id', $receiver_id);
                $this->db->update('tbl_ledger');
                // 2. Add amount to master's balance
                $this->db->set('coin_balance', "coin_balance + {$amount}", false)
                    ->where('id', $master_id)
                    ->update('tbl_ledger');
            } else {
                echo "<script>alert('Insufficient balance for withdrawal.'); window.history.back();</script>";
                return;
            }
        } else {
            echo "<script>alert('Invalid transaction type.'); window.history.back();</script>";
            return;
        }

        $insert = $this->db->insert('coin_transactions', $coin_data);

        if ($insert) {
            echo "<script>alert('Transaction successful.'); window.location.href='" . base_url('ledger') . "';</script>";
        } else {
            echo "<script>alert('Transaction failed. Please try again.'); window.history.back();</script>";
        }
    }

    // Process Allocation
    public function processAllocation()
    {
        $receiver_id = $this->input->post('receiver_id');
        $amount = $this->input->post('amount');
        $sender_id = $this->session->userdata('id');
        $role = $this->session->userdata('role');
        $transactiontype = $this->input->post('transactiontype');
        if ($transactiontype == 'W') {
            $receiver_id = $this->session->userdata('id');
            $sender_id = $this->input->post('receiver_id');
        }
        // echo $transactiontype.' '.$receiver_id.' '.$sender_id; die;
        log_message('error', $transactiontype . ' ' . $receiver_id . ' ' . $sender_id);

        if ($role === 'Super Admin' || $role === 'Master') {
            if ($this->CoinModel->allocateCoins($sender_id, $receiver_id, $amount)) {
                if ($transactiontype == 'W') {
                    $this->session->set_flashdata('success', 'Coins withdraw successfully.');
                } else {
                    $this->session->set_flashdata('success', 'Coins allocated successfully.');
                }
            } else {
                $this->session->set_flashdata('error', 'Insufficient balance.');
            }
        } else {
            show_error('Unauthorized access.', 403);
        }
        //$this->session->set_flashdata('success', 'Coins allocated successfully!');
        //return true;
        redirect('ledger');
    }

    // View Balance
    public function viewBalance()
    {
        $user_id = $this->session->userdata('user_id');
        $data['balance'] = $this->CoinModel->getUserBalance($user_id);
        $this->load->view('coin/view_balance', $data);
    }
}
