<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Tbl_jantri extends CI_Controller
{
	function __construct()
	{
		parent::__construct();
		$this->load->model('Tbl_jantri_model');
		$this->load->model('Tbl_transactions_model');
		$this->load->model('Tbl_shift_model');
		$this->load->model('Tbl_ledger_model');
		$this->load->model('Tbl_staff_model');
		$this->load->library('session');
		$this->load->helper('url');
	}

	function view_jantri()
	{
		$id = $_GET['id'];
		$data['tbl_transactions'] = $this->Tbl_transactions_model->get_custom_transactions($id);
		$data['_view'] = 'tbl_jantri/viewjantri';
		if($this->session->userdata['role'] == 'Staff'){
			$this->load->view('layouts/mainold', $data);	
		}
		else{
			$this->load->view('layouts/main', $data);
		}
	}
	function view_jantri_total()
	{
		$pid = $_GET['pid'];
		$date = $_GET['date'];
		$data['tbl_transactions'] = $this->Tbl_transactions_model->get_custom_transactions_total_shift($pid, $date);
		$data['_view'] = 'tbl_jantri/viewjantri_total';
		$this->load->view('layouts/main', $data);
	}
	function view_jantri_intotal()
	{

		$data['tbl_transactions'] = $this->Tbl_jantri_model->get_all_tbl_jantri_intotal();
		$data['_view'] = 'tbl_jantri/view_jantri_intotal';
		if($this->session->userdata['role'] == 'Staff'){
			$this->load->view('layouts/mainold', $data);	
		}
		else{
			$this->load->view('layouts/main', $data);
		}
	}

	/*
     * Listing of tbl_jantri
     */
	function index()
	{
		/* $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tbl_jantri/index?');
        $config['total_rows'] = $this->Tbl_jantri_model->get_all_tbl_jantri_count();
        $this->pagination->initialize($config);

        $data['tbl_jantri'] = $this->Tbl_jantri_model->get_all_tbl_jantri($params);
        */
		$data['_view'] = 'tbl_jantri/index';
		$this->load->view('layouts/main', $data);
	}

	/*
     * Adding a new tbl_jantri
     */
	function cutjantritemp($useNewView = false)
	{ //pr($_GET,1);
		date_default_timezone_set('Asia/Kolkata');
		$data['tbl_transactions'] = [];
		$data['sendjantri'] = 0;
		$pid = '';
		$date = '';
		$baseShiftId = '';
		$selectedDate = date('Y-m-d');
		$data['apply_commission'] = $useNewView && $this->input->get('apply_commission') === '1';
		$data['apply_patti'] = $useNewView && $this->input->get('apply_patti') === '1';
		if (isset($_GET) && !(empty($_GET))) {
			//echo '<pre>'; print_r($_GET); echo '</pre>';	die;
			$pid = $_GET['pid'];
			$date = $_GET['date'];
			$selectedDate = date('Y-m-d', strtotime($date));
			$shiftRow = $this->Tbl_shift_model->get_tbl_shift_usershift($pid);
			$baseShiftId = !empty($shiftRow['shift_id']) ? $shiftRow['shift_id'] : $pid;
			$resolvedTiming = $this->Tbl_shift_model->get_cutjantri_timing_for_shift(
				$this->session->userdata['id'],
				$baseShiftId,
				$date
			);
			if (!empty($resolvedTiming['id'])) {
				$pid = $resolvedTiming['id'];
			}
			$jandata =  $this->Tbl_shift_model->get_master_jantri_temp($pid,$date);
			//echo '<pre>'; print_r($jandata); echo '</pre>'; die;
			if($jandata){
			// $databaseTime = $jandata->mastertime; // Replace with your actual database time

			// // Convert database time to 24-hour format for comparison
			// $databaseTime24 = date('H:i', strtotime($databaseTime));

			// // Get current time in 24-hour format
			// $current24 = date('H:i');
			// //echo $databaseTime24.$current24; die;
			// if($jandata->open_date == date('Y-m-d') && ($databaseTime24 > $current24)){
			// 	$data['sendjantri'] = 1;	
			// } 
			// else{
			// 	$data['sendjantri'] = 0;
			// }
				// Define the date and time
			$dateString = $jandata->open_date.' '.$jandata->mastertime;

			// Create a DateTime object from the date string
			$dateTime = new DateTime($dateString);

			// Get the Unix timestamp
			$dbtimestamp = $dateTime->getTimestamp();

			$currtimestamp = time();

			if($currtimestamp < $dbtimestamp){
				$data['sendjantri'] = 1;	
			} 
				else{
					$data['sendjantri'] = 0;
				}

		}
			//$data['sendjantri'] =
			if($this->session->userdata['id'] != '1'){
				$data['tbl_transactions'] = $this->Tbl_transactions_model->get_custom_transactions_total_shift_master($pid, $date);
				if (empty($data['tbl_transactions'])) {
					$data['tbl_transactions'] = $this->Tbl_transactions_model->get_custom_transactions_total_shift($baseShiftId, $date);
				}
			}
			else{
				//$data['tbl_transactions'] = $this->Tbl_transactions_model->get_custom_transactions_total_shift_admin($pid, $date);
				//$data['tbl_transactions'] = $this->Tbl_transactions_model->view_transaction_filter($pid, $date);
				$data['todate'] = $date;
				$data['shift_name'] = $baseShiftId;
				$data['created_by'] = '1';
				//to correct admin jantri bringh data in same format as non admin
				$data['tbl_transactions'] = $this->Tbl_transactions_model->view_transaction_filter_admin($data);
				if (empty($data['tbl_transactions'])) {
					$data['tbl_transactions'] = $this->Tbl_transactions_model->get_custom_transactions_total_shift($baseShiftId, $date);
				}
			}
			
		}
		// Match the same ownership rules as the working transaction page.
		$shiftOwnerId = $this->session->userdata['id'];
		$timeColumn = 'master';
		if ($this->session->userdata['role'] == 'Staff') {
			$tbl_staff = $this->Tbl_staff_model->get_tbl_staff($this->session->userdata['id']);
			if (!empty($tbl_staff['updated_by'])) {
				$shiftOwnerId = $tbl_staff['updated_by'];
			}
			$timeColumn = 'data_entry_operator';
		}

		// Use the selected business date so historical cut-jantri pages can
		// resolve the same timing row that was active when the transactions were booked.
		$data['shifts'] = $this->Tbl_shift_model->get_cutjantri_shifts_for_date(
			$shiftOwnerId,
			$selectedDate,
			$timeColumn
		);
		if (empty($data['shifts'])) {
			$fallbackEndDate = date('Y-m-d', strtotime($selectedDate.' +1 day'));
			$data['shifts'] = $this->Tbl_shift_model->get_all_tbl_shift_master_for_trans(
				$shiftOwnerId,
				$selectedDate,
				$fallbackEndDate,
				$timeColumn
			);
		}
		if (empty($data['shifts'])) {
			$data['shifts'] = $this->Tbl_shift_model->get_all_tbl_shift_master($shiftOwnerId);
		}
		$data['selected_shift_id'] = $pid;
		$tbl_ledger_elements = $this->Tbl_ledger_model->get_tbl_ledger($this->session->userdata['id']);
		$data['ledger'] = $tbl_ledger_elements;
		//echo '<pre>'; print_r($jandata); echo '</pre>'; die;
		$data['_view'] = $useNewView
			? 'tbl_jantri/cut_index_temp'
			: 'tbl_jantri/cut_index_legacy';
		$this->load->view('layouts/main', $data);
	}

	function cutjantrinew()
	{
		$this->cutjantritemp(true);
	}

	/*
     * Adding a new tbl_jantri
     */
	function cutjantri()
	{ //echo '<pre>'; print_r($_GET); echo '</pre>'; die;

		$data['tbl_transactions'] = [];
		if (isset($_GET) && !(empty($_GET))) {

			$pid = $_GET['pid'];
			$date = $_GET['date'];
			$data['tbl_transactions'] = $this->Tbl_transactions_model->get_custom_transactions_total_shift($pid, $date);
		}
		//echo '<pre>'; print_r($data); echo '</pre>'; die;
		$data['shifts'] = $this->Tbl_shift_model->get_all_tbl_shift();
		
		$data['_view'] = 'tbl_jantri/cut_index';
		$this->load->view('layouts/main', $data);
	}

	/*
     * Adding a new tbl_jantri
     */
	function add()
	{
		$this->load->library('form_validation');
		$data['error'] = '';
		$this->form_validation->set_rules('shift_name', 'Shift Name', 'max_length[255]');
		$this->form_validation->set_rules('next_day', 'Next Day', 'max_length[255]');
		$this->form_validation->set_rules('shift_working_for', 'Shift Working For', 'max_length[255]');
		$this->form_validation->set_rules('is_active', 'Is Active', 'integer');
		$this->form_validation->set_rules('updated_by', 'Updated By', 'integer');
		//echo '<pre>';print_r($this->session->userdata); die;
		//echo '<pre>';print_r($_POST); die;

		$mastr['shift_id'] = $_POST['shift'];
		$mastr['party_id'] = $_POST['party'];
		$mastr['t_date'] = date('Y-m-d', strtotime($_POST['tdate']));
		$mastr['total_number_amount'] = '';
		$mastr['total_akhar_amount'] = '';
		$tbl_transactions_id = $this->Tbl_transactions_model->add_tbl_transaction($mastr); //die;
		if ($tbl_transactions_id) { // echo $tbl_transactions_id; die;
			$tbl_master_transactions_id = $this->Tbl_transactions_model->add_jantri($tbl_transactions_id, $_POST);
			if ($tbl_master_transactions_id) {
				$this->session->set_flashdata('msg', 'Jantri Added');
				redirect('/transactions');
			}
		} else {
			return false;
		}
	}

	function partyjantri()
	{
		$data['tbl_transactions'] = [];
		if (isset($_GET) && !(empty($_GET))) {
			//echo '<pre>'; print_r($_GET); echo '</pre>';	die;
			$pid = $_GET['pid'];
			$date = $_GET['date'];
			$party = $_GET['partyid'];
			$data['tbl_transactions'] = $this->Tbl_transactions_model->get_custom_transactions_total_shift_party($pid, $date, $party);
		}
		//echo '<pre>'; print_r($data['tbl_transactions']); echo '</pre>'; die;
		$data['shifts'] = $this->Tbl_shift_model->get_all_tbl_shift_master($this->session->userdata['id']);
		$data['party'] = $this->Tbl_ledger_model->get_all_tbl_ledger_admin();
		//echo '<pre>';print_r($data); die;
		$data['_view'] = 'tbl_jantri/partyjantri';
		$this->load->view('layouts/main', $data);
	}

	/*
     * Editing a tbl_jantri
     */
	function edit($id)
	{
		// check if the tbl_jantri exists before trying to edit it
		$data['tbl_jantri'] = $this->Tbl_jantri_model->get_tbl_jantri($id);
		$data['error'] = '';
		if (isset($data['tbl_jantri']['id'])) {
			$this->load->library('form_validation');

			$this->form_validation->set_rules('shift_name', 'Shift Name', 'max_length[255]');
			$this->form_validation->set_rules('next_day', 'Next Day', 'max_length[255]');
			$this->form_validation->set_rules('shift_working_for', 'Shift Working For', 'max_length[255]');
			$this->form_validation->set_rules('is_active', 'Is Active', 'integer');
			$this->form_validation->set_rules('updated_by', 'Updated By', 'integer');

			if ($this->form_validation->run()) {
				//echo $this->Tbl_jantri_model->checkDuplicate($this->input->post('shift_name'),$this->session->userdata['id']); die;				
				if ($this->Tbl_jantri_model->checkDuplicate($this->input->post('shift_name'), $this->session->userdata['id']) == '1') {
					$data['error'] = "Duplicate Entry Found.Please try with other name.";
				} else {
					$params = array(
						'shift_name' => $this->input->post('shift_name'),
						'open_date' => $this->input->post('open_date'),
						'next_day' => $this->input->post('next_day'),
						'shift_working_for' => $this->input->post('shift_working_for'),
						'owner' => $this->input->post('owner'),
						'super_admin' => $this->input->post('super_admin'),
						'fanter' => $this->input->post('fanter'),
						'cash_agent' => $this->input->post('cash_agent'),
						'admin' => $this->input->post('admin'),
						'data_entry_operator' => $this->input->post('data_entry_operator'),
						'is_active' => $this->input->post('is_active'),
						'updated_by' => $this->session->userdata['id'],
						'updated_date' => $this->input->post('updated_date'),
					);

					$this->Tbl_jantri_model->update_tbl_jantri($id, $params);
					redirect('/shift_master');
				}
			}
			// else
			// {
			$data['_view'] = 'tbl_jantri/edit';
			$this->load->view('layouts/main', $data);
			// }
		} else
			show_error('The tbl_jantri you are trying to edit does not exist.');
	}

	/*
     * Deleting tbl_jantri
     */
	function remove($id)
	{
		$tbl_jantri = $this->Tbl_jantri_model->get_tbl_jantri($id);

		// check if the tbl_jantri exists before trying to delete it
		if (isset($tbl_jantri['id'])) {
			$this->Tbl_jantri_model->delete_tbl_jantri($id);
			redirect('shift_master');
		} else
			show_error('The tbl_jantri you are trying to delete does not exist.');
	}
	function add_jantri()
	{
		//print_r($_SERVER['HTTP_REFERER']);
		//print_r($_POST['dindex']);
		$tbl_transactions_id = $this->Tbl_transactions_model->add_tbl_transaction($_POST);
		//unset($_POST['shift']);
		if ($tbl_transactions_id) { // echo $tbl_transactions_id; die; 
			$tbl_master_transactions_id = $this->Tbl_transactions_model->add_jantri($tbl_transactions_id, $_POST);
			if ($tbl_master_transactions_id) {
				$this->session->set_flashdata('msg', 'Random Form Added');
				redirect('/transactions');
			}
		} else {
			return false;
		}
	}
	function add_jantri_form()
	{
		//print_r($_SERVER['HTTP_REFERER']);
		//print_r($_POST['dindex']);
		//$post = array_values(array_filter($_POST));
		foreach ($_POST as $key => $val) {
			if ($val == '') {
				$_POST[$key] = 0;
			}
		}
		$trnamt = $trnum = array();
		foreach ($_POST['trn_amount'] as $key => $val) {
			if ($val == '') {
				unset($_POST['trn_amount'][$key]);
			}
		}
		$_POST['trn_number'] = array_keys($_POST['trn_amount']);
		foreach ($_POST['trn_number'] as $keyt => $valt) {
			if ($valt == '99') {
				$_POST['trn_number'][$keyt] = '00';
			} else {
				$_POST['trn_number'][$keyt] = sprintf("%02d", $valt + 1);
			}
		}
		if (isset($_POST['b'])) {
			foreach ($_POST['b'] as $bkey => $val) {
				$bkey = $bkey + 1;
				if ($bkey == 10) {
					$bkey = 0;
				}
				if ($val == '') {
					unset($_POST['b'][$bkey]);
				} else {
					$bak = $bkey . $bkey . $bkey;
					array_push($_POST['trn_number'], $bak);
					array_push($_POST['trn_amount'], $val);
				}
			}
		}
		if (isset($_POST['a'])) {
			foreach ($_POST['a'] as $akey => $val) {
				$akey = $akey + 1;
				if ($akey == 10) {
					$akey = 0;
				}
				if ($val == '') {
					unset($_POST['a'][$akey]);
				} else {
					$abak = $akey . $akey . $akey . $akey;
					array_push($_POST['trn_number'], $abak);
					array_push($_POST['trn_amount'], $val);
				}
			}
		}

		$_POST['ttamntt'] = $_POST['total_all'] + $_POST['total_b'] + $_POST['total_a'];
		//	$trnamt = implode(',',$trnamt);
		//$trnum = implode(',',$trnum);
		//$post['']
		// = 
		//
		//echo '<pre>'; print_r($trnum); print_r($_POST); echo '</pre>'; die;
		$trn_amount = $_POST['trn_amount'];
		//echo '<pre>'; print_r($_POST); echo '</pre>';
		//$f2tno = array_sum($trn_amount);
		//$f4tno = $_POST['tamount'];
		//$tnocross = $_POST['total_amount_cross'];
		//$tnofromto = $_POST['total_amount_fromto'];
		//$f8tno = count(explode(' ',$_POST['dara_f8']))*($_POST['dara_amount_f8']);
		//$f8akharbahartno = (strlen($_POST['akhar_bahar_f8']))* ($_POST['amount_akahr_bahar_f8']);
		//$f8akharandertno = (strlen($_POST['akahr_andar_f8']))* ($_POST['amount_akahr_andar_f8']);
		//$ttnumber = $f2tno + $f4tno + $tnofromto + $f8tno+$tnocross;
		$ttnumber = $_POST['ttamntt'];
		//$ttakharno =  $f8akharbahartno + $f8akharandertno;
		$mastr['shift_id'] = $_POST['shift'];
		$mastr['party_id'] = $_POST['party'];
		$mastr['master_id'] = $_SESSION['updated_by'];
		$mastr['t_date'] = date('Y-m-d', strtotime($_POST['dateoftrn']));
		$mastr['total_number_amount'] = $ttnumber;
		$mastr['total_akhar_amount']= $_POST['total_b'] + $_POST['total_a'];

		$tbl_ledger_elements = $this->Tbl_ledger_model->get_tbl_ledger($_POST['party']);
		//echo '<pre>'; print_r($tbl_ledger_elements); echo '</pre>'; die;
		$Tb_Date_shift_party_entry['DaraRate'] = $tbl_ledger_elements['dara_rate'];
		$Tb_Date_shift_party_entry['Commision'] = $tbl_ledger_elements['dara_commision'];
		$Tb_Date_shift_party_entry['AkarRate'] = $tbl_ledger_elements['akhar_rate'];
		$Tb_Date_shift_party_entry['Commission'] = $tbl_ledger_elements['akhar_commission'];
		$Tb_Date_shift_party_entry['Rebait'] = $tbl_ledger_elements['rebate'];
		$Tb_Date_shift_party_entry['TP_person'] = $tbl_ledger_elements['tp_party_id'];
		$Tb_Date_shift_party_entry['TP_perc'] = $tbl_ledger_elements['tppercentage'];
		$Tb_Date_shift_party_entry['ShiftId'] = $_POST['shift'];
		$Tb_Date_shift_party_entry['PartyId'] = $_POST['party'];
		$Tb_Date_shift_party_entry['Date'] = date('Y-m-d', strtotime($_POST['dateoftrn']));
		$Tb_Date_shift_party_entry['Total_Number_amount'] = $ttnumber;
		//$Tb_Date_shift_party_entry['Total_Akhar_amount']=$ttakharno;
		$Tb_Date_shift_party_entry['Total_amount'] = $ttnumber;
		/*echo '<pre>'; print_r($_POST['trn_number']); echo '</pre>';
		$_POST['trn_number'] = array_map(
    function($v) { if ($v == '00') $v = '100'; return $v; },
    $_POST['trn_number']
);
$_POST['number'] = array_map(
    function($v) { if ($v == '00') $v = '100'; return $v; },
    $_POST['number']
);
if($_POST['fromto_from']=='00'){
	$_POST['fromto_from'] = 100;
}
if($_POST['fromto_to']=='00'){
	$_POST['fromto_to'] = 100;
}
	//	$num_f2 = $_POST['trn_number'];
			//$num_f2 = array_map($this->replaceHundreds, $num_f2);
		echo '<pre>'; print_r($_POST['trn_number']); echo '</pre>'; die;*/
		$tbl_transactions_id = $this->Tbl_transactions_model->add_tbl_transaction($mastr); //die;
		$tbl_transactions_only_id = $this->Tbl_transactions_model->add_tbl_only_transaction_may($tbl_transactions_id, $_POST);
		/*added later*/	//$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->add_Tb_Date_shift_party_entry($tbl_transactions_id,$Tb_Date_shift_party_entry);	

		/* //commented for only number amount entry//	$tbl_transactions_rndomf4 = $this->Tbl_transactions_model->add_tbl_randomf4($tbl_transactions_id,$_POST);
		$tbl_transactions_cross = $this->Tbl_transactions_model->add_cross($tbl_transactions_id,$_POST);
		$tbl_transactions_add_fromto = $this->Tbl_transactions_model->add_fromto($tbl_transactions_id,$_POST);
		$tbl_transactions_random_f8 = $this->Tbl_transactions_model->random_f8($tbl_transactions_id,$_POST);*/
		//$if_trn_exist = $this->Tbl_transactions_model->get_Date_shift_party_entry($_POST['shift'], $_POST['party'], date('Y-m-d', strtotime($_POST['dateoftrn'])));
		//echo '<pre>';print_r($if_trn_exist);die;
		// if (!empty($if_trn_exist)) { //echo  'there';die;
		// 	$odata = $this->Tbl_transactions_model->get_transaction_result_total($if_trn_exist[0]['id']);
		// 	//echo '<pre>';print_r($odata); die;
		// 	$uTb_Date_shift_party_entry['Total_Number_amount'] = $ttnumber + $odata['Total_Number_amount'];
		// 	$uTb_Date_shift_party_entry['Total_Akhar_amount'] = $ttakharno + $odata['Total_Akhar_amount'];
		// 	$uTb_Date_shift_party_entry['Total_amount'] = $ttnumber + $ttakharno + $odata['Total_amount'];
		// 	$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->update_Tb_Date_shift_party_entry($if_trn_exist[0]['id'], $uTb_Date_shift_party_entry);
		// } else {  //echo  'here';die;
//			$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->add_Tb_Date_shift_party_entry($Tb_Date_shift_party_entry);
			//echo $Tb_Date_shift_party_entry_id;	die;
		//}
		/*$this->session->set_flashdata('msg', 'Transactions Added');
				 redirect(site_url('/transactions'));*/

				 $if_trn_exist = $this->Tbl_transactions_model->get_Date_shift_party_entry($_POST['shift'], $_POST['party'], date('Y-m-d', strtotime($_POST['dateoftrn'])));
				 //echo '<pre>';print_r($if_trn_exist);//die;
				 if (!empty($if_trn_exist)) { //echo  'there';die;
					 $odata = $this->Tbl_transactions_model->get_transaction_result_total($if_trn_exist[0]['id']);
					 //echo '<pre>';print_r($odata); die;
					 //$uTb_Date_shift_party_entry['Total_Number_amount']=$ttnumber+$odata['Total_Number_amount'];
					 //$uTb_Date_shift_party_entry['Total_Akhar_amount']=$ttakharno+$odata['Total_Akhar_amount'];
					 //$uTb_Date_shift_party_entry['Total_amount']=$ttnumber+$ttakharno+$odata['Total_amount'];
					 $uTb_Date_shift_party_entry['Total_Number_amount'] = $ttnumber;
					 $uTb_Date_shift_party_entry['Total_Akhar_amount'] = $mastr['total_akhar_amount'];
					 $uTb_Date_shift_party_entry['Total_amount'] = $ttnumber + $mastr['total_akhar_amount'];
					 //echo '<pre>'; print_r($uTb_Date_shift_party_entry); echo '</pre>'; die;
					 $Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->update_Tb_Date_shift_party_entry($if_trn_exist[0]['id'], $uTb_Date_shift_party_entry);
				 } else {  //echo  'here';die;
					 $Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->add_Tb_Date_shift_party_entry($Tb_Date_shift_party_entry);
				 }
		$this->session->set_flashdata('message', 'Transactions Added');
		redirect('/transactions');
	}

	function add_jantri_form_live(){
		//print_r($_SERVER['HTTP_REFERER']);
			//print_r($_POST['dindex']);
			//$post = array_values(array_filter($_POST));
			foreach($_POST as $key => $val){
				if($val==''){
					$_POST[$key]=0;
				}
			}
			$trnamt = $trnum = array();
			foreach($_POST['trn_amount'] as $key => $val){
				if($val==''){
					unset($_POST['trn_amount'][$key]);
				}
			}
			$_POST['trn_number']= array_keys($_POST['trn_amount']);
			foreach($_POST['trn_number'] as $keyt => $valt){
				if($valt=='99'){
					$_POST['trn_number'][$keyt] = '00';
				}
				else{
				$_POST['trn_number'][$keyt]= sprintf("%02d", $valt+1);
			}
			}
			if(isset($_POST['b'])){
			foreach($_POST['b'] as $bkey => $val){
				$bkey = $bkey+1;
				if($bkey==10){
					$bkey = 0;
				}
				if($val==''){
					unset($_POST['b'][$bkey]);
				}
				else{
				$bak = $bkey.$bkey.$bkey;
				array_push($_POST['trn_number'],$bak);
				array_push($_POST['trn_amount'],$val);
			}	
			}
			}
			if(isset($_POST['a'])){
			foreach($_POST['a'] as $akey => $val){
				$akey = $akey+1;
				if($akey==10){
					$akey = 0;
				}
				if($val==''){
					unset($_POST['a'][$akey]);
				}
				else{
				$abak = $akey.$akey.$akey.$akey;
				array_push($_POST['trn_number'],$abak);
				array_push($_POST['trn_amount'],$val);
			}
			}	
			}
			
			$_POST['ttamntt'] = $_POST['total_all']+$_POST['total_b']+$_POST['total_a'];
		//	$trnamt = implode(',',$trnamt);
			//$trnum = implode(',',$trnum);
			//$post['']
			// = 
			//
	//echo '<pre>'; print_r($trnum); print_r($_POST); echo '</pre>'; die;
			$trn_amount = $_POST['trn_amount'];
			//echo '<pre>'; print_r($_POST); echo '</pre>';
			//$f2tno = array_sum($trn_amount);
			//$f4tno = $_POST['tamount'];
			//$tnocross = $_POST['total_amount_cross'];
			//$tnofromto = $_POST['total_amount_fromto'];
			//$f8tno = count(explode(' ',$_POST['dara_f8']))*($_POST['dara_amount_f8']);
			//$f8akharbahartno = (strlen($_POST['akhar_bahar_f8']))* ($_POST['amount_akahr_bahar_f8']);
			//$f8akharandertno = (strlen($_POST['akahr_andar_f8']))* ($_POST['amount_akahr_andar_f8']);
			//$ttnumber = $f2tno + $f4tno + $tnofromto + $f8tno+$tnocross;
			$ttnumber = $_POST['ttamntt'];
			//$ttakharno =  $f8akharbahartno + $f8akharandertno;
			$mastr['shift_id']= $_POST['shift'];
			$mastr['party_id']= $_POST['party'];
			$mastr['t_date']= date('Y-m-d',strtotime($_POST['dateoftrn']));
			$mastr['total_number_amount']= $ttnumber;
			//$mastr['total_akhar_amount']= $ttakharno;
			
			$tbl_ledger_elements= $this->Tbl_ledger_model->get_tbl_ledger($_POST['party']);
			//echo '<pre>'; print_r($tbl_ledger_elements); echo '</pre>'; die;
			$Tb_Date_shift_party_entry['DaraRate']=$tbl_ledger_elements['dara_rate'];
			$Tb_Date_shift_party_entry['Commision']=$tbl_ledger_elements['dara_commision'];
			$Tb_Date_shift_party_entry['AkarRate']=$tbl_ledger_elements['akhar_rate'];
			$Tb_Date_shift_party_entry['Commission']=$tbl_ledger_elements['akhar_commission'];
			$Tb_Date_shift_party_entry['Rebait']=$tbl_ledger_elements['rebate'];
			$Tb_Date_shift_party_entry['TP_person']=$tbl_ledger_elements['tp_party_id'];
			$Tb_Date_shift_party_entry['TP_perc']=$tbl_ledger_elements['tppercentage'];
			$Tb_Date_shift_party_entry['ShiftId']=$_POST['shift'];
			$Tb_Date_shift_party_entry['PartyId']=$_POST['party'];
			$Tb_Date_shift_party_entry['Date']=date('Y-m-d', strtotime($_POST['dateoftrn']));
			$Tb_Date_shift_party_entry['Total_Number_amount']=$ttnumber;
			//$Tb_Date_shift_party_entry['Total_Akhar_amount']=$ttakharno;
			$Tb_Date_shift_party_entry['Total_amount']=$ttnumber;
			/*echo '<pre>'; print_r($_POST['trn_number']); echo '</pre>';
			$_POST['trn_number'] = array_map(
		function($v) { if ($v == '00') $v = '100'; return $v; },
		$_POST['trn_number']
	);
	$_POST['number'] = array_map(
		function($v) { if ($v == '00') $v = '100'; return $v; },
		$_POST['number']
	);
	if($_POST['fromto_from']=='00'){
		$_POST['fromto_from'] = 100;
	}
	if($_POST['fromto_to']=='00'){
		$_POST['fromto_to'] = 100;
	}
		//	$num_f2 = $_POST['trn_number'];
				//$num_f2 = array_map($this->replaceHundreds, $num_f2);
			echo '<pre>'; print_r($_POST['trn_number']); echo '</pre>'; die;*/
			$tbl_transactions_id = $this->Tbl_transactions_model->add_tbl_transaction($mastr);//die;
			$tbl_transactions_only_id = $this->Tbl_transactions_model->add_tbl_only_transaction_may($tbl_transactions_id,$_POST);
		/*added later*/	//$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->add_Tb_Date_shift_party_entry($tbl_transactions_id,$Tb_Date_shift_party_entry);	
			
			/* //commented for only number amount entry//	$tbl_transactions_rndomf4 = $this->Tbl_transactions_model->add_tbl_randomf4($tbl_transactions_id,$_POST);
			$tbl_transactions_cross = $this->Tbl_transactions_model->add_cross($tbl_transactions_id,$_POST);
			$tbl_transactions_add_fromto = $this->Tbl_transactions_model->add_fromto($tbl_transactions_id,$_POST);
			$tbl_transactions_random_f8 = $this->Tbl_transactions_model->random_f8($tbl_transactions_id,$_POST);*/
			$if_trn_exist = $this->Tbl_transactions_model->get_Date_shift_party_entry($_POST['shift'],$_POST['party'],date('Y-m-d', strtotime($_POST['dateoftrn'])));
			//echo '<pre>';print_r($if_trn_exist);die;
			if(!empty($if_trn_exist)){ //echo  'there';die;
				$odata = $this->Tbl_transactions_model->get_transaction_result_total($if_trn_exist[0]['id']);
				//echo '<pre>';print_r($odata); die;
				$uTb_Date_shift_party_entry['Total_Number_amount']=$ttnumber+$odata['Total_Number_amount'];
			$uTb_Date_shift_party_entry['Total_Akhar_amount']=$odata['Total_Akhar_amount'];
			$uTb_Date_shift_party_entry['Total_amount']=$ttnumber+$odata['Total_amount'];
			$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->update_Tb_Date_shift_party_entry($if_trn_exist[0]['id'],$uTb_Date_shift_party_entry);
			}
			else{  //echo  'here';die;
			$Tb_Date_shift_party_entry_id = $this->Tbl_transactions_model->add_Tb_Date_shift_party_entry($Tb_Date_shift_party_entry);	
			//echo $Tb_Date_shift_party_entry_id;	die;
		} 
			/*$this->session->set_flashdata('msg', 'Transactions Added');
					 redirect(site_url('/transactions'));*/
					 $this->session->set_flashdata('message','Transactions Added');
					redirect('/transactions');
		}
}
