<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 defined('BASEPATH') OR exit('No direct script access allowed');
class Common_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get all shift entries
     */
   public function getallshift()
    {
        $query = $this->db->get('tbl_shift');

        return $query->result_array();
    }
	/*
     * Get all shift entries
     */
   public function getallshiftadmin()
    {
        $query = $this->db->get('tbl_shift');

        return $query->result_array();
    }
	
     /*
     * Get all ledger entries
     */
   public function getallledger()
    {
        $query = $this->db->get('tbl_ledger');

        return $query->result_array();
    }   
   
   public function created_by()
    {
        $query = $this->db->get('tbl_user_login');
		
        return $query->result_array();
    }   
   
}
