<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_kist_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_kist by id
     */
    function get_tbl_kist($id)
    {
        return $this->db->get_where('tbl_kist',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all tbl_kist count
     */
    function get_all_tbl_kist_count()
    {
        $this->db->from('tbl_kist');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tbl_kist
     */
    function get_all_tbl_kist($params = array())
    {
		$this->db->select('tbl_kist.*,tl.ledger_name as partyname');
		$this->db->from('tbl_kist');
		$this->db->join('tbl_ledger as tl', 'tl.id = tbl_kist.PartyId');		
		//$this->db->join('tbl_ledger as tll', 'tll.id = tbl_kist.Collect_By');
        //$this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
		$query = $this->db->get();
		//echo $this->db->last_query(); die;
        return $query->result_array();
        /*$this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tbl_kist')->result_array();*/
		//$arr= $this->db->get('tbl_kist')->result_array();
		
		//$arr['party_name'] = $this->get_ledger_name($arr['PartyId']);
//$arr['collected_by'] = $this->get_ledger_name($arr['Collect_By']);
    }
	
	/*
     * Get all tbl_kist for admin
     */
    function get_all_tbl_kist_admin($params = array())
    {    $admin_id = $this->session->userdata['id'];
		$this->db->select('tbl_kist.*,tl.ledger_name as partyname');
		$this->db->from('tbl_kist');
		$this->db->join('tbl_ledger as tl', 'tl.id = tbl_kist.PartyId');
		//$this->db->join('tbl_admin', 'tbl_admin.id = tl.updated_by');
		//$this->db->join('tbl_ledger as tll', 'tll.id = tbl_kist.Collect_By');
        //$this->db->order_by('id', 'desc');
        $this->db->where('tl.updated_by',$admin_id);
		if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
		$query = $this->db->get();
		//echo $this->db->last_query(); die;
        return $query->result_array();
        /*$this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tbl_kist')->result_array();*/
		//$arr= $this->db->get('tbl_kist')->result_array();
		
		//$arr['party_name'] = $this->get_ledger_name($arr['PartyId']);
//$arr['collected_by'] = $this->get_ledger_name($arr['Collect_By']);
    }
	
	/*
     * Get all tbl_ledger_name
     */
    function get_ledger_name($id)
    {
       return $this->db->get_where('tbl_ledger',array('id'=>$id))->row_array();
    }
        
    /*
     * function to add new tbl_kist
     */
    function add_tbl_kist($params)
    {
        $this->db->insert('tbl_kist',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_kist
     */
    function update_tbl_kist($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_kist',$params);
    }
    
    /*
     * function to delete tbl_kist
     */
    function delete_tbl_kist($id)
    {
        return $this->db->delete('tbl_kist',array('id'=>$id));
    }
}
