<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_shift_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /* 
     * Get tbl_shift by id
     */
    function get_tbl_shift($id)
    {
        return $this->db->get_where('tbl_shift',array('id'=>$id))->row_array();
    }
    function get_tbl_shift_from_usershift($id)
    {
        $this->db->select('tbl_shift.*,user_shift_timings.id as usershiftid');
        $this->db->from('user_shift_timings');
        $this->db->join('tbl_shift', 'user_shift_timings.shift_id = tbl_shift.id', 'left');
        $this->db->where('user_shift_timings.id', $id);
        $result = $this->db->get()->row_array();
       //echo $this->db->last_query(); die; 
        return $result;
       
    }

    function check_usershifttiming_master($shift_id,$updated_by,$open_date){
        $this->db->select('user_shift_timings.*');
        $this->db->from('user_shift_timings');
        $this->db->where('user_shift_timings.updated_by', $updated_by);
        $this->db->where('user_shift_timings.id', $shift_id);
        $this->db->where('user_shift_timings.open_date', $open_date);
        $result = $this->db->get()->row_array();
        //echo $this->db->last_query(); die; 
         return $result;
    }
    function check_usershifttiming($shift_id,$updated_by,$open_date){
        $this->db->select('user_shift_timings.*');
        $this->db->from('user_shift_timings');
        $this->db->where('user_shift_timings.updated_by', $updated_by);
        $this->db->where('user_shift_timings.shift_id', $shift_id);
        $this->db->where('user_shift_timings.open_date', $open_date);
        $result = $this->db->get()->row_array();
        //echo $this->db->last_query(); die; 
         return $result;
    }
function get_tbl_shift_usershift($id)
    {
        $this->db->select('user_shift_timings.*, tbl_shift.shift_name');
        $this->db->from('user_shift_timings');
        $this->db->join('tbl_shift', 'user_shift_timings.shift_id = tbl_shift.id', 'left');
        $this->db->where('user_shift_timings.id', $id);
        $result = $this->db->get()->row_array();
       //echo $this->db->last_query(); die; 
        return $result;
       
    }
    function get_tbl_shift_usershift_bymasterid($id)
    {
        $this->db->select('user_shift_timings.*, tbl_shift.shift_name');
        $this->db->from('user_shift_timings');
        $this->db->join('tbl_shift', 'user_shift_timings.shift_id = tbl_shift.id', 'left');
        $this->db->where('user_shift_timings.master_id', $id);
        $this->db->where('user_shift_timings.open_date >=', date('Y-m-d'));
        $result = $this->db->get()->result_array();
       //echo $this->db->last_query(); die; 
        return $result;
       
    }
    
    /* 
     * Get tbl_shift by id
     */
    function get_tbl_shift_time($id,$master_id)
    { 
        // Join the tbl_shift table with user_shift_timings table
        $this->db->select('user_shift_timings.*, tbl_shift.shift_name');
        $this->db->from('user_shift_timings');
        $this->db->join('tbl_shift', 'user_shift_timings.shift_id = tbl_shift.id', 'left');
        $this->db->where('user_shift_timings.id', $id);
        $this->db->group_start();
        $this->db->where('user_shift_timings.master_id', $master_id);
        $this->db->or_where('user_shift_timings.master_id', '1');
        $this->db->or_where('user_shift_timings.master_id IS NULL', null, false);
        $this->db->group_end();
        // Get the result as an array
        $result = $this->db->get()->row_array();
       //echo $this->db->last_query(); die; 
        return $result;
    }
    
    /*
     * Get all tbl_shift count
     */
    function get_all_tbl_shift_count()
    {
        $this->db->from('tbl_shift');
		$this->db->order_by('orderby', 'asc');
        return $this->db->count_all_results();
    }
    function get_all_tbl_shift_master_for_transold($updated_by,$fromdate,$todate){
        $this->db->select('tbl_shift.id AS tbl_shift_id, 
        tbl_shift.*, 
        user_shift_timings.id AS user_shift_timing_id, 
        user_shift_timings.*, 
        tbl_shift.open_date AS tbl_shift_open_date, 
        user_shift_timings.open_date AS user_shift_open_date');
        $this->db->from('user_shift_timings');
        $this->db->join('tbl_shift', 'user_shift_timings.shift_id = tbl_shift.id', 'left');
        $this->db->where('user_shift_timings.updated_by', $updated_by);
        $this->db->where('user_shift_timings.open_date >=', $fromdate);
        $this->db->where('user_shift_timings.open_date <=', $todate);
        $this->db->where('user_shift_timings.is_active = 1');
        //$this->db->order_by('user_shift_timings.open_date', 'ASC'); // Order by date ascending
        $this->db->order_by('user_shift_timings.master', 'ASC'); // Order by time ascending
        $result = $this->db->get()->result_array();
       // echo $this->db->last_query(); die; 
         return $result;
    }
    
function get_all_tbl_shift_master_for_trans($updated_by, $fromdate, $todate)
{
    $this->db->select('
        tbl_shift.id AS tbl_shift_id,
        tbl_shift.*,
        user_shift_timings.id AS user_shift_timing_id,
        user_shift_timings.*,
        tbl_shift.open_date AS tbl_shift_open_date,
        user_shift_timings.open_date AS user_shift_open_date
    ');

    $this->db->from('user_shift_timings');

    $this->db->join(
        'tbl_shift',
        'user_shift_timings.shift_id = tbl_shift.id',
        'left'
    );

    $this->db->where('user_shift_timings.updated_by', $updated_by);
    $this->db->where('user_shift_timings.open_date >=', $fromdate);
    $this->db->where('user_shift_timings.open_date <=', $todate);
    $this->db->where('user_shift_timings.is_active', 1);

    // 1. Sort by date
    $this->db->order_by(
        'user_shift_timings.open_date',
        'ASC'
    );

    // 2. PM first, AM always last
    $this->db->order_by("
        CASE
            WHEN UPPER(user_shift_timings.master) LIKE '%AM' THEN 1
            ELSE 0
        END
    ", 'ASC', false);

    // 3. Sort actual time chronologically
    $this->db->order_by("
        STR_TO_DATE(user_shift_timings.master, '%h:%i %p')
    ", 'ASC', false);

    $result = $this->db->get()->result_array();

    // Debug:
    // echo $this->db->last_query();
    // die;

    return $result;
}
    function get_all_tbl_shift_master_cutjantri($params = array())
    {
//print_r($this->session->userdata['userid']); die;
		 $this->db->select('tbl_shift.*,user_shift_timings.*');
		$this->db->from('user_shift_timings');
        $this->db->join('tbl_shift', 'user_shift_timings.shift_id=tbl_shift.id','left');
			//if(isset($this->session->userdata['userid']) && $this->session->userdata['userid'] != '1'){
			//if(!empty($params)){
		$this->db->where('user_shift_timings.updated_by',$this->session->userdata['userid']);
        //$this->db->or_where('user_shift_timings.updated_by','1');	
			//}			
			//}
            //else{
               // $this->db->or_where('tbl_shift.updated_by','1');
           // }
        //$this->db->order_by('id', 'desc');
        
		$result = $this->db->get()->result_array();
        echo $this->db->last_query(); die; 
         return $result;
    }
    function get_all_tbl_shift_master($params = array())
    { //print_r($this->session->userdata['userid']); die;
		//  $this->db->select('tbl_shift.*,user_shift_timings.*');
		// $this->db->from('user_shift_timings');
        // $this->db->join('tbl_shift', 'user_shift_timings.shift_id=tbl_shift.id','left');
		// 	//if(isset($this->session->userdata['userid']) && $this->session->userdata['userid'] != '1'){
		// 	if(!empty($params)){
		// $this->db->where('user_shift_timings.updated_by',$params);
        // //$this->db->or_where('user_shift_timings.updated_by','1');	
		// 	}			
		// 	//}
        //     //else{
        //         $this->db->or_where('tbl_shift.updated_by','1');
        //    // }
        // //$this->db->order_by('id', 'desc');
        
		// $query = $this->db->get();
         $tbl_shift_updated_by = 1;
         $user_shift_updated_by = $this->session->userdata['userid'];
         $this->db->select('
         tbl_shift.id AS tbl_shift_id, 
         tbl_shift.*, 
         user_shift_timings.id AS user_shift_timing_id, 
         user_shift_timings.*, 
         tbl_shift.open_date AS tbl_shift_open_date, 
         user_shift_timings.open_date AS user_shift_open_date,
         tbl_shift.updated_by as adminshift
     ');
     $this->db->from('tbl_shift');
     $this->db->join('user_shift_timings', 'tbl_shift.id = user_shift_timings.shift_id AND user_shift_timings.updated_by IN (1, '.$user_shift_updated_by.')', 'left');
     $this->db->group_start();
     $this->db->where('tbl_shift.updated_by', $tbl_shift_updated_by);
     $this->db->or_where_in('user_shift_timings.updated_by', [1, $user_shift_updated_by]);
     $this->db->group_end();
     $this->db->group_by('tbl_shift.id');
        $query = $this->db->get();
        // echo $this->db->last_query(); die;

        // $this->db->select('tbl_shift.id AS tbl_shift_id, tbl_shift.*, user_shift_timings.id AS user_shift_timing_id, user_shift_timings.*')
        //  ->from('tbl_shift')
        //  ->join('user_shift_timings', 'tbl_shift.id = user_shift_timings.shift_id', 'left')
        //  ->where('user_shift_timings.updated_by', $user_shift_updated_by)
        //  ->group_start() // Start grouping for complex OR condition
        //  ->where('user_shift_timings.shift_id IS NOT NULL')
        //  ->or_where('tbl_shift.id NOT IN (SELECT shift_id FROM user_shift_timings)', NULL, FALSE)
        //  ->group_end() // End grouping
        //  ->group_by('tbl_shift.id');

        // $query = $this->db->get();
        //echo $this->db->last_query(); die;
        $result = $query->result_array();
            return $result;
    }
       function get_all_tbl_shift_app_add($userid)
    { //print_r($this->session->userdata['userid']); die;
		//  $this->db->select('tbl_shift.*,user_shift_timings.*');
		// $this->db->from('user_shift_timings');
        // $this->db->join('tbl_shift', 'user_shift_timings.shift_id=tbl_shift.id','left');
		// 	//if(isset($this->session->userdata['userid']) && $this->session->userdata['userid'] != '1'){
		// 	if(!empty($params)){
		// $this->db->where('user_shift_timings.updated_by',$params);
        // //$this->db->or_where('user_shift_timings.updated_by','1');	
		// 	}			
		// 	//}
        //     //else{
        //         $this->db->or_where('tbl_shift.updated_by','1');
        //    // }
        // //$this->db->order_by('id', 'desc');
        
		// $query = $this->db->get();
         //$tbl_shift_updated_by = 1;
         $user_shift_updated_by = $userid;
         $this->db->select('
         tbl_shift.id AS tbl_shift_id, 
         tbl_shift.*, 
         user_shift_timings.id AS user_shift_timing_id, 
         user_shift_timings.*, 
         tbl_shift.open_date AS tbl_shift_open_date, 
         user_shift_timings.open_date AS user_shift_open_date
     ');
     $this->db->from('tbl_shift');
     $this->db->join('user_shift_timings', 'tbl_shift.id = user_shift_timings.shift_id AND user_shift_timings.updated_by IN (1, '.$user_shift_updated_by.')', 'left');
     $this->db->group_start();
     $this->db->where('tbl_shift.updated_by', $userid);
     //$this->db->or_where_in('user_shift_timings.updated_by', [1, $user_shift_updated_by]);
     $this->db->group_end();
     $this->db->group_by('tbl_shift.id');
        $query = $this->db->get();
        // echo $this->db->last_query(); die;

        // $this->db->select('tbl_shift.id AS tbl_shift_id, tbl_shift.*, user_shift_timings.id AS user_shift_timing_id, user_shift_timings.*')
        //  ->from('tbl_shift')
        //  ->join('user_shift_timings', 'tbl_shift.id = user_shift_timings.shift_id', 'left')
        //  ->where('user_shift_timings.updated_by', $user_shift_updated_by)
        //  ->group_start() // Start grouping for complex OR condition
        //  ->where('user_shift_timings.shift_id IS NOT NULL')
        //  ->or_where('tbl_shift.id NOT IN (SELECT shift_id FROM user_shift_timings)', NULL, FALSE)
        //  ->group_end() // End grouping
        //  ->group_by('tbl_shift.id');

        // $query = $this->db->get();
        //echo $this->db->last_query(); die;
        $result = $query->result_array();
            return $result;
    } 
    /*
     * Get all tbl_shift
     */
    function get_all_tbl_shift($params = array())
    { //print_r($this->session->userdata['userid']); die;
		 $this->db->select('tbl_shift.*,tbl_ledger.ledger_name');
		$this->db->from('tbl_shift');
		$this->db->join('tbl_ledger', 'tbl_ledger.id = tbl_shift.updated_by','left');
			if(isset($this->session->userdata['userid']) && $this->session->userdata['userid'] != '1'){
			if(!empty($params)){
		$this->db->where('tbl_shift.updated_by',$params);
        $this->db->or_where('tbl_shift.updated_by','1');	
			}			
			}
            else{
                $this->db->where('tbl_shift.updated_by','1');
            }
				if(isset($_SESSION['role'])&&$_SESSION['role']=='Staff'){
                    $this->db->or_where('tbl_shift.updated_by','1');
                }
                $this->db->where('tbl_shift.is_active','1');
        //$this->db->order_by('id', 'desc');
        
		$query = $this->db->get();
        //echo $this->db->last_query(); die;
        return $query->result_array();
    }
    public function toggle_status($id) {
        // Fetch current status
        $this->db->select('tbl_shift.id,user_shift_timings.is_active');
        $this->db->from('tbl_shift');
        $this->db->join('user_shift_timings', 'user_shift_timings.shift_id = tbl_shift.id');
        $this->db->where('user_shift_timings.id', $id);
        $query = $this->db->get();
        
        //echo '<pre>'; print_r($query->row()); echo '</pre>'; die;
        $current_status = $query->row()->is_active;

        // Toggle the status
        $new_status = ($current_status == 1) ? 0 : 1;

        // Update the status in the database
        $this->db->where('id', $id);
        $this->db->update('user_shift_timings', array('is_active' => $new_status));
    }

    function get_all_tbl_shift_app($userid)
    { 
        $query = $this->db->query("SELECT `tbl_master_transaction`.`id`,  `tbl_agent`.`agent_name`, `tbl_trans_numbers`.`created_date` as `createddate`, `tbl_trans_numbers`.`modified_date` as `modifieddate`, `tbl_master_transaction`.`t_date`, `tbl_master_transaction`.`total_number_amount`, `tbl_master_transaction`.`created_date`, `tbl_master_transaction`.`party_id`, `tbl_shift`.id as shiftid,`user_shift_timings`.id as ushiftid,`user_shift_timings`.app_time,`tbl_shift`.`shift_name` as `shift_name`, `user_shift_timings`.`open_date`, `tbl_shift`.`super_admin`, `tbl_shift`.`data_entry_operator`, `tbl_shift`.`id` as `shift_id`, `tbl_ledger`.`ledger_name`, `tbl_trans_numbers`.`number` as `trnno`, `tbl_trans_numbers`.`amount` as `trn_amt` FROM `tbl_master_transaction` JOIN `user_shift_timings` ON `user_shift_timings`.`id` = `tbl_master_transaction`.`shift_id` JOIN `tbl_shift` ON `tbl_shift`.`id` = `user_shift_timings`.`shift_id` JOIN `tbl_trans_numbers` ON `tbl_trans_numbers`.`master_id` = `tbl_master_transaction`.`id` JOIN `tbl_ledger` ON `tbl_ledger`.`id` = `tbl_master_transaction`.`party_id` LEFT JOIN `tbl_agent` ON `tbl_ledger`.`agent_id` = `tbl_agent`.`id`  
				WHERE `tbl_master_transaction`.`t_date` >= NOW() - INTERVAL 30 DAY AND `tbl_master_transaction`.`created_by` = '".$userid."' ORDER BY `tbl_master_transaction`.`id` DESC");
        return $query->result_array();
    }
        /*
     * Get all tbl_shift
     */
    function get_all_tbl_shift_admin($params = array())
    { //print_r($params); die;
	$admin_id = $this->session->userdata['id'];
		 $this->db->select('tbl_shift.*,user_shift_timings.id as shift_id');
		$this->db->from('tbl_shift');
		$this->db->join('user_shift_timings', 'user_shift_timings.shift_id = tbl_shift.id');
			//if(!empty($params)){
		$this->db->where('tbl_shift.updated_by',$admin_id);	
        $this->db->where('user_shift_timings.updated_by',$admin_id);	
			//}
			//$this->db->where('tbl_ledger.id',$admin_id);
        //$this->db->order_by('id', 'desc');
        //if($admin_id != 1){
			//$this->db->where('tbl_shift.updated_by','1');
		//}
		$query = $this->db->get();
		//echo $this->db->last_query(); die;
        return $query->result_array();
    }
    
    function get_master_jantri_temp($pid,$date){
        $master_id = $this->session->userdata['id'];
        $this->db->select('user_shift_timings.*, tbl_shift.super_admin as mastertime');
        $this->db->from('user_shift_timings');
        $this->db->join('tbl_shift', 'tbl_shift.id = user_shift_timings.shift_id');
        $this->db->where('user_shift_timings.updated_by', $master_id);
        $this->db->where('user_shift_timings.id', $pid);
        
        // Grouping the two date conditions
        $this->db->group_start();
        $this->db->where('user_shift_timings.open_date', date('Y-m-d', strtotime($date)));
        $this->db->or_where('user_shift_timings.open_date', date('Y-m-d', strtotime($date . ' +24 hours')));
        $this->db->group_end();
        

       // $this->db->select('user_shift_timings.*');
       // $this->db->from('user_shift_timings');
       
       // $this->db->where('user_shift_timings.updated_by',$this->session->userdata['userid']);	
       // $this->db->where('user_shift_timings.id',$pid);	
       // $this->db->where('user_shift_timings.open_date',date('Y-m-d',strtotime($date)));		
        $query = $this->db->get();
       // echo $this->db->last_query(); die;
       return $query->row();
   }

    function get_master_jantri($pid,$date){
		 $this->db->select('tbl_shift.*');
		$this->db->from('tbl_shift');
		//$this->db->join('tbl_ledger', 'tbl_ledger.id = tbl_shift.updated_by');
			//if(!empty($params)){
		$this->db->where('tbl_shift.updated_by',1);	
		$this->db->where('tbl_shift.id',$pid);	
       //update to test if master update the shift time is working for his own submission.
       // $this->db->where('tbl_shift.open_date',date('Y-m-d',strtotime($date)));	
        // $this->db->select('user_shift_timings.*');
		// $this->db->from('user_shift_timings');
		
		// $this->db->where('user_shift_timings.updated_by',$this->session->userdata['userid']);	
		// $this->db->where('user_shift_timings.id',$pid);	
        // $this->db->where('user_shift_timings.open_date',date('Y-m-d',strtotime($date)));		
		 $query = $this->db->get();
        // echo $this->db->last_query(); die;
        return $query->row();
    }
    /*
     * function to add new tbl_shift
     */
    function add_tbl_shift($params)
    {
        $this->db->insert('tbl_shift',$params);
        return $this->db->insert_id();
    }
 /*
     * function to add new tbl_shift
     */
    function insert_tbl_shift_timing($params)
    {
        $this->db->insert('user_shift_timings',$params);
        return $this->db->insert_id();
    }
    /*function to add tbl user shift*/
    function add_tbl_shift_time($shift_id,$params)
    { 
        $param['master_id'] = $params['updated_by'];
        $param['shift_id'] = $shift_id;
        $param['start_time'] = date("H:i:s", strtotime($params['master']));
        $param['app_time'] = date("H:i:s", strtotime($params['app_time']));
        $param['data_entry_operator'] = date("H:i:s", strtotime($params['data_entry_operator']));
        $this->db->insert('user_shift_timings',$param);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_shift
     */
    function update_tbl_shift($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_shift',$params);
    }

    /*
     * function to update tbl_shift
     */
    function update_tbl_shift_timing($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('user_shift_timings',$params);
    }

    /*
     * function to update tbl_shift
     */
    function update_tbl_shift_timing_by_shiftid($id,$params)
    {
       $this->db->where('id',$id);
        //print_r($params); die; 
        return $this->db->update('user_shift_timings',$params);
         //echo $this->db->last_query(); die; 
    }
    
    /*
     * function to delete tbl_shift
     */
    function delete_tbl_shift($id)
    {
        return $this->db->delete('tbl_shift',array('id'=>$id));
    }
	
	/*Function to check duplicate entry*/
	function checkDuplicate($val,$id)
    {
        return $this->db->get_where('tbl_shift',array('shift_name'=>strtolower(trim($val))))->num_rows();
    }

    public function get_access_time($user_id) {
        $this->db->select('access_times.*');
        $this->db->from('users');
        $this->db->join('admins as sub_admin', 'users.sub_admin_id = sub_admin.id', 'left');
        $this->db->join('access_times', 'access_times.admin_id = COALESCE(sub_admin.id, (SELECT id FROM admins WHERE role = "super_admin" LIMIT 1))', 'left');
        $this->db->where('users.id', $user_id);
        $query = $this->db->get();
        return $query->row();
    }

    public function get_master_shifts(){
        $this->db->from('tbl_shift');
		//$this->db->join('tbl_ as sub_admin', 'users.sub_admin_id = sub_admin.id', 'left');
        $this->db->order_by('orderby', 'asc');
        $this->db->where('updated_by', '1');
        $this->db->or_where('updated_by', $this->session->userdata['userid']);
        $this->db->where('is_active', '1');
        $this->db->where('open_date >=', date('Y-m-d'));
        $query = $this->db->get();
        return $query->row();
    }
    public function get_ledger_shifts($id){
        $this->db->select('user_shift_timings.*,tbl_shift.shift_name');
        $this->db->from('user_shift_timings');
        $this->db->join('tbl_shift', 'user_shift_timings.shift_id = tbl_shift.id', 'left');
		$this->db->order_by('user_shift_timings.id', 'asc');
        $this->db->where('user_shift_timings.master_id', '1');
        $this->db->or_where('user_shift_timings.master_id', $id);
        $this->db->where('tbl_shift.is_active', '1');
        $this->db->where('tbl_shift.open_date >=', date('Y-m-d'));
        $query = $this->db->get();
        return $query->result_array();
    }
    public function delete_shift_with_timing($usershift_timing_id) {
        // Get the shift ID from user_shift_timings table
        $this->db->select('shift_id');
        $this->db->from('user_shift_timings');
        $this->db->where('id', $usershift_timing_id);
        $query = $this->db->get();
        $result = $query->row();

        if ($result) {
            $shift_id = $result->shift_id;

            // Begin transaction to ensure both deletions succeed or fail together
            $this->db->trans_begin();

            // Delete from user_shift_timings table
            $this->db->where('id', $usershift_timing_id);
            $this->db->delete('user_shift_timings');

            // Delete the related record in tbl_shift using the shift ID
            $this->db->where('id', $shift_id);
            $this->db->delete('tbl_shift');

            // Check for successful completion of both queries
            if ($this->db->trans_status() === FALSE) {
                // Rollback if there’s an issue
                $this->db->trans_rollback();
                return false;
            } else {
                // Commit if successful
                $this->db->trans_commit();
                return true;
            }
        } else {
            // If no record is found, return false
            return false;
        }
    }
}
