<?php

/* 

 * Generated by CRUDigniter v3.2 

 * www.crudigniter.com

 */



class Tbl_ledger_model extends CI_Model

{

    function __construct()

    {

        parent::__construct();
    }



    /* 

     * Get tbl_ledger by id

     */

    function get_tbl_ledger($id)

    {

        return $this->db->get_where('tbl_ledger', array('id' => $id, 'status' => 1))->row_array();
    }


     /**
     * Get all active ledgers (for dropdown)
     */
    public function get_all_ledgers() {
        return $this->db->where('status', 1)
                        ->order_by('ledger_name', 'ASC')
                        ->get('tbl_ledger')
                        ->result_array();
    }

    /**
     * Get master commission for a ledger between two dates
     */
    public function get_master_commission_reportoldd($ledger_id, $start_date, $end_date) {
        $start_datetime = date('Y-m-d 12:00:00', strtotime($start_date));
        $end_datetime   = date('Y-m-d 06:00:00', strtotime($end_date . ' +1 day'));

        $sql = "
            SELECT 
                DATE(mt.t_date) AS report_date,
                SUM(mt.total_number_amount) AS total_number_amount,
                SUM(mt.total_akhar_amount) AS total_akhar_amount,
                l.dara__master_commision,
                l.akhar__master_commision,
                (
                    (SUM(mt.total_number_amount) * (CAST(l.dara__master_commision AS DECIMAL(10,2)) / 100)) +
                    (SUM(mt.total_akhar_amount) * (CAST(l.akhar__master_commision AS DECIMAL(10,2)) / 100))
                ) AS master_commission
            FROM tbl_master_transaction mt
            INNER JOIN tbl_ledger l ON mt.party_id = l.id
            WHERE mt.party_id = ?
              AND mt.t_date BETWEEN ? AND ?
            GROUP BY report_date
            ORDER BY report_date ASC
        ";
//   // 👇 Build final query string manually for debugging
//     $final_query = $this->db->compile_binds($sql, [$ledger_id, $start_datetime, $end_datetime]);

//     echo "<pre>$final_query</pre>"; // Debug print
//     die;
        return $this->db->query($sql, [$ledger_id, $start_datetime, $end_datetime])->result_array();
    }
public function get_master_commission_report($ledger_id, $start_date, $end_date)
{
    $start_datetime = date('Y-m-d 06:00:00', strtotime($start_date));
    $end_datetime   = date('Y-m-d 06:00:00', strtotime($end_date . ' +1 day'));

    $sql = "
        SELECT 
            DATE(DATE_SUB(mt.t_date, INTERVAL 6 HOUR)) AS report_date,
            SUM(mt.total_number_amount) AS total_number_amount,
            SUM(mt.total_akhar_amount) AS total_akhar_amount,
            l.dara__master_commision,
            l.akhar__master_commision,
            (
                (SUM(mt.total_number_amount) * (CAST(l.dara__master_commision AS DECIMAL(10,2)) / 100)) +
                (SUM(mt.total_akhar_amount) * (CAST(l.akhar__master_commision AS DECIMAL(10,2)) / 100))
            ) AS master_commission
        FROM tbl_master_transaction mt
        INNER JOIN tbl_ledger l ON mt.party_id = l.id
        WHERE mt.party_id = ?
          AND mt.t_date >= ?
          AND mt.t_date < ?
        GROUP BY DATE(DATE_SUB(mt.t_date, INTERVAL 6 HOUR))
        ORDER BY DATE(DATE_SUB(mt.t_date, INTERVAL 6 HOUR)) ASC
    ";

    return $this->db->query($sql, [$ledger_id, $start_datetime, $end_datetime])->result_array();
}
    /* 

     * Get tbl_ledger by id

     */

    function get_tbl_ledger_byupdatedbyforparty($id)

    {

        return $this->db->get_where('tbl_ledger', array('status' => 1, 'updated_by' => $id))->result();
    }

    //  public function getledgercreditdebit()
    // {
    //    $admin_id = $this->session->userdata['id'];

    // // Subquery: Latest transaction date from tbl_master_transaction
    // $sub_transaction = "(SELECT party_id, MAX(t_date) AS latest_transaction_date 
    //                      FROM tbl_master_transaction 
    //                      GROUP BY party_id) AS mt";

    // // Subquery: Latest credit record per party_id
    // $sub_credit = "(SELECT c1.*
    //                 FROM tbl_credit c1
    //                 INNER JOIN (
    //                     SELECT party_id, MAX(id) AS max_id
    //                     FROM tbl_credit
    //                     GROUP BY party_id
    //                 ) c2 ON c1.party_id = c2.party_id AND c1.id = c2.max_id
    //               ) AS cr";

    // // Subquery: Latest final_hisab record per ledger_id
    // $sub_hisab = "(SELECT h1.*
    //                FROM tbl_final_hisab h1
    //                INNER JOIN (
    //                    SELECT ledger_id, MAX(id) AS max_id
    //                    FROM tbl_final_hisab
    //                    GROUP BY ledger_id
    //                ) h2 ON h1.ledger_id = h2.ledger_id AND h1.id = h2.max_id
    //               ) AS h";

    // $this->db->select("
    //     l.id AS ledger_id,
    //     l.ledger_name,
    //     l.openingbalance,
    //     IFNULL(cr.credit_balance, 0) AS credit_balance,
    //     IFNULL(h.final_hisab, 0) AS final_hisab,
    //     (IFNULL(cr.credit_balance, 0) - IFNULL(h.final_hisab, 0)) AS totalbalance,
    //     IFNULL(mt.latest_transaction_date, NULL) AS last_transaction_date
    // ");

    // $this->db->from('tbl_ledger l');
    // $this->db->join($sub_credit, 'l.id = cr.party_id', 'left');
    // $this->db->join($sub_transaction, 'l.id = mt.party_id', 'left');
    // $this->db->join($sub_hisab, 'l.id = h.ledger_id', 'left');

    // $this->db->where('l.updated_by', $admin_id);
    // $this->db->group_by('l.id');
    // $this->db->order_by('l.ledger_name', 'ASC');

    // $query = $this->db->get();
    // $result = $query->result_array();
    //     return $result;
    // }

    // public function getledgercreditdebit()
    // {
    //     $admin_id = $this->session->userdata('id');
    //     $firstDayOfMonth = date('Y-m-01');

    //     // Subquery: Latest transaction date from tbl_master_transaction
    //     $sub_transaction = "(SELECT party_id, MAX(t_date) AS latest_transaction_date 
    //                          FROM tbl_master_transaction 
    //                          GROUP BY party_id) AS mt";

    //     // Subquery: Latest credit record per party_id
    //     $sub_credit = "(SELECT c1.*
    //                     FROM tbl_credit c1
    //                     INNER JOIN (
    //                         SELECT party_id, MAX(id) AS max_id
    //                         FROM tbl_credit
    //                         GROUP BY party_id
    //                     ) c2 ON c1.party_id = c2.party_id AND c1.id = c2.max_id
    //                   ) AS cr";

    //     // Subquery: Latest final_hisab record per ledger_id
    //     $sub_hisab = "(SELECT h1.*
    //                    FROM tbl_final_hisab h1
    //                    INNER JOIN (
    //                        SELECT ledger_id, MAX(id) AS max_id
    //                        FROM tbl_final_hisab
    //                        GROUP BY ledger_id 
    //                    ) h2 ON h1.ledger_id = h2.ledger_id AND h1.id = h2.max_id
    //                   ) AS h";

    //     // Subquery: Net voucher calculation per ledger from 1st of this month
    //     $sub_voucher = "(SELECT 
    //                         ledger_id,
    //                         SUM(voucher_amount) AS voucher_total
    //                     FROM (
    //                         SELECT 
    //                             PartyId AS ledger_id,
    //                             Amount AS voucher_amount
    //                         FROM tbl_voucher
    //                         WHERE Date >= '{$firstDayOfMonth}'

    //                         UNION ALL

    //                         SELECT 
    //                             Collect_By AS ledger_id,
    //                             -Amount AS voucher_amount
    //                         FROM tbl_voucher
    //                         WHERE Date >= '{$firstDayOfMonth}'
    //                     ) AS combined
    //                     GROUP BY ledger_id
    //                    ) AS v";

    //     $this->db->select("
    //         l.id AS ledger_id,
    //         l.ledger_name,
    //         l.openingbalance,
    //         IFNULL(cr.credit_balance, 0) AS credit_balance,
    //         IFNULL(h.final_hisab, 0) AS final_hisab,
    //         IFNULL(h.today_hisab, 0) AS today_hisab,
    //         (IFNULL(cr.credit_balance, 0) - IFNULL(h.final_hisab, 0)) AS totalbalance,
    //         IFNULL(mt.latest_transaction_date, NULL) AS last_transaction_date,
    //         IFNULL(v.voucher_total, 0) AS net_voucher_amount
    //     ");

    //     $this->db->from('tbl_ledger l');
    //     $this->db->join($sub_credit, 'l.id = cr.party_id', 'left');
    //     $this->db->join($sub_transaction, 'l.id = mt.party_id', 'left');
    //     $this->db->join($sub_hisab, 'l.id = h.ledger_id', 'left');
    //     $this->db->join($sub_voucher, 'l.id = v.ledger_id', 'left'); // ✅ new join

    //     $this->db->where('l.updated_by', $admin_id);
    //     $this->db->group_by('l.id');
    //     $this->db->order_by('l.ledger_name', 'ASC');

    //     $query = $this->db->get();
    //     return $query->result_array();
    // }
    // public function getledgercreditdebit_with_coin_balance()
    // {
    //     $admin_id = $this->session->userdata('id');

    //     // Subquery: Latest transaction date from tbl_master_transaction
    //     $sub_transaction = "(SELECT party_id, MAX(t_date) AS latest_transaction_date 
    //                          FROM tbl_master_transaction 
    //                          GROUP BY party_id) AS mt";

    //     // Subquery: Latest credit record per party_id
    //     $sub_credit = "(SELECT c1.*
    //                     FROM tbl_credit c1
    //                     INNER JOIN (
    //                         SELECT party_id, MAX(id) AS max_id
    //                         FROM tbl_credit
    //                         GROUP BY party_id
    //                     ) c2 ON c1.party_id = c2.party_id AND c1.id = c2.max_id
    //                   ) AS cr";

    //     // Subquery: Latest final_hisab record per ledger_id
    //     $sub_hisab = "(SELECT h1.*
    //                    FROM tbl_final_hisab h1
    //                    INNER JOIN (
    //                        SELECT ledger_id, MAX(id) AS max_id
    //                        FROM tbl_final_hisab
    //                        GROUP BY ledger_id 
    //                    ) h2 ON h1.ledger_id = h2.ledger_id AND h1.id = h2.max_id
    //                   ) AS h";

    //     $this->db->select("
    //         l.id AS ledger_id,
    //         l.ledger_name,
    //         l.openingbalance,
    //         IFNULL(cr.credit_balance, 0) AS credit_balance,
    //         IFNULL(h.final_hisab, 0) AS final_hisab,
    //         IFNULL(h.today_hisab, 0) AS today_hisab,
    //         (IFNULL(cr.credit_balance, 0) - IFNULL(h.final_hisab, 0)) AS totalbalance,
    //         IFNULL(mt.latest_transaction_date, NULL) AS last_transaction_date
    //     ");

    //     $this->db->from('tbl_ledger l');
    //     $this->db->join($sub_credit, 'l.id = cr.party_id', 'left');
    //     $this->db->join($sub_transaction, 'l.id = mt.party_id', 'left');
    //     $this->db->join($sub_hisab, 'l.id = h.ledger_id', 'left');

    //     $this->db->where('l.updated_by', $admin_id);
    //     $this->db->group_by('l.id');
    //     $this->db->order_by('l.ledger_name', 'ASC');

    //     $query = $this->db->get();
    //     $results = $query->result_array();

    //     // Append coin_balance using the external get_coin_balance() logic
    //     foreach ($results as &$row) {
    //         $row['coin_balance'] = $this->get_coin_balance($row['ledger_id']);
    //     }

    //     return $results;
    // }

    public function getledgercreditdebit_with_coin_balance()
{
    $admin_id = $this->session->userdata('id');

    /*
     * Same date range as get_final_balance()
     */
    $start_date = '2025-08-01';
    $end_date   = date('Y-m-d');

    $start_datetime = date('Y-m-d H:i:s', strtotime($start_date . ' 12:00:00'));
    $end_datetime   = date('Y-m-d H:i:s', strtotime($end_date . ' +1 day 06:00:00'));

    $hisab_start_date = date('Y-m-d', strtotime($start_datetime));
    $hisab_end_date   = date('Y-m-d', strtotime($end_datetime));

    /*
     * Latest transaction date per ledger
     */
    $sub_transaction = "(
        SELECT 
            party_id, 
            MAX(t_date) AS latest_transaction_date 
        FROM tbl_master_transaction 
        GROUP BY party_id
    ) AS mt";

    /*
     * Latest credit balance per ledger
     */
    $sub_credit = "(
        SELECT 
            c1.party_id, 
            c1.credit_balance
        FROM tbl_credit c1
        INNER JOIN (
            SELECT 
                party_id, 
                MAX(id) AS max_id
            FROM tbl_credit
            GROUP BY party_id
        ) c2 ON c1.party_id = c2.party_id 
            AND c1.id = c2.max_id
    ) AS cr";

    /*
     * Latest hisab row per ledger
     */
    $sub_hisab = "(
        SELECT 
            h1.ledger_id, 
            h1.final_hisab, 
            h1.today_hisab
        FROM tbl_final_hisab h1
        INNER JOIN (
            SELECT 
                ledger_id, 
                MAX(id) AS max_id
            FROM tbl_final_hisab
            GROUP BY ledger_id
        ) h2 ON h1.ledger_id = h2.ledger_id 
            AND h1.id = h2.max_id
    ) AS h";

    /*
     * Main ledger query
     */
    $this->db->select("
        l.id AS ledger_id,
        l.ledger_name,
         l.username,
        l.password,
        l.openingbalance,
        IFNULL(cr.credit_balance, 0) AS credit_balance,
        IFNULL(h.final_hisab, 0) AS final_hisab,
        IFNULL(h.today_hisab, 0) AS today_hisab,
        mt.latest_transaction_date AS last_transaction_date
    ", false);

    $this->db->from('tbl_ledger l');
    $this->db->join($sub_credit, 'l.id = cr.party_id', 'left');
    $this->db->join($sub_transaction, 'l.id = mt.party_id', 'left');
    $this->db->join($sub_hisab, 'l.id = h.ledger_id', 'left');

    $this->db->where('l.updated_by', $admin_id);

    /*
     * Old function did not filter status.
     * Keep this commented if you want exact old output.
     * Uncomment only if inactive ledgers should be excluded.
     */
    // $this->db->where('l.status', 1);

    $this->db->group_by('l.id');
    $this->db->order_by('l.ledger_name', 'ASC');

    $results = $this->db->get()->result_array();

    $ledger_ids = array_column($results, 'ledger_id');

    if (empty($ledger_ids)) {
        return [];
    }

    /*
     * 1. Coins received
     *
     * Exact get_final_balance() rule:
     * If receiver_id == ledger_id, add amount.
     * No status filter is used for received coins in helper.
     */
    $this->db->select('receiver_id AS ledger_id, COALESCE(SUM(amount), 0) AS received_amount', false);
    $this->db->from('coin_transactions');
    $this->db->where_in('receiver_id', $ledger_ids);
    $this->db->where('created_at >=', $start_datetime);
    $this->db->where('created_at <', $end_datetime);
    $this->db->group_by('receiver_id');

    $received_rows = $this->db->get()->result_array();
    $received_map = array_column($received_rows, 'received_amount', 'ledger_id');

    /*
     * 2. Coins sent / spent
     *
     * Exact get_final_balance() rule:
     * sender_id == ledger_id
     * type = spend
     * status = 1
     */
    $this->db->select('sender_id AS ledger_id, COALESCE(SUM(amount), 0) AS sent_amount', false);
    $this->db->from('coin_transactions');
    $this->db->where_in('sender_id', $ledger_ids);
    $this->db->where('type', 'spend');
    $this->db->where('status', 1);
    $this->db->where('created_at >=', $start_datetime);
    $this->db->where('created_at <', $end_datetime);
    $this->db->group_by('sender_id');

    $sent_rows = $this->db->get()->result_array();
    $sent_map = array_column($sent_rows, 'sent_amount', 'ledger_id');

    /*
     * 3. P/L from tbl_final_hisab
     *
     * Helper logic:
     *
     * if today_hisab < 0:
     *     balance += abs(today_hisab)
     * else:
     *     balance -= today_hisab
     *
     * This is mathematically same as:
     * balance -= today_hisab
     *
     * Example:
     * today_hisab = 100  => balance - 100
     * today_hisab = -100 => balance - (-100) = balance + 100
     */
    $this->db->select('ledger_id, COALESCE(SUM(today_hisab), 0) AS hisab_amount', false);
    $this->db->from('tbl_final_hisab');
    $this->db->where_in('ledger_id', $ledger_ids);
    $this->db->where("STR_TO_DATE(`date`, '%d-%m-%Y') >=", $hisab_start_date);
    $this->db->where("STR_TO_DATE(`date`, '%d-%m-%Y') <", $hisab_end_date);
    $this->db->group_by('ledger_id');

    $hisab_rows = $this->db->get()->result_array();
    $hisab_map = array_column($hisab_rows, 'hisab_amount', 'ledger_id');

    /*
     * 4. Final balance
     *
     * Same as get_final_balance():
     * balance = received - sent - today_hisab
     */
    foreach ($results as &$row) {
        $ledger_id = $row['ledger_id'];

        $received_amount = isset($received_map[$ledger_id]) ? (float) $received_map[$ledger_id] : 0;
        $sent_amount     = isset($sent_map[$ledger_id]) ? (float) $sent_map[$ledger_id] : 0;
        $hisab_amount    = isset($hisab_map[$ledger_id]) ? (float) $hisab_map[$ledger_id] : 0;

        $row['coin_balance'] = $received_amount - $sent_amount - $hisab_amount;
    }

    unset($row);

    return $results;
}
    public function getledgercreditdebit_with_coin_balanceold()
    {
        $admin_id = $this->session->userdata('id');

        // Subqueries (same as before)
        $sub_transaction = "(SELECT party_id, MAX(t_date) AS latest_transaction_date 
                         FROM tbl_master_transaction 
                         GROUP BY party_id) AS mt";

        $sub_credit = "(SELECT c1.*
                    FROM tbl_credit c1
                    INNER JOIN (
                        SELECT party_id, MAX(id) AS max_id
                        FROM tbl_credit
                        GROUP BY party_id
                    ) c2 ON c1.party_id = c2.party_id AND c1.id = c2.max_id
                  ) AS cr";

        $sub_hisab = "(SELECT h1.*
                   FROM tbl_final_hisab h1
                   INNER JOIN (
                       SELECT ledger_id, MAX(id) AS max_id
                       FROM tbl_final_hisab
                       GROUP BY ledger_id 
                   ) h2 ON h1.ledger_id = h2.ledger_id AND h1.id = h2.max_id
                  ) AS h";

        // Main Ledger Query
        $this->db->select("
        l.id AS ledger_id,
        l.ledger_name,
        l.openingbalance,
        IFNULL(cr.credit_balance, 0) AS credit_balance,
        IFNULL(h.final_hisab, 0) AS final_hisab,
        IFNULL(h.today_hisab, 0) AS today_hisab,
       
        IFNULL(mt.latest_transaction_date, NULL) AS last_transaction_date
    ");

        $this->db->from('tbl_ledger l');
        $this->db->join($sub_credit, 'l.id = cr.party_id', 'left');
        $this->db->join($sub_transaction, 'l.id = mt.party_id', 'left');
        $this->db->join($sub_hisab, 'l.id = h.ledger_id', 'left');
        $this->db->where('l.updated_by', $admin_id);
        $this->db->group_by('l.id');
        $this->db->order_by('l.ledger_name', 'ASC');

        $query = $this->db->get();
        $results = $query->result_array();

        // Prepare ledger IDs
        $ledger_ids = array_column($results, 'ledger_id');
        if (empty($ledger_ids)) {
            return [];
        }

        // 1. Used coins this month from tbl_final_hisab
        $this->db->select('ledger_id, SUM(today_hisab) as used_amount');
        $this->db->from('tbl_final_hisab');
        $this->db->where_in('ledger_id', $ledger_ids);
        $this->db->where("STR_TO_DATE(date, '%d-%m-%Y') BETWEEN DATE_FORMAT(CURDATE(), '%Y-%m-01') AND LAST_DAY(CURDATE())", null, false);
        $this->db->group_by('ledger_id');
        $used = $this->db->get()->result_array();
        $used_map = array_column($used, 'used_amount', 'ledger_id');

        // 2. Coins received
        $this->db->select('receiver_id, SUM(amount) as received');
        $this->db->from('coin_transactions');
        $this->db->where_in('receiver_id', $ledger_ids);
        $this->db->group_by('receiver_id');
        $received = $this->db->get()->result_array();
        $received_map = array_column($received, 'received', 'receiver_id');

        // 3. Coins sent today after 6:00 AM
        $this->db->select('sender_id, SUM(amount) as sent');
        $this->db->from('coin_transactions');
        $this->db->where_in('sender_id', $ledger_ids);
        $this->db->where('status', 1);
        $this->db->where("created_at >= CONCAT(CURDATE(), ' 06:00:00')", null, false);
        $this->db->group_by('sender_id');
        $sent = $this->db->get()->result_array();
        $sent_map = array_column($sent, 'sent', 'sender_id');
        $this->load->helper('comman');
        // Final map assignment
        foreach ($results as &$row) {
            // $id = $row['ledger_id'];
            // $coin_received = isset($received_map[$id]) ? (float) $received_map[$id] : 0;
            // $coin_sent     = isset($sent_map[$id]) ? (float) $sent_map[$id] : 0;
            // $coin_used     = isset($used_map[$id]) ? (float) $used_map[$id] : 0;
            // if($id==409){
            // //echo $coin_received .' '. $coin_sent .' '. $coin_used.'<br>'; 
            // }
            // $row['coin_balance'] = $coin_received - $coin_sent - $coin_used;
            $ledger_id = $row['ledger_id'];
            $start_date = '2025-08-01'; // First of current month
            $end_date = date('Y-m-d');    // Today

            $row['coin_balance'] = get_final_balance($this, $ledger_id, $start_date, $end_date);
        }

        return $results;
    }



    // public function get_coin_balance($login_id)
    // {
    //     // 1. Coins used this month from tbl_final_hisab
    //     $sqlamt = "SELECT SUM(today_hisab) AS amount
    //                FROM tbl_final_hisab
    //                WHERE ledger_id = ?
    //                AND STR_TO_DATE(date, '%d-%m-%Y') BETWEEN DATE_FORMAT(CURDATE(), '%Y-%m-01') AND LAST_DAY(CURDATE())";
    //     $query = $this->db->query($sqlamt, array($login_id));
    //     $used_amount = 0;

    //     if ($query->num_rows() > 0) {
    //         $used_amount = (float) $query->row()->amount;
    //     }

    //     // 2. Total coins received
    //     $sql_received = "SELECT SUM(amount) AS coin_balance
    //                      FROM coin_transactions
    //                      WHERE receiver_id = ?";
    //     $coin_received_query = $this->db->query($sql_received, array($login_id));
    //     $coin_received = 0;

    //     if ($coin_received_query->num_rows() > 0) {
    //         $coin_received = (float) $coin_received_query->row()->coin_balance;
    //     }

    //     // 3. Total coins sent
    //     $sql_sent = "SELECT SUM(amount) AS coin_sent
    //                  FROM coin_transactions
    //                  WHERE sender_id = ?";
    //     $coin_sent_query = $this->db->query($sql_sent, array($login_id));
    //     $coin_sent = 0;

    //     if ($coin_sent_query->num_rows() > 0) {
    //         $coin_sent = (float) $coin_sent_query->row()->coin_sent;
    //     }

    //     // 4. Final balance = Received - Sent - Used
    //     if($login_id == '295'){
    //         echo $coin_received .' '. $coin_sent .' '. $used_amount; die;
    //     }
    //     return $coin_received - $coin_sent - $used_amount;
    // }


    public function get_coin_balance($login_id)
    {
        // 1. Total coins used this month from tbl_final_hisab
        $this->db->select('SUM(today_hisab) as amount');
        $this->db->from('tbl_final_hisab');
        $this->db->where('ledger_id', $login_id);
        $this->db->where("STR_TO_DATE(date, '%d-%m-%Y') BETWEEN DATE_FORMAT(CURDATE(), '%Y-%m-01') AND LAST_DAY(CURDATE())", null, false);
        $used_result = $this->db->get()->row();
        $used_amount = $used_result && $used_result->amount ? (float) $used_result->amount : 0;

        // 2. Total coins received
        $this->db->select('SUM(amount) as coin_balance');
        $this->db->from('coin_transactions');
        $this->db->where('receiver_id', $login_id);
        $received_result = $this->db->get()->row();
        $coin_received = $received_result && $received_result->coin_balance ? (float) $received_result->coin_balance : 0;

        // 3. Total coins sent after today 6:00 AM
        $this->db->select('SUM(amount) as amount');
        $this->db->from('coin_transactions');
        $this->db->where('sender_id', $login_id);
        $this->db->where('status', 1);
        $this->db->where("created_at >= CONCAT(CURDATE(), ' 06:00:00')", null, false);
        $sent_result = $this->db->get()->row();
        $coin_sent = $sent_result && $sent_result->amount ? (float) $sent_result->amount : 0;

        // Final coin balance = Received - Sent - Used
        return $coin_received - $coin_sent - $used_amount;
    }


    public function getLedgerTotalBalance($ledger_id)
    {
        // Get the latest credit record for this ledger
        $this->db->select('credit_balance');
        $this->db->from('tbl_credit');
        $this->db->where('party_id', $ledger_id);
        $this->db->order_by('id', 'desc');
        $this->db->limit(1);

        $creditQuery = $this->db->get();
        $creditResult = $creditQuery->row();

        $credit_balance = $creditResult ? $creditResult->credit_balance : 0;

        // Get the final hisab (profit/loss) for this ledger
        $this->db->select('final_hisab');
        $this->db->from('tbl_final_hisab');
        $this->db->where('ledger_id', $ledger_id);
        $hisabQuery = $this->db->get();
        $hisabResult = $hisabQuery->row();

        $final_hisab = $hisabResult ? $hisabResult->final_hisab : 0;

        // Calculate total balance
        $totalbalance = $credit_balance - $final_hisab;

        return $totalbalance;
    }


    public function getledgercreditdebitback()
    {
        $month_start = date('Y-m-01');
        $month_end = date('Y-m-t');
        $admin_id = $this->session->userdata['id'];

        $this->db->select("
        l.id as ledger_id,
        l.ledger_name AS account_name,
        ct.created_at AS transaction_date,
        CASE 
            WHEN ct.receiver_id = l.id THEN ct.amount 
            ELSE 0 
        END AS credit,
        CASE 
            WHEN ct.sender_id = l.id THEN ct.amount 
            ELSE 0 
        END AS withdraw,
        IFNULL(tc.credit_balance, 0) AS party_credit,
        (l.openingbalance + l.coin_balance) AS totalbalance
    ", false);

        $this->db->from('coin_transactions ct');
        $this->db->join('tbl_ledger l', 'l.id = ct.sender_id OR l.id = ct.receiver_id');
        $this->db->join('tbl_credit tc', 'tc.party_id = l.id', 'left'); // Left join to get credit or 0 if not found
        $this->db->where('l.updated_by', $admin_id);
        $this->db->where('ct.created_at >=', $month_start);
        $this->db->where('ct.created_at <=', $month_end);
        $this->db->order_by('ct.created_at', 'DESC');

        $query = $this->db->get();
        return json_encode($query->result_array());
    }


    /* 

     * Get tbl_ledger by id

     */

    function get_tbl_ledger_byupdatedbyformasters($id)

    {

        //return $this->db->get_where('tbl_ledger',array('status'=>1,'updated_by'=>$id))->result();

        $this->db->select('tbl_ledger.*, tbl_agent.agent_name');
        $this->db->from('tbl_ledger');
        $this->db->join('tbl_agent', 'tbl_ledger.agent_id = tbl_agent.id', 'left');
        $this->db->where('tbl_ledger.status', 1);
        $this->db->where('tbl_ledger.updated_by', $id);
        $query = $this->db->get();

// echo 'test<br>';
// echo $this->db->last_query();
// die;

return $query->result();
    }

    /*check for unique username*/
    public function username_exists($username)
    {
        $this->db->where('username', $username);
        $query = $this->db->get('tbl_ledger');

        return $query->num_rows() > 0;
    }

    /* 

     * Get tbl_ledger by id

     */

    function get_tbl_ledger_byupdatedby($id)

    {

        return $this->db->get_where('tbl_ledger', array('is_master' => '1', 'status' => 1))->result();
    }

    /* 

     * Get tbl_ledger admin

     */

    function get_all_admin()

    {

        return $this->db->get_where('tbl_ledger', array('is_master' => '1'))->result();
    }

    /* 

     * Get tbl_ledger by id

     */

    function get_tbl_ledger_delete($id)

    {

        return $this->db->get_where('tbl_ledger', array('id' => $id))->row_array();
    }



    /*Get agent wise ledger*/

    function get_tbl_ledger_agent($id)
    {

        // return $this->db->get_where('tbl_ledger',array('agent_id'=>$id,'status'=>1))->result_array();

        //echo '<pre>'; print_r($arr); die;



        $this->db->select('tbl_ledger.*,tbl_admin.admin_name');

        $this->db->from('tbl_ledger');

        $this->db->join('tbl_admin', 'tbl_admin.id = tbl_ledger.updated_by');

        //$this->db->get_where('tbl_ledger',array('agent_id'=>$id,'status'=>1));

        if ($id) {

            $this->db->where('tbl_ledger.agent_id', $id);
        }

        $this->db->where('tbl_ledger.status', '1');

        $this->db->order_by('id', 'desc');

        if (isset($params) && !empty($params)) {

            $this->db->limit($params['limit'], $params['offset']);
        }

        $query = $this->db->get();

        //echo $this->db->last_query(); die;

        return $query->result_array();
    }

    /* 

     * Get tbl_ledger by id

     */

    function get_tbl_ledger_inact($id)

    {

        return $this->db->get_where('tbl_ledger', array('id' => $id, 'status' => 0))->row_array();
    }



    function get_all_tbl_ledger_limit($params)
    {



        $this->db->select('tbl_ledger.*,tbl_admin.admin_name');

        $this->db->from('tbl_ledger');

        $this->db->join('tbl_admin', 'tbl_admin.id = tbl_ledger.updated_by');

        $this->db->where('tbl_ledger.status', '1');

        $this->db->order_by('id', 'desc');

        if (isset($params) && !empty($params)) {

            $this->db->limit($params['limit'], $params['offset']);
        }

        $query = $this->db->get();

        //echo $this->db->last_query(); die;

        return $query->result_array();
    }

    /*

     * Get all tbl_ledger

     */

    function get_all_tbl_ledger()

    {

        $this->db->select('tbl_ledger.*,tbl_admin.admin_name');

        $this->db->from('tbl_ledger');

        $this->db->join('tbl_admin', 'tbl_admin.id = tbl_ledger.updated_by');

        $this->db->where('tbl_ledger.status', '1');

        $this->db->order_by('id', 'desc');

        if (isset($params) && !empty($params)) {

            $this->db->limit($params['limit'], $params['offset']);
        }

        $query = $this->db->get();

        //echo $this->db->last_query(); die;

        return $query->result_array();
    }



    /*

     * Get all tbl_ledger_admin

     */

    function get_all_tbl_ledger_admin()

    {
        $admin_id = $this->session->userdata['id'];

        //echo '<pre>'; print_r($this->session->userdata); echo '</pre>'; die;

        $this->db->select('tbl_ledger.*,tbl_ledger.ledger_name');

        $this->db->from('tbl_ledger');

        $this->db->where('tbl_ledger.updated_by', $admin_id);

        $this->db->where('tbl_ledger.status', '1');



        $this->db->order_by('id', 'desc');

        if (isset($params) && !empty($params)) {

            $this->db->limit($params['limit'], $params['offset']);
        }

        $query = $this->db->get();

        return $query->result_array();
    }



    /*

     * Get all tbl_ledger_list

     */

    function get_all_tbl_ledger_list()

    {

        $this->db->select('tbl_ledger.*,tbl_admin.admin_name');

        $this->db->from('tbl_ledger');

        $this->db->join('tbl_admin', 'tbl_admin.id = tbl_ledger.updated_by');

        //$this->db->where('tbl_ledger.status','1');

        $this->db->order_by('id', 'desc');

        if (isset($params) && !empty($params)) {

            $this->db->limit($params['limit'], $params['offset']);
        }

        $query = $this->db->get();

        //echo $this->db->last_query(); die;

        return $query->result_array();
    }



    /*

     * function to add new tbl_ledger

     */

    function add_tbl_ledger($params)

    {

        $this->db->insert('tbl_ledger', $params);

        return $this->db->insert_id();
    }



    /*

     * function to add new tbl_final_ledger

     */

    function add_tbl_final_ledger($id)

    {

        $params['PartyId'] = $id;

        $this->db->insert('final_ledger', $params);

        return $this->db->insert_id();
    }



    /*

     * function to update tbl_ledger

     */

    function update_tbl_ledger($id, $params)

    {

        $this->db->where('id', $id);

        return $this->db->update('tbl_ledger', $params);
    }



    /*

     * function to delete tbl_ledger

     */

    function delete_tbl_ledger($id)

    {

        return $this->db->delete('tbl_ledger', array('id' => $id));
    }



    function get_all_tbl_master()
    {

        return $this->db->get_where('tbl_ledger', array('is_master' => '1'))->result_array();
    }



    function ledger_final_exist($party_id, $date)
    {

        return $this->db->get_where('tbl_final_ledger', array('PartyId' => $party_id, 'Date' => $date))->row_array();
    }
}
