<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_staff_model extends CI_Model
{
    function __construct()
    {
        parent::__construct(); 
    }
    
    /*
     * Get tbl_staff by id
     */
    function get_tbl_staff($id)
    {
        return $this->db->get_where('tbl_staff',array('id'=>$id))->row_array();
    }

    public function toggle_status($id) {
        // Fetch current status
        $this->db->select('is_active');
        $this->db->from('tbl_staff');
        $this->db->where('id', $id);
        $query = $this->db->get();
        $current_status = $query->row()->is_active;

        // Toggle the status
        $new_status = ($current_status == 1) ? 0 : 1;

        // Update the status in the database
        $this->db->where('id', $id);
        $this->db->update('tbl_staff', array('is_active' => $new_status));
    }
    function get_tbl_ledger_master($id)
    {
        //return $this->db->get_where('tbl_ledger',array('updated_by'=>$id))->result_array();
        $this->db->select('tbl_ledger.*'); 
		$this->db->from('tbl_ledger');		
		$this->db->where('tbl_ledger.updated_by', $id);
        //$this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
		$query = $this->db->get();
	//echo $this->db->last_query(); die;
        return $query->result_array();
    }
   
    function get_tbl_staff_master_view($id)
    {
        return $this->db->get_where('tbl_staff',array('updated_by'=>$id))->result_array();
    }
    function get_tbl_staff_master($id)
    {
        return $this->db->get_where('tbl_staff',array('updated_by'=>$id))->row_array();
    }
        
    /*
     * Get all tbl_staff 
     */
    function get_all_tbl_staff()
    {
		 $this->db->select('tbl_staff.*,tbl_ledger.ledger_name'); 
		$this->db->from('tbl_staff');
		$this->db->join('tbl_ledger', 'tbl_ledger.id = tbl_staff.updated_by');		
		$this->db->where('tbl_staff.updated_by', $this->session->userdata['id']);
        //$this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
		$query = $this->db->get();
		//echo $this->db->last_query(); die;
        return $query->result_array();
    }
        
    /*
     * function to add new tbl_staff
     */
    function add_tbl_staff($params)
    {
        $this->db->insert('tbl_staff',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_staff
     */
    function update_tbl_staff($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_staff',$params);
    }
    
    /*
     * function to delete tbl_staff
     */
    function delete_tbl_staff($id)
    {
        return $this->db->delete('tbl_staff',array('id'=>$id));
    }
	/*Function to check duplicate entry*/
	function checkDuplicate($val,$role)
    {
        return $this->db->get_where('tbl_staff',array('user_role'=>$role,'user_name'=>strtolower($val)))->num_rows();
    }
}
