<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Tbl_transactions_model extends CI_Model
{
	function __construct()
	{
		parent::__construct();
	}

	/*
	 * Get tbl_transactions by id
	 */
	function get_tbl_transactions($id)
	{
		return $this->db->get_where('tbl_master_transaction', array('id' => $id))->row_array();
	}

	/*
	 * Get tbl_transactions_master by id
	 */
	function get_party_entry($shift, $party, $date)
	{ //echo '<pre>'; print_r($arr); echo '</pre>'; die;
		/*$this->db->select('*');
			   $this->db->from('Tb_Date_shift_party_entry');
			   $this->db->where('ShiftId',$shift);
			   $this->db->where('PartyId',$party);
			   $this->db->where('Date',$date);
			   $query = $this->db->get();
			   return $query->result_array();*/
		//$array = ['name !=' => $name, 'id <' => $id, 'date >' => $date];
		//$builder->where($array);
		$multiarr = ['shift_id' => $shift, 'party_id' => $party, 't_date' => $date];
		//print_r($multiarr); die;
		$query = $this->db->get_where('tbl_master_transaction', $multiarr)->result_array();
		//	echo $this->db->last_query(); die;
		return $query;
		// echo $this->db->last_query(); die;
		// $builder = $this->db->get();
		//return $this->db->get_where('tbl_master_transactions',array('id'=>$id))->row_array();
	}

	/*
	 * Get tbl_transactions_master by id
	 */
	function get_Date_shift_party_entry($shift, $party, $date)
	{ //echo '<pre>'; print_r($arr); echo '</pre>'; die;
		/*$this->db->select('*');
			   $this->db->from('Tb_Date_shift_party_entry');
			   $this->db->where('ShiftId',$shift);
			   $this->db->where('PartyId',$party);
			   $this->db->where('Date',$date);
			   $query = $this->db->get();
			   return $query->result_array();*/
		//$array = ['name !=' => $name, 'id <' => $id, 'date >' => $date];
		//$builder->where($array);
		$multiarr = ['ShiftId' => $shift, 'PartyId' => $party, 'Date' => date('Y-m-d', strtotime($date))];
		//print_r($multiarr); die;
		$query = $this->db->get_where('Tb_Date_shift_party_entry', $multiarr)->result_array();

		return $query;
		// echo $this->db->last_query(); die;
		// $builder = $this->db->get();
		//return $this->db->get_where('tbl_master_transactions',array('id'=>$id))->row_array();
	}


	/*
	 * Get all tbl_transactions
	 */
	function get_all_tbl_transactions()
	{
		$this->db->select('tbl_transactions.*,tbl_user_login.user_name');
		$this->db->from('tbl_master_transactions');
		$this->db->join('tbl_user_login', 'tbl_user_login.id = tbl_transactions.updated_by');

		//$this->db->order_by('id', 'desc');
		if (isset($params) && !empty($params)) {
			$this->db->limit($params['limit'], $params['offset']);
		}
		$query = $this->db->get();
		//echo $this->db->last_query(); die;
		return $query->result_array();
	}
	/*
	 * Get all tbl_transactions
	 */
	function get_all_transactions_may()
	{ //die;
		$this->db->select('tbl_master_transaction.id,tbl_staff.staff_name,tbl_agent.agent_name,tbl_trans_numbers.created_date as createddate,tbl_trans_numbers.modified_date as modifieddate,tbl_master_transaction.t_date,tbl_master_transaction.total_number_amount,tbl_master_transaction.created_date, tbl_master_transaction.party_id,tbl_shift.shift_name as shift_name,tbl_shift.open_date,tbl_shift.super_admin,tbl_shift.data_entry_operator,tbl_shift.id as shift_id,tbl_ledger.ledger_name,tbl_trans_numbers.number as trnno,tbl_trans_numbers.amount as trn_amt');
		$this->db->from('tbl_master_transaction');
		$this->db->join('tbl_shift', 'tbl_shift.id = tbl_master_transaction.shift_id', 'FULL OUTER JOIN');
		$this->db->join('tbl_trans_numbers', 'tbl_trans_numbers.master_id = tbl_master_transaction.id', 'FULL OUTER JOIN');
		$this->db->join('tbl_ledger', 'tbl_ledger.id = tbl_master_transaction.party_id', 'FULL OUTER JOIN');
		$this->db->join('tbl_agent', 'tbl_ledger.agent_id = tbl_agent.id', 'LEFT');
		$this->db->join('tbl_staff', 'tbl_staff.id = tbl_master_transaction.created_by', 'FULL OUTER JOIN');
		$this->db->where('tbl_master_transaction.t_date', date('Y-m-d', time()));
		$this->db->where('tbl_master_transaction.created_by', $this->session->userid);
		$this->db->order_by("tbl_master_transaction.id", "desc");
		//$this->db->limit('10', '0');		
		//$this->db->order_by('id', 'desc');
		if (isset($params) && !empty($params)) {
			$this->db->limit($params['limit'], $params['offset']);
		}
		$query = $this->db->get();
		//echo $this->db->last_query(); die;
		return $query->result_array();
	}
	/*
	 * Get all tbl_transactions
	 */
	function get_all_transactions_admin_may()
	{ //die;
		$this->db->select('tbl_master_transaction.id,tbl_shift.open_date,tbl_shift.super_admin,tbl_shift.data_entry_operator,tbl_shift.super_admin,
		tbl_shift.data_entry_operator,tbl_trans_numbers.created_date as createddate,tbl_trans_numbers.modified_date as modifieddate,tbl_master_transaction.t_date,tbl_master_transaction.total_number_amount,tbl_master_transaction.created_date, tbl_master_transaction.party_id,tbl_shift.open_date,tbl_shift.shift_name as shift_name,tbl_shift.id as shift_id,tbl_ledger.ledger_name,tbl_trans_numbers.number as trnno,tbl_trans_numbers.amount as trn_amt');
		$this->db->from('tbl_master_transaction');
		$this->db->join('user_shift_timings', 'user_shift_timings.id = tbl_master_transaction.shift_id', 'FULL OUTER JOIN');
		$this->db->join('tbl_shift', 'tbl_shift.id = user_shift_timings.shift_id', 'FULL OUTER JOIN');

		$this->db->join('tbl_trans_numbers', 'tbl_trans_numbers.master_id = tbl_master_transaction.id', 'FULL OUTER JOIN');
		$this->db->join('tbl_ledger', 'tbl_ledger.id = tbl_master_transaction.party_id', 'FULL OUTER JOIN');
		//$this->db->join('tbl_agent', 'tbl_ledger.agent_id = tbl_agent.id', 'FULL OUTER JOIN');
		//$this->db->join('tbl_staff', 'tbl_staff.id = tbl_master_transaction.created_by', 'LEFT');
		$this->db->where('tbl_master_transaction.t_date', date('Y-m-d', time()));
		//$this->db->where('tbl_master_transaction.created_by', $this->session->userid);
		$this->db->where('tbl_master_transaction.show_to_admin', '1');
		$this->db->order_by("tbl_master_transaction.id", "desc");
		//$this->db->limit('10', '0');		
		//$this->db->order_by('id', 'desc');
		if (isset($params) && !empty($params)) {
			$this->db->limit($params['limit'], $params['offset']);
		}
		$query = $this->db->get();
		//echo $this->db->last_query(); die;
		return $query->result_array();
	}

	/*
	 * Get all tbl_transactions
	 */
	function get_all_transactions()
	{ //die;
		$this->db->select('tbl_master_transaction.id,tbl_master_transaction.t_date,tbl_master_transaction.total_number_amount,tbl_master_transaction.created_date, tbl_master_transaction.party_id,tbl_shift.shift_name as shift_name,tbl_shift.id as shift_id,tbl_ledger.ledger_name,tbl_trans_add.number as trnno,tbl_trans_add.Amount as trn_amt');
		$this->db->select('tbl_trans_cross.ander,tbl_trans_cross.bahar,tbl_trans_cross.cross_count,tbl_trans_cross.amount as trncrs_amt');
		$this->db->select('tbl_random_f4.number,tbl_random_f4.amount,tbl_random_f4.total_amount as trnf4_tamt');
		$this->db->select('tbl_trans_fromto.fromto_from,tbl_trans_fromto.fromto_to,tbl_trans_fromto.fromto_amount,tbl_trans_fromto.all_commission');
		$this->db->select('tbl_random_f8.dara_f8,tbl_random_f8.dara_amount_f8,tbl_random_f8.akhar_bahar_f8,tbl_random_f8.amount_akahr_bahar_f8,tbl_random_f8.akahr_andar_f8,tbl_random_f8.amount_akahr_andar_f8,tbl_random_f8.total_amount ');
		$this->db->from('tbl_master_transaction');
		$this->db->join('tbl_trans_add', 'tbl_trans_add.master_id = tbl_master_transaction.id', 'FULL OUTER JOIN');
		$this->db->join('tbl_random_f4', 'tbl_random_f4.trns_id = tbl_master_transaction.id', 'FULL OUTER JOIN');
		$this->db->join('tbl_random_f8', 'tbl_random_f8.master_id = tbl_master_transaction.id', 'FULL OUTER JOIN');
		$this->db->join('tbl_shift', 'tbl_shift.id = tbl_master_transaction.shift_id', 'FULL OUTER JOIN');
		$this->db->join('tbl_trans_cross', 'tbl_trans_cross.master_id = tbl_master_transaction.id', 'FULL OUTER JOIN');
		$this->db->join('tbl_ledger', 'tbl_ledger.id = tbl_master_transaction.party_id', 'FULL OUTER JOIN');
		$this->db->join('tbl_trans_fromto', 'tbl_trans_fromto.master_id = tbl_master_transaction.id', 'FULL OUTER JOIN');

		$this->db->order_by("tbl_master_transaction.id", "desc");
		//$this->db->limit('10', '0');		
		//$this->db->order_by('id', 'desc');
		if (isset($params) && !empty($params)) {
			$this->db->limit($params['limit'], $params['offset']);
		}
		$query = $this->db->get();
		//echo $this->db->last_query(); die;
		return $query->result_array();
	}

	/*
	 * Get custom tbl_transactions
	 */
	function get_edit_transactions($id)
	{
		$this->db->select('tbl_master_transaction.id,tbl_master_transaction.t_date,
		tbl_master_transaction.shift_id as shiftid,tbl_shift.shift_name,
		tbl_ledger.id as ledgerid,tbl_ledger.ledger_name,
		tbl_trans_numbers.number as trnno,tbl_trans_numbers.amount as trn_amt');
		$this->db->from('tbl_master_transaction');
		$this->db->join('tbl_trans_numbers', 'tbl_trans_numbers.master_id = tbl_master_transaction.id', 'FULL OUTER JOIN');
		$this->db->join('tbl_ledger', 'tbl_ledger.id = tbl_master_transaction.party_id', 'FULL OUTER JOIN');
		$this->db->join('user_shift_timings', 'user_shift_timings.id = tbl_master_transaction.shift_id', 'FULL OUTER JOIN');
		$this->db->join('tbl_shift', 'user_shift_timings.shift_id = tbl_shift.id', 'FULL OUTER JOIN');

		$this->db->where('tbl_master_transaction.id', $id);
		$this->db->order_by("tbl_master_transaction.id", "desc");
		//$this->db->limit('10', '0');		
		//$this->db->order_by('id', 'desc');
		if (isset($params) && !empty($params)) {
			$this->db->limit($params['limit'], $params['offset']);
		}
		$query = $this->db->get();
		//echo $this->db->last_query(); die;
		return $query->result_array();
	}
	/*
	 * Get custom tbl_transactions
	 */
	function get_custom_transactions($id)
	{
		$this->db->select('tbl_master_transaction.id,tbl_master_transaction.t_date,tbl_master_transaction.total_number_amount as ttamnt,tbl_shift.id as shiftid,tbl_ledger.id as ledgerid,tbl_ledger.ledger_name,tbl_ledger.dara_commision as dcomm,
		tbl_ledger.hissa as dhissa, tbl_trans_numbers.number as trnno,tbl_trans_numbers.amount as trn_amt');
		//$this->db->select('tbl_trans_cross.ander,tbl_trans_cross.bahar,tbl_trans_cross.cross_count,tbl_trans_cross.amount as trncrs_amt');
		//$this->db->select('tbl_random_f4.number,tbl_random_f4.amount,tbl_random_f4.total_amount as trnf4_tamt');
		//$this->db->select('tbl_trans_fromto.fromto_from,tbl_trans_fromto.fromto_to,tbl_trans_fromto.fromto_amount,tbl_trans_fromto.all_commission');
		//$this->db->select('tbl_random_f8.dara_f8,tbl_random_f8.dara_amount_f8,tbl_random_f8.akhar_bahar_f8,tbl_random_f8.amount_akahr_bahar_f8,tbl_random_f8.akahr_andar_f8,tbl_random_f8.amount_akahr_andar_f8,tbl_random_f8.total_amount ');
		$this->db->from('tbl_master_transaction');
		$this->db->join('tbl_trans_numbers', 'tbl_trans_numbers.master_id = tbl_master_transaction.id', 'FULL OUTER JOIN');
		//$this->db->join('tbl_random_f4', 'tbl_random_f4.trns_id = tbl_master_transaction.id','FULL OUTER JOIN');	
		//$this->db->join('tbl_random_f8', 'tbl_random_f8.master_id = tbl_master_transaction.id','FULL OUTER JOIN');	

		//$this->db->join('tbl_trans_cross', 'tbl_trans_cross.master_id = tbl_master_transaction.id','FULL OUTER JOIN');
		$this->db->join('tbl_ledger', 'tbl_ledger.id = tbl_master_transaction.party_id', 'FULL OUTER JOIN');
		$this->db->join('tbl_shift', 'tbl_shift.id = tbl_master_transaction.shift_id', 'FULL OUTER JOIN');
		$this->db->join('tbl_trans_fromto', 'tbl_trans_fromto.master_id = tbl_master_transaction.id', 'FULL OUTER JOIN');
		$this->db->where('tbl_master_transaction.id', $id);
		$this->db->order_by("tbl_master_transaction.id", "desc");
		//$this->db->limit('10', '0');		
		//$this->db->order_by('id', 'desc');
		if (isset($params) && !empty($params)) {
			$this->db->limit($params['limit'], $params['offset']);
		}
		$query = $this->db->get();
		echo $this->db->last_query();
		die;
		return $query->result_array();
	}
	function send_jantri($pid, $date)
	{
		$params = array('show_to_admin' => '1');
		$this->db->where('tbl_master_transaction.shift_id', $pid);
		$this->db->where('tbl_master_transaction.t_date', date('Y-m-d', strtotime($date)) . ' 00:00:00');
		return $this->db->update('tbl_master_transaction', $params);
	}

	function get_custom_transactions_total_shift_admin($pid, $date)
	{


		$this->db->select('tbl_master_transaction.id,tbl_master_transaction.show_to_admin, tbl_master_transaction.t_date,tbl_master_transaction.total_number_amount as ttamnt,tbl_shift.id as shiftid,tbl_ledger.id as ledgerid,tbl_ledger.ledger_name,tbl_ledger.dara_commision as dcomm,
		tbl_ledger.hissa as dhissa,tbl_ledger.tppercentage as tppercentage, tbl_trans_numbers.number as trnno,tbl_trans_numbers.amount as trn_amt');
		//$this->db->select('tbl_trans_cross.ander,tbl_trans_cross.bahar,tbl_trans_cross.cross_count,tbl_trans_cross.amount as trncrs_amt');
		//$this->db->select('tbl_random_f4.number,tbl_random_f4.amount,tbl_random_f4.total_amount as trnf4_tamt');
		//$this->db->select('tbl_trans_fromto.fromto_from,tbl_trans_fromto.fromto_to,tbl_trans_fromto.fromto_amount,tbl_trans_fromto.all_commission');
		//$this->db->select('tbl_random_f8.dara_f8,tbl_random_f8.dara_amount_f8,tbl_random_f8.akhar_bahar_f8,tbl_random_f8.amount_akahr_bahar_f8,tbl_random_f8.akahr_andar_f8,tbl_random_f8.amount_akahr_andar_f8,tbl_random_f8.total_amount ');
		$this->db->from('tbl_master_transaction');
		$this->db->join('tbl_trans_numbers', 'tbl_trans_numbers.master_id = tbl_master_transaction.id', 'FULL OUTER JOIN');
		//$this->db->join('tbl_random_f4', 'tbl_random_f4.trns_id = tbl_master_transaction.id','FULL OUTER JOIN');	
		//$this->db->join('tbl_random_f8', 'tbl_random_f8.master_id = tbl_master_transaction.id','FULL OUTER JOIN');	

		//$this->db->join('tbl_trans_cross', 'tbl_trans_cross.master_id = tbl_master_transaction.id','FULL OUTER JOIN');
		$this->db->join('tbl_ledger', 'tbl_ledger.id = tbl_master_transaction.party_id', 'FULL OUTER JOIN');
		$this->db->join('user_shift_timings', 'user_shift_timings.id = tbl_master_transaction.shift_id', 'FULL OUTER JOIN');
		$this->db->join('tbl_shift', 'tbl_shift.id = user_shift_timings.shift_id', 'FULL OUTER JOIN');
		//$this->db->join('tbl_trans_fromto', 'tbl_trans_fromto.master_id = tbl_master_transaction.id','FULL OUTER JOIN');	
		//$this->db->where('tbl_master_transaction.shift_id', $pid);
		$this->db->where('user_shift_timings.shift_id', $pid);
		$this->db->where('tbl_master_transaction.t_date', date('Y-m-d', strtotime($date)) . ' 00:00:00');
		$this->db->where('tbl_ledger.updated_by', $this->session->userid);
		$this->db->order_by("tbl_master_transaction.id", "desc");
		//$this->db->limit('10', '0');		
		//$this->db->order_by('id', 'desc');
		if (isset($params) && !empty($params)) {
			$this->db->limit($params['limit'], $params['offset']);
		}
		$query = $this->db->get();
		//echo $this->db->last_query(); die;
		return $query->result_array();
	}


	function get_custom_transactions_total_shift_master($pid, $date)
	{
		$this->db->select('tbl_master_transaction.id,tbl_master_transaction.show_to_admin, tbl_master_transaction.t_date,tbl_master_transaction.total_number_amount as ttamnt,tbl_shift.id as shiftid,tbl_ledger.id as ledgerid,tbl_ledger.ledger_name,tbl_ledger.dara_commision as dcomm,
			tbl_ledger.hissa as dhissa,tbl_ledger.tppercentage as tppercentage, tbl_trans_numbers.number as trnno,tbl_trans_numbers.amount as trn_amt');
		//$this->db->select('tbl_trans_cross.ander,tbl_trans_cross.bahar,tbl_trans_cross.cross_count,tbl_trans_cross.amount as trncrs_amt');
		//$this->db->select('tbl_random_f4.number,tbl_random_f4.amount,tbl_random_f4.total_amount as trnf4_tamt');
		//$this->db->select('tbl_trans_fromto.fromto_from,tbl_trans_fromto.fromto_to,tbl_trans_fromto.fromto_amount,tbl_trans_fromto.all_commission');
		//$this->db->select('tbl_random_f8.dara_f8,tbl_random_f8.dara_amount_f8,tbl_random_f8.akhar_bahar_f8,tbl_random_f8.amount_akahr_bahar_f8,tbl_random_f8.akahr_andar_f8,tbl_random_f8.amount_akahr_andar_f8,tbl_random_f8.total_amount ');
		$this->db->from('tbl_master_transaction');
		$this->db->join('tbl_trans_numbers', 'tbl_trans_numbers.master_id = tbl_master_transaction.id', 'FULL OUTER JOIN');
		//$this->db->join('tbl_random_f4', 'tbl_random_f4.trns_id = tbl_master_transaction.id','FULL OUTER JOIN');	
		//$this->db->join('tbl_random_f8', 'tbl_random_f8.master_id = tbl_master_transaction.id','FULL OUTER JOIN');	

		//$this->db->join('tbl_trans_cross', 'tbl_trans_cross.master_id = tbl_master_transaction.id','FULL OUTER JOIN');
		$this->db->join('tbl_ledger', 'tbl_ledger.id = tbl_master_transaction.party_id', 'FULL OUTER JOIN');
		$this->db->join('user_shift_timings', 'user_shift_timings.id = tbl_master_transaction.shift_id', 'FULL OUTER JOIN');
		$this->db->join('tbl_shift', 'tbl_shift.id = user_shift_timings.shift_id', 'FULL OUTER JOIN');
		//$this->db->join('tbl_trans_fromto', 'tbl_trans_fromto.master_id = tbl_master_transaction.id','FULL OUTER JOIN');	
		//$this->db->where('tbl_master_transaction.shift_id', $pid);
		$this->db->where('user_shift_timings.id', $pid);
		$this->db->where('tbl_master_transaction.t_date', date('Y-m-d', strtotime($date)) . ' 00:00:00');
		$this->db->where('tbl_ledger.updated_by', $this->session->userid);
		$this->db->order_by("tbl_master_transaction.id", "desc");
		//$this->db->limit('10', '0');		
		//$this->db->order_by('id', 'desc');
		if (isset($params) && !empty($params)) {
			$this->db->limit($params['limit'], $params['offset']);
		}
		$query = $this->db->get();
		//echo $this->db->last_query(); die;
		return $query->result_array();
	}
	function get_custom_transactions_total_shift($pid, $date)
	{
		$this->db->select('tbl_master_transaction.id,tbl_master_transaction.show_to_admin, tbl_master_transaction.t_date,tbl_master_transaction.total_number_amount as ttamnt,tbl_shift.id as shiftid,tbl_ledger.id as ledgerid,tbl_ledger.ledger_name,tbl_ledger.dara_commision as dcomm,
		tbl_ledger.hissa as dhissa,tbl_ledger.tppercentage as tppercentage, tbl_trans_numbers.number as trnno,tbl_trans_numbers.amount as trn_amt');
		//$this->db->select('tbl_trans_cross.ander,tbl_trans_cross.bahar,tbl_trans_cross.cross_count,tbl_trans_cross.amount as trncrs_amt');
		//$this->db->select('tbl_random_f4.number,tbl_random_f4.amount,tbl_random_f4.total_amount as trnf4_tamt');
		//$this->db->select('tbl_trans_fromto.fromto_from,tbl_trans_fromto.fromto_to,tbl_trans_fromto.fromto_amount,tbl_trans_fromto.all_commission');
		//$this->db->select('tbl_random_f8.dara_f8,tbl_random_f8.dara_amount_f8,tbl_random_f8.akhar_bahar_f8,tbl_random_f8.amount_akahr_bahar_f8,tbl_random_f8.akahr_andar_f8,tbl_random_f8.amount_akahr_andar_f8,tbl_random_f8.total_amount ');
		$this->db->from('tbl_master_transaction');
		$this->db->join('tbl_trans_numbers', 'tbl_trans_numbers.master_id = tbl_master_transaction.id', 'FULL OUTER JOIN');
		//$this->db->join('tbl_random_f4', 'tbl_random_f4.trns_id = tbl_master_transaction.id','FULL OUTER JOIN');	
		//$this->db->join('tbl_random_f8', 'tbl_random_f8.master_id = tbl_master_transaction.id','FULL OUTER JOIN');	

		//$this->db->join('tbl_trans_cross', 'tbl_trans_cross.master_id = tbl_master_transaction.id','FULL OUTER JOIN');
		$this->db->join('tbl_ledger', 'tbl_ledger.id = tbl_master_transaction.party_id', 'FULL OUTER JOIN');
		$this->db->join('tbl_shift', 'tbl_shift.id = tbl_master_transaction.shift_id', 'FULL OUTER JOIN');
		//$this->db->join('tbl_trans_fromto', 'tbl_trans_fromto.master_id = tbl_master_transaction.id','FULL OUTER JOIN');	
		$this->db->where('tbl_master_transaction.shift_id', $pid);
		$this->db->where('tbl_master_transaction.t_date', date('Y-m-d', strtotime($date)) . ' 00:00:00');
		$this->db->where('tbl_ledger.updated_by', $this->session->userid);
		$this->db->order_by("tbl_master_transaction.id", "desc");
		//$this->db->limit('10', '0');		
		//$this->db->order_by('id', 'desc');
		if (isset($params) && !empty($params)) {
			$this->db->limit($params['limit'], $params['offset']);
		}
		$query = $this->db->get();
		//echo $this->db->last_query(); die;
		return $query->result_array();
	}
	function get_custom_transactions_total($pid, $date)
	{
		$this->db->select('tbl_master_transaction.id,tbl_master_transaction.t_date,tbl_shift.id as shiftid,tbl_ledger.id as ledgerid,tbl_ledger.ledger_name,tbl_trans_add.number as trnno,tbl_trans_add.Amount as trn_amt');
		$this->db->select('tbl_trans_cross.ander,tbl_trans_cross.bahar,tbl_trans_cross.cross_count,tbl_trans_cross.amount as trncrs_amt');
		$this->db->select('tbl_random_f4.number,tbl_random_f4.amount,tbl_random_f4.total_amount as trnf4_tamt');
		$this->db->select('tbl_trans_fromto.fromto_from,tbl_trans_fromto.fromto_to,tbl_trans_fromto.fromto_amount,tbl_trans_fromto.all_commission');
		$this->db->select('tbl_random_f8.dara_f8,tbl_random_f8.dara_amount_f8,tbl_random_f8.akhar_bahar_f8,tbl_random_f8.amount_akahr_bahar_f8,tbl_random_f8.akahr_andar_f8,tbl_random_f8.amount_akahr_andar_f8,tbl_random_f8.total_amount ');
		$this->db->from('tbl_master_transaction');
		$this->db->join('tbl_trans_add', 'tbl_trans_add.master_id = tbl_master_transaction.id', 'FULL OUTER JOIN');
		$this->db->join('tbl_random_f4', 'tbl_random_f4.trns_id = tbl_master_transaction.id', 'FULL OUTER JOIN');
		$this->db->join('tbl_random_f8', 'tbl_random_f8.master_id = tbl_master_transaction.id', 'FULL OUTER JOIN');

		$this->db->join('tbl_trans_cross', 'tbl_trans_cross.master_id = tbl_master_transaction.id', 'FULL OUTER JOIN');
		$this->db->join('tbl_ledger', 'tbl_ledger.id = tbl_master_transaction.party_id', 'FULL OUTER JOIN');
		$this->db->join('tbl_shift', 'tbl_shift.id = tbl_master_transaction.shift_id', 'FULL OUTER JOIN');
		$this->db->join('tbl_trans_fromto', 'tbl_trans_fromto.master_id = tbl_master_transaction.id', 'FULL OUTER JOIN');
		$this->db->where('tbl_master_transaction.party_id', $pid);
		$this->db->where('tbl_master_transaction.t_date', $date);
		$this->db->order_by("tbl_master_transaction.id", "desc");
		//$this->db->limit('10', '0');		
		//$this->db->order_by('id', 'desc');
		if (isset($params) && !empty($params)) {
			$this->db->limit($params['limit'], $params['offset']);
		}
		$query = $this->db->get();
		//echo $this->db->last_query(); die;
		return $query->result_array();
	}

	/*
	 * function to add new tbl_transactions
	 */
	function add_tbl_transactions($params)
	{ //echo '<pre>'; print_r(); echo '</pre>';
		$this->db->insert('tbl_master_transaction', $params);
		return $this->db->insert_id();
	}

	/*
	 * function to add new tbl_transactions
	 */
	function edit_tbl_transaction($id, $params)
	{         // echo '<pre>'; echo $id; print_r($params); echo '</pre>'; die;
		$this->db->where('id', $id);
		return $this->db->update('tbl_master_transaction', $params);
	}

	/*
	 * function to add new tbl_transactions
	 */
	function updateclosing($opening, $tid, $dateoftrn)
	{         // echo '<pre>'; echo $id; print_r($dateoftrn); echo '</pre>'; die;
		date_default_timezone_set('Asia/Kolkata');
		$params = array('opening' => $opening, 'ledger_id' => $tid, 'dated' => date('Y-m-d', strtotime($dateoftrn)), 'updated_at' => date('Y-m-d h:i:s', time()));
		$check = $this->isexistclosing($tid, $dateoftrn);

		if (!empty($check)) { //echo '<pre>'; print_r($params); die;
			$this->db->where('id', $check->id);
			$update = $this->db->update('tbl_opening', $params);
			return $update;
		} else {
			$this->db->insert('tbl_opening', $params);
			return $this->db->insert_id();
		}
		// $query = $this->db->where('id',$tid);
		//return $this->db->update('tbl_opening',$params);
		// echo $query->createCommand()->getRawSql();

		//return $this->db->update('Tb_Date_shift_party_entry',$params);
	}
	/*
	 * function to add new tbl_transactions
	 */
	function updateclosingback($opening, $tid, $dateoftrn)
	{         // echo '<pre>'; echo $id; print_r($dateoftrn); echo '</pre>'; die;
		date_default_timezone_set('Asia/Kolkata');
		$params = array('opening' => $opening, 'ledger_id' => $tid, 'dated' => date('Y-m-d', strtotime($dateoftrn)), 'updated_at' => date('Y-m-d h:i:s', time()));
		$check = $this->isexistclosing($tid, $dateoftrn);

		if (!empty($check)) { //echo '<pre>'; print_r($params); die;
			$this->db->where('id', $check->id);
			$update = $this->db->update('tbl_opening', $params);
			return $update;
		} else {
			$this->db->insert('tbl_opening', $params);
			return $this->db->insert_id();
		}
		// $query = $this->db->where('id',$tid);
		//return $this->db->update('tbl_opening',$params);
		// echo $query->createCommand()->getRawSql();

		//return $this->db->update('Tb_Date_shift_party_entry',$params);
	}
	function isexistclosing($tid, $dateoftrn)
	{
		//	$query = $this->db->query('SELECT id FROM tbl_opening where dated='.$dateoftrn.' AND ledger_id='.$tid)->get()->row();
		//echo $query->id;
		return $this->db->get_where('tbl_opening', array('dated' => date('Y-m-d', strtotime($dateoftrn)), 'ledger_id' => $tid))->row();
		//echo $this->db->last_query(); //die;
	}
	/*
	 * function to add new add_Tb_Date_shift_party_entry
	 */
	function add_Tb_Date_shift_party_entry($params)
	{  //echo '<pre>';print_r($params); die;
		//$params['master_id'] = $master_id; 
		$this->db->insert('Tb_Date_shift_party_entry', $params);
		// Optionally print params for more insight
		//  echo '<pre>';
		//  print_r($params);
		//  echo '</pre>';

		// echo $this->db->last_query(); die;
		return $this->db->insert_id();
	}


	/*
	 * function to add new tbl_transaction_ledger
	 */
	function add_tbl_transaction_ledger($params)
	{ //print_r($params); //print_r($this->session->userid); die;
		$param['Date'] = $params['date'];
		$param['ShiftId'] = $params['shift'];
		$param['PartyId'] = $params['party'];
		$param['status'] = '1';

		$this->db->insert('Tb_Date_shift_party_entry', $param);
		$mst_id = $this->db->insert_id();
		return $mst_id;
	}
	/*
	 * function to add new tbl_transaction
	 */
	function get_party_id($masterid)
	{
		return $this->db->get_where('tbl_master_transaction', array('id' => $masterid))->row_array();
	}
	/*
	 * function to add new tbl_transaction
	 */
	function get_transaction_result_total($masterid)
	{
		return $this->db->get_where('Tb_Date_shift_party_entry', array('id' => $masterid))->row_array();
	}
	/*
	 * function to add new tbl_transaction
	 */
	function add_tbl_transaction($params)
	{ //print_r($params); //print_r($this->session->userid); die;
		$params['created_by'] = $this->session->userid;
		//$param['shift_id']=$params['shift_id'];
		//$param['party_id']=$params['party_id'];
		$params['status'] = '1';
		//print_r($params);
		$this->db->insert('tbl_master_transaction', $params);
		$mst_id = $this->db->insert_id();
		return $mst_id;
	}

	function add_tbl_transaction_app($params)
{
    // If created_by is not passed or empty, take from session
    if (!isset($params['created_by']) || empty($params['created_by'])) {
        $params['created_by'] = $this->session->userid;
    }

    $params['status'] = '1';

    $this->db->insert('tbl_master_transaction', $params);
    return $this->db->insert_id();
}

	/*
	 * function to add new tbl_jantri
	 */
	function add_jantri($master_id, $params)
	{
		$param['trns_id'] = $master_id;
		$param['str_json'] = $params['dindex'];
		//$param['amount']=$params['amount'];
		$param['total_amount'] = $params['tamnt'];
		//print_r($param); print_r($this->session->userid); die;
		$this->db->insert('tbl_jantri', $param);
		$mst_id = $this->db->insert_id();
		return $mst_id;
	}

	/*
	 * function to add new tbl_transaction_random f4
	 */
	function add_tbl_randomf4($master_id, $params)
	{ //echo '<pre>';print_r($params); print_r($master_id); die;
		$param['trns_id'] = $master_id;
		$param['number'] = implode(',', $params['number']);
		$param['amount'] = $params['randf4amount'];
		$param['total_amount'] = $params['thamount'];
		//print_r($param); print_r($this->session->userid); die;
		$this->db->insert('tbl_random_f4', $param);
		$mst_id = $this->db->insert_id();
		//echo  json_encode($param);
		return $mst_id;
	}
	/*
	 * function to edit new tbl_transaction_random f4
	 */
	function edit_tbl_randomf4($master_id, $params)
	{ //echo '<pre>';print_r($params); print_r($master_id); die;
		//$param['trns_id']=$master_id;
		$param['number'] = implode(',', $params['number']);
		$param['amount'] = $params['randf4amount'];
		$param['total_amount'] = $params['thamount'];
		//print_r($param); print_r($this->session->userid); die;
		$this->db->where('trns_id', $master_id);
		return $this->db->update('tbl_random_f4', $param);
	}
	/*
	 * function to edit new tbl_transaction_random f4
	 */
	function edit_cross($master_id, $params)
	{  // echo '<pre>'; print_r($params); echo '</pre>'; die;
		//$param['master_id']=$master_id;
		$param['ander'] = $params['ander'];
		$param['bahar'] = $params['bahar'];
		$param['joda'] = $params['joda'];
		$param['cross_count'] = $params['cross_count'];
		$param['amount'] = $params['amount'];
		$param['all_commission'] = $params['total_amount_cross'];
		//print_r($param); print_r($this->session->userid); die;
		$this->db->where('master_id', $master_id);
		return $this->db->update('tbl_trans_cross', $param);
	}
	/*
	 * function to add new tbl_transaction_random f4
	 */
	function add_cross($master_id, $params)
	{  // echo '<pre>'; print_r($params); echo '</pre>'; die;
		$param['master_id'] = $master_id;
		$param['ander'] = $params['ander'];
		$param['bahar'] = $params['bahar'];
		$param['joda'] = $params['joda'];
		$param['cross_count'] = $params['cross_count'];
		$param['amount'] = $params['amount'];
		$param['all_commission'] = $params['total_amount_cross'];
		//print_r($param); print_r($this->session->userid); die;
		$this->db->insert('tbl_trans_cross', $param);
		$mst_id = $this->db->insert_id();
		//echo  json_encode($param);
		return $mst_id;
	}

	/*
	 * function to edit new tbl_transaction_random f4
	 */
	function edit_fromto($master_id, $params)
	{   //echo '<pre>'; print_r($params); echo '</pre>'; die;
		// $param['master_id']=$master_id;
		$param['fromto_from'] = $params['fromto_from'];
		$param['fromto_to'] = $params['fromto_to'];
		$param['fromto_amount'] = $params['fromto_amount'];
		$param['all_commission'] = $params['total_amount_fromto'];
		//print_r($param); print_r($this->session->userid); die;
		$this->db->where('master_id', $master_id);
		return $this->db->update('tbl_trans_fromto', $param);
	}
	/*
	 * function to add new tbl_transaction_random f4
	 */
	function add_fromto($master_id, $params)
	{   //echo '<pre>'; print_r($params); echo '</pre>'; die;
		$param['master_id'] = $master_id;
		$param['fromto_from'] = $params['fromto_from'];
		$param['fromto_to'] = $params['fromto_to'];
		$param['fromto_amount'] = $params['fromto_amount'];
		$param['all_commission'] = $params['total_amount_fromto'];
		//print_r($param); print_r($this->session->userid); die;
		$this->db->insert('tbl_trans_fromto', $param);
		$mst_id = $this->db->insert_id();
		//echo  json_encode($param);
		return $mst_id;
	}

	/*
	 * function to add new tbl_transaction_random f4
	 */
	function edit_random_f8($master_id, $params)
	{   //echo '<pre>'; print_r($params); echo '</pre>'; die;
		//$param['master_id']=$master_id;
		$param['dara_amount_f8'] = $params['dara_amount_f8'];
		$param['akhar_bahar_f8'] = $params['akhar_bahar_f8'];
		$param['dara_f8'] = $params['dara_f8'];
		$param['amount_akahr_bahar_f8'] = $params['amount_akahr_bahar_f8'];
		$param['akahr_andar_f8'] = $params['akahr_andar_f8'];
		$param['amount_akahr_andar_f8'] = $params['amount_akahr_andar_f8'];
		$param['total_amount'] = $params['ranf8amt'];
		//print_r($param); print_r($this->session->userid); die;
		$this->db->where('master_id', $master_id);
		return $this->db->update('tbl_random_f8', $param);
		//echo  json_encode($param);
	}
	/*
	 * function to add new tbl_transaction_random f4
	 */
	function random_f8($master_id, $params)
	{   //echo '<pre>'; print_r($params); echo '</pre>'; die;
		$param['master_id'] = $master_id;
		$param['dara_amount_f8'] = $params['dara_amount_f8'];
		$param['akhar_bahar_f8'] = $params['akhar_bahar_f8'];
		$param['dara_f8'] = $params['dara_f8'];
		$param['amount_akahr_bahar_f8'] = $params['amount_akahr_bahar_f8'];
		$param['akahr_andar_f8'] = $params['akahr_andar_f8'];
		$param['amount_akahr_andar_f8'] = $params['amount_akahr_andar_f8'];
		$param['total_amount'] = $params['ranf8amt'];
		//print_r($param); print_r($this->session->userid); die;
		$this->db->insert('tbl_random_f8', $param);
		$mst_id = $this->db->insert_id();
		//echo  json_encode($param);
		return $mst_id;
	}

	/*
	 * function to add new tbl_master_transaction
	 */
	function add_tbl_only_transaction($master_id, $params)
	{ //echo '<pre>';print_r($params); print_r($master_id); die;
		$param['master_id'] = $master_id;
		$param['number'] = implode(',', $params['trn_number']);
		$param['Amount'] = implode(',', $params['trn_amount']);

		$this->db->insert('tbl_trans_add', $param);
		$mst_id = $this->db->insert_id();
		if ($mst_id) {
			$this->db->select_sum('Amount');
			$result = $this->db->get('tbl_trans_add')->row();
			//echo $result->amount;

		}
		$param['last_id'] = $mst_id;
		//echo  json_encode($param);
		//die;
		return $mst_id;
	}
	/*
	 * function to add new tbl_master_transaction_may
	 */
	function add_tbl_only_transaction_may($master_id, $params)
	{
		date_default_timezone_set('Asia/Kolkata');

		// Prefer session userid, otherwise take from POST params
		$userid = !empty($this->session->userid)
			? $this->session->userid
			: (!empty($params['userid']) ? $params['userid'] : null);

		$param['master_id']   = $master_id;
		$param['number']      = implode(',', $params['trn_number']);
		$param['amount']      = implode(',', $params['trn_amount']);
		$param['created_by']  = $userid;
		$param['modified_by'] = $userid;
		//$param['modified_date']=date("Y-m-d h:i:s",time());
		$param['created_date'] = date("Y-m-d h:i:s", time());
		//echo '<pre>';print_r($param); print_r($master_id); die;

		$this->db->insert('tbl_trans_numbers', $param);
		$mst_id = $this->db->insert_id();
		if ($mst_id) {
			$this->db->select_sum('Amount');
			$result = $this->db->get('tbl_trans_add')->row();
			//echo $result->amount;

		}
		$param['last_id'] = $mst_id;
		//echo  json_encode($param);
		//die;
		return $mst_id;
	}
	/*
	 * function to add new tbl_master_transaction_may
	 */
	function edit_tbl_only_transaction_may($master_id, $params)
	{
		date_default_timezone_set('Asia/Kolkata');
		//$param['master_id']=$master_id;
		$param['number'] = implode(',', $params['trn_number']);
		$param['amount'] = implode(',', $params['trn_amount']);
		$param['modified_date'] = date("Y-m-d h:i:s", time());
		//$param['created_by']=$this->session->userid;
		$param['modified_by'] = $this->session->userid;
		//echo '<pre>';print_r($param); print_r($master_id); die;

		$this->db->where('master_id', $master_id);
		return $this->db->update('tbl_trans_numbers', $param);
		//echo  json_encode($param);
		//die;
		//return $mst_id;

	}
	/*
	 * function to add new tbl_master_transaction
	 */
	function edit_tbl_only_transaction($id, $params)
	{ //echo '<pre>';print_r($params); print_r($id); die;

		$param['number'] = implode(',', array_values(array_filter($params['trn_number'])));
		$param['Amount'] = implode(',', array_values(array_filter($params['trn_amount'])));

		//$this->db->insert('tbl_trans_add',$param);
		$this->db->where('master_id', $id);
		return $this->db->update('tbl_trans_add', $param);
		//echo  json_encode($param);
		//die;
		//return $mst_id;

	}
	/*Total number amount update in loop after no opened*/
	function numberamountinloop($shift_id, $party_id, $date, $data)
	{
		$tdata = $this->tnumberdetails($shift_id, $party_id, $date);
		//echo '<pre>'; print_r($tdata); echo '</pre>'; die;
	}

	function add_Tb_Date_total_akhar_numbertest()
	{
		//echo '<pre>';print_r($params); print_r($master_id); die;
		for ($i = 0; $i < 10000; $i++) {
			$data[$i] = array(
				'Open_Number_amount' => '30',
				'Akhar_Number_amount' => '10',
				'Total_Number_amount' => '240',
				'Total_Akhar_amount' => '60',
				'Total_amount' => '300',
				'DARATotalAmt' => '2700',
				'AmountCom' => '24',
				'AkarAmount' => '90',
				'Akharcom' => '6',
				'AkarNumber_AndBothComisionTotal' => '2820',
				'ProfitAmount' => '-2520',
				'RebateAmount' => '0',
				'ProfiteAfterRebate' => '-2520',
				'TP_person' => '4',
				'TP_perc' => '10',
				'TP_Amount' => '-252',
				'Hissa' => '6',
				'hissa_perc' => '10',
				'Hissa_Amount' => '-252',
				'Net_profit' => '-2016',
			);
		}
		//echo '<pre>'; print_r($data); die;
		//$data = array( 
		//$myarr
		//);

		//$sql = $this->db->set($data)->get_compiled_insert('mytable');
		$sql = $this->db->insert_batch('Tb_Date_shift_party_entrytest', $data);
		echo $sql;
		//$this->db->insert('tbl_trans_add',$param);
	}
	function getexistingdata($id)
	{
		return $this->db->get_where('Tb_Date_shift_party_entry', array('id' => $id))->row_array();
	}
	function add_Tb_Date_total_akhar_numbertempedit($key, $id, $party_id, $date, $data)
	{ //echo $id;
		$gdata = $this->getexistingdata($id);
		//echo '<pre>'; print_r($gdata); print_r($data); echo '</pre>'; die;
		//$gdata['Open_Number_amount'] =0;
		//$gdata['Akhar_Number_amount'] =0;
		//if($key){
		if ($key == '1') {
			$param['Open_Number_amount'] = $data['Open_Number_amount'];
			$param['Akhar_Number_amount'] = $data['Akhar_Number_amount'];
			$param['Total_amount'] = $data['Total_amount'];
		} else {
			$param['Open_Number_amount'] = $gdata['Open_Number_amount'] + $data['Open_Number_amount'];
			$param['Akhar_Number_amount'] = $gdata['Akhar_Number_amount'] + $data['Akhar_Number_amount'];
			$param['Total_amount'] = $data['Total_amount'] + $gdata['Total_amount'];
		}

		$param['Total_Number_amount'] = $gdata['Total_Number_amount'];
		$param['Total_Akhar_amount'] = $gdata['Total_Akhar_amount'];


		// get_transaction_result_total
		//$tdata= $this->tnumberdetails($shift_id,$data[$i]['party_id'],$date);
		$thridparty = $this->thirdpartydetails($party_id);
		//echo '<pre>';print_r($data);
		//echo '<pre>';print_r($tdata);
		//echo '<pre>';print_r($thridparty); echo '</pre>';die;
		$param['DARATotalAmt'] = $gdata['DaraRate'] * $param['Open_Number_amount'];
		$param['AmountCom'] = ($param['Total_Number_amount'] * $gdata['Commision']) / 100;
		$param['AkarAmount'] = ((isset($param['Akhar_Number_amount'])) ? $param['Akhar_Number_amount'] : '0') * $gdata['AkarRate'];
		$param['Akharcom'] = (((isset($param['Total_Akhar_amount'])) ? $param['Total_Akhar_amount'] : '0') * $gdata['Commission']) / 100;
		$param['AkarNumber_AndBothComisionTotal'] = $param['DARATotalAmt'] + $param['AmountCom'] + $param['AkarAmount'] + $param['Akharcom'];
		$param['ProfitAmount'] = ($param['Total_amount'] - $param['AkarNumber_AndBothComisionTotal']);
		//$param['RebateAmount'] = ($param['ProfitAmount']*$thridparty['rebate'])/100;
		$param['RebateAmount'] = 0;
		$param['ProfiteAfterRebate'] = $param['ProfitAmount'] - $param['RebateAmount'];
		$param['TP_person'] = (isset($thridparty['tp_party_id'])) ? $thridparty['tp_party_id'] : '0';
		if ($param['TP_person'] != "") {
			$param['TP_perc'] = (isset($thridparty['tppercentage'])) ? $thridparty['tppercentage'] : '0';
			$param['TP_Amount'] = ($param['ProfiteAfterRebate'] * $param['TP_perc']) / 100;
		} else {
			$param['TP_perc'] = 0;
			$param['TP_Amount'] = 0;
		}
		$param['Hissa'] = $party_id;
		$param['hissa_perc'] = (isset($thridparty['hissa'])) ? $thridparty['hissa'] : '0';
		$param['Hissa_Amount'] = ((int) $param['ProfiteAfterRebate'] * (int) $param['hissa_perc']) / 100;

		$param['Net_profit'] = $param['ProfiteAfterRebate'] - $param['TP_Amount'] - $param['Hissa_Amount'];
		$array = array('id' => $id, 'PartyId' => $party_id);
		//echo '<pre>';print_r($array); print_r($param);  die;
		//echo $party_id; echo $id; 
		//echo '</pre>'; //die;


		$this->db->where($array);

		$this->db->update('Tb_Date_shift_party_entry', $param);
		//echo $sql;
		//$ledger_final_ledger = $this->ledger_final_ledger($party_id,$date,$param['Net_profit'],"+");
	}
	function add_Tb_Date_total_akhar_numbertemp($id, $party_id, $date, $data)
	{
		$gdata = $this->getexistingdata($id);
		//echo '<pre>'; print_r($gdata); print_r($data); echo '</pre>'; //die;
		//$gdata['Open_Number_amount'] =0;
		//$gdata['Akhar_Number_amount'] =0;
		$param['Open_Number_amount'] = $data['Open_Number_amount'];
		$param['Akhar_Number_amount'] = $data['Akhar_Number_amount'];
		$param['Total_Number_amount'] = $gdata['Total_Number_amount'];
		$param['Total_Akhar_amount'] = $gdata['Total_Akhar_amount'];
		$param['Total_amount'] = $gdata['Total_amount'];


		// get_transaction_result_total
		//$tdata= $this->tnumberdetails($shift_id,$data[$i]['party_id'],$date);
		$thridparty = $this->thirdpartydetails($party_id);
		//echo '<pre>';print_r($data);
		//echo '<pre>';print_r($tdata);
		//echo '<pre>';print_r($thridparty); echo '</pre>';die;
		$param['DARATotalAmt'] = $gdata['DaraRate'] * $param['Open_Number_amount'];
		$param['AmountCom'] = ($param['Total_Number_amount'] * $gdata['Commision']) / 100;
		$param['AkarAmount'] = ((isset($param['Akhar_Number_amount'])) ? $param['Akhar_Number_amount'] : '0') * $gdata['AkarRate'];
		$param['Akharcom'] = (((isset($param['Total_Akhar_amount'])) ? $param['Total_Akhar_amount'] : '0') * $gdata['Commission']) / 100;
		$param['AkarNumber_AndBothComisionTotal'] = $param['DARATotalAmt'] + $param['AmountCom'] + $param['AkarAmount'] + $param['Akharcom'];
		$param['ProfitAmount'] = ($param['Total_amount'] - $param['AkarNumber_AndBothComisionTotal']);
		//$param['RebateAmount'] = ($param['ProfitAmount']*$thridparty['rebate'])/100;
		$param['RebateAmount'] = 0;
		$param['ProfiteAfterRebate'] = $param['ProfitAmount'] - $param['RebateAmount'];
		$param['TP_person'] = (isset($thridparty['tp_party_id'])) ? $thridparty['tp_party_id'] : '';
		if ($param['TP_person'] != "") {
			$param['TP_perc'] = $thridparty['tppercentage'];
			$param['TP_Amount'] = ($param['ProfiteAfterRebate'] * $param['TP_perc']) / 100;
		} else {
			$param['TP_perc'] = 0;
			$param['TP_Amount'] = 0;
		}
		$param['Hissa'] = $party_id;
		$param['hissa_perc'] = (isset($thridparty['hissa'])) ? $thridparty['hissa'] : '';
		$param['Hissa_Amount'] = ((int) $param['ProfiteAfterRebate'] * (int) $param['hissa_perc']) / 100;

		$param['Net_profit'] = $param['ProfiteAfterRebate'] - $param['TP_Amount'] - $param['Hissa_Amount'];
		//echo '<pre>';print_r($param); echo '</pre>';
		$array = array('id' => $id, 'PartyId' => $party_id);

		$this->db->where($array);
		$this->db->update('Tb_Date_shift_party_entry', $param);
		//echo $sql;
		//echo $param['Net_profit']; die;
		//$ledger_final_ledger = $this->ledger_final_ledger($party_id,$date,$param['Net_profit'],"+");
	}

	/*
	 * function to update transaction result
	 */
	function add_Tb_Date_total_akhar_number($shift_id, $date, $data)
	{
		//$last_id = $this->db->insert_id(); 

		//$param['ShiftId']=$shift_id;
		//$param['PartyId']=$party_id;
		//$param['Date']=$date;
		//$last_id = $params['last_id'];
		//$param['Total_Number_amount']=$data[''];
		//$param['Total_Akhar_amount']=$takhar;
		for ($i = 0; $i < count($data); $i++) {
			//echo '<pre>';print_r($data[$i]); die;
			$param['Open_Number_amount'] = (isset($data[$i]['Open_Number_amount'])) ? $data[$i]['Open_Number_amount'] : '0';
			$param['Akhar_Number_amount'] = (isset($data[$i]['Akhar_Number_amount'])) ? $data[$i]['Akhar_Number_amount'] : '0';
			$param['Total_Number_amount'] = (isset($data[$i]['Total_Number_amount'])) ? $data[$i]['Total_Number_amount'] : '0';
			$param['Total_Akhar_amount'] = (isset($data[$i]['Total_Akhar_amount'])) ? $data[$i]['Total_Akhar_amount'] : '0';
			$param['Total_amount'] = (isset($data[$i]['Total_amount'])) ? $data[$i]['Total_amount'] : '0';

			// get_transaction_result_total
			$tdata = $this->tnumberdetails($shift_id, $data[$i]['party_id'], $date);
			$thridparty = $this->thirdpartydetails($data[$i]['party_id']);
			//echo '<pre>';print_r($data);
			//echo '<pre>';print_r($tdata);
			//echo '<pre>';print_r($thridparty); echo '</pre>';die;
			$param['DARATotalAmt'] = $tdata['DaraRate'] * $param['Open_Number_amount'];
			$param['AmountCom'] = ($param['Total_Number_amount'] * $tdata['Commision']) / 100;
			$param['AkarAmount'] = ((isset($param['Akhar_Number_amount'])) ? $param['Akhar_Number_amount'] : '0') * $tdata['AkarRate'];
			$param['Akharcom'] = (((isset($param['Total_Akhar_amount'])) ? $param['Total_Akhar_amount'] : '0') * $tdata['Commission']) / 100;
			$param['AkarNumber_AndBothComisionTotal'] = $param['DARATotalAmt'] + $param['AmountCom'] + $param['AkarAmount'] + $param['Akharcom'];
			$param['ProfitAmount'] = ($param['Total_amount'] - $param['AkarNumber_AndBothComisionTotal']);
			//$param['RebateAmount'] = ($param['ProfitAmount']*$thridparty['rebate'])/100;
			$param['RebateAmount'] = 0;
			$param['ProfiteAfterRebate'] = $param['ProfitAmount'] - $param['RebateAmount'];
			$param['TP_person'] = $thridparty['tp_party_id'];
			if ($param['TP_person'] != "") {
				$param['TP_perc'] = $thridparty['tppercentage'];
				$param['TP_Amount'] = ($param['ProfiteAfterRebate'] * $param['TP_perc']) / 100;
			} else {
				$param['TP_perc'] = 0;
				$param['TP_Amount'] = 0;
			}
			$param['Hissa'] = $data[$i]['party_id'];
			$param['hissa_perc'] = $thridparty['hissa'];
			$param['Hissa_Amount'] = ($param['ProfiteAfterRebate'] * $param['hissa_perc']) / 100;
			$param['Net_profit'] = $param['ProfiteAfterRebate'] - $param['TP_Amount'] - $param['Hissa_Amount'];

			/*$dataa[$i]=array(
				 'Open_Number_amount' => $param['Open_Number_amount'],
				 'Akhar_Number_amount'  => $param['Akhar_Number_amount'],
				 'Total_Number_amount'  => $param['Total_Number_amount'],
				 'Total_Akhar_amount' => $param['Total_Akhar_amount'],
				 'Total_amount'  => $param['Total_amount'],
				 'DARATotalAmt'  => $param['DARATotalAmt'],
				 'AmountCom' => $param['AmountCom'],
				 'AkarAmount'  => $param['AkarAmount'],
				 'Akharcom'  => $param['Akharcom'],
				 'AkarNumber_AndBothComisionTotal' => $param['AkarNumber_AndBothComisionTotal'],
				 'ProfitAmount'  => $param['ProfitAmount'],
				 'RebateAmount'  => $param['RebateAmount'],
				 'ProfiteAfterRebate' => $param['ProfiteAfterRebate'],
				 'TP_person'  => $param['TP_person'],
				 'TP_perc'  => $param['TP_perc'],
				 'TP_Amount' => $param['TP_Amount'],
				 'Hissa'  => $param['Hissa'],
				 'hissa_perc'  => $param['hissa_perc'],
				 'Hissa_Amount'  => $param['Hissa_Amount'],
				 'Net_profit'  => $param['Net_profit'],
		 );*/
			$array = array('PartyId' => $data[$i]['party_id'], 'ShiftId' => $shift_id, 'Date' => $date);

			$this->db->where($array);
			$this->db->update('Tb_Date_shift_party_entry', $param);
			//echo $sql;
			//$ledger_final_ledger = $this->ledger_final_ledger($data[$i]['party_id'],$date,$param['Net_profit'],"+");
		}

		//echo '<pre>'; print_r($dataa); echo '</pre>'; die;
		//$this->db->insert('Tb_Date_shift_party_entry',$param);
		//$param['ProfiteAfterRebate'] = $param['ProfitAmount']-$param['RebateAmount'];
		//$param['ProfiteAfterRebate'] = $param['ProfitAmount']-$param['RebateAmount'];
		//$this->db->where('PartyId',$party_id);
		//$this->db->where('ShiftId',$shift_id);
		//$this->db->where('Date',$date);


		//echo '<pre>';print_r($this->db->get_compiled_update()); echo '</pre>';//die;
		// $this->db->update('Tb_Date_shift_party_entry',$param);
		//echo $this->db->last_query(); //die;


		//print_r($updatedId); die;
		//$stats = $this->calctotalresult($updatedId);
		//return $updatedId;
		//$this->db->where('shift_id',$shift_id);
		//$this->db->where('party_id',$party_id);
		// $this->db->where('date',$date);
		/* $data = $this->get_Date_shift_party_entry($shift_id,$party_id,$date);
				echo '<pre>'; print_r($data); echo '</pre>';
		die;
		 if($this->db->update('tbl_trans_add',$param))
			  echo $this->db->last_query(); die;
		  echo  json_encode($params);*/
		//die;

	}

	/*
	 * function to add final_tbl_ledger_from_ledger
	 */
	function ledger_final_ledger($partyid, $date, $amount, $operation)
	{
		$exist = $this->ledger_final_same_date_exist($partyid, $date); /// for same date ?? hnji
		//echo '<pre>'; print_r($exist); die;
		if ($exist) {
			$cr_amnt = $exist['Closing'];
			$closingamnt = $exist['Closing'] + $amount;
			$samedayid = $exist['id'];
			//$param['PartyId']=$partyid;
			$param['Date'] = date('Y-m-d', strtotime($date));
			$param['CrAmount'] = $cr_amnt;
			$param['Closing'] = $closingamnt;
			$this->db->where('id', $samedayid);
			//echo $this->db->last_query(); die;
			if ($this->db->update('final_ledger', $param)) {
				//return true;
				$sql = "UPDATE final_ledger SET Closing = Closing + " . $amount . " WHERE Date > '" . date('Y-m-d', strtotime($date)) . "'";
				$this->db->query($sql);
			}
		} else {
			/*$otherday = $this->ledger_final_before_same_date_exist($partyid,$date); // this for last record.. yes
					 //echo '<pre>'; print_r($otherday);///echo 'tt'; echo '</pre>'; die;
					 $cr_amnt = $otherday['Closing'];
					 $closingamnt = $otherday['Closing']+$amount;
					 $samedayid = $otherday['id'];	
					 //$param['PartyId']=$partyid;
					 $param['Date']=date('Y-m-d',strtotime($date));
				 $param['CrAmount']=$cr_amnt;
				 $param['Closing']=$closingamnt;
				 
				$this->db->where('id',$samedayid);
				//print_r( $param); die;
				 if($this->db->update('final_ledger',$param)){
					 //return true;
				 //	echo $this->db->last_query();
					  $sql="UPDATE final_ledger SET Closing = Closing + ".$amount." WHERE Date > '".date('Y-m-d',strtotime($date))."'";    
			 //echo $sql; die;
			 $this->db->query($sql);
				 }*/
		}
		//$thisrecord = 
	}

	/* function to update further records after a date*/
	function updatefurtherrecords($party_id, $date, $amount)
	{
		$param['PartyId'] = $party_id;
		$data = $this->ledger_final_getfurtherecord($partyid, $date);
		//$param['Closing']=$amount; //UPDATE user SET points = points + 1 WHERE id = 42
	}

	/*function to get closing of the date and party id passed*/
	function ledger_final_getfurtherecord($partyid, $date) {}

	/*function to check final same date ledger exist */
	function ledger_final_same_date_exist($party_id, $date)
	{
		return $this->db->order_by('id', 'desc')->limit(1, 0)->get_where('final_ledger', array('PartyId' => $party_id, 'Date' => date('Y-m-d', strtotime($date))))->row_array();
		// echo $this->db->last_query();
	}

	/*function to check final very early ledger exist*/
	function ledger_final_before_same_date_exist($party_id, $date)
	{
		return $this->db->order_by('id', 'desc')->limit(1, 0)->get_where('final_ledger', array('PartyId' => $party_id, 'Date<' => date('Y-m-d', strtotime($date))))->row_array();
		//echo $this->db->last_query();
	}
	function view_transaction_filter($data)
	{ //echo '<pre>'; print_r($data);die;
		//$data['created_by'] = $this->session->userdata['id'];
		$this->db->select('tbl_master_transaction.id,tbl_staff.staff_name,tbl_shift.open_date,tbl_shift.super_admin,tbl_shift.data_entry_operator,tbl_master_transaction.t_date,tbl_master_transaction.total_number_amount,tbl_master_transaction.created_date, tbl_master_transaction.party_id,tbl_shift.shift_name as shift_name,tbl_shift.id as shift_id,tbl_ledger.ledger_name,tbl_trans_numbers.createddate,tbl_trans_numbers.modifieddate,tbl_trans_numbers.trnno,tbl_trans_numbers.trn_amt');
		$this->db->from('tbl_master_transaction');

		// Aggregate number rows first so each master transaction is returned once.
		$this->db->join(
			'(SELECT master_id,
				GROUP_CONCAT(number ORDER BY id) AS trnno,
				GROUP_CONCAT(amount ORDER BY id) AS trn_amt,
				MAX(created_date) AS createddate,
				MAX(modified_date) AS modifieddate
			 FROM tbl_trans_numbers
			 GROUP BY master_id) AS tbl_trans_numbers',
			'tbl_trans_numbers.master_id = tbl_master_transaction.id',
			'LEFT',
			FALSE
		);
		$this->db->join('tbl_ledger', 'tbl_ledger.id = tbl_master_transaction.party_id', 'FULL OUTER JOIN');
		$this->db->join('tbl_agent', 'tbl_ledger.agent_id = tbl_agent.id', 'LEFT');
		$this->db->join('tbl_staff', 'tbl_staff.id = tbl_master_transaction.created_by', 'LEFT');
		if ($this->session->userdata['role'] == 'Master') {
			//echo '<pre>'; print_r($data); echo '</pre>'; die;
			// foreach($data['created_by'] as $val){
			// 	$this->db->or_where('tbl_master_transaction.created_by',$val);
			// 	$this->db->where('tbl_staff.updated_by',$this->session->userdata['id']);
			// 	$this->db->where('tbl_staff.id',$val);
			// }
			$this->db->join('user_shift_timings', 'user_shift_timings.id = tbl_master_transaction.shift_id', 'FULL OUTER JOIN');
			$this->db->join('tbl_shift', 'tbl_shift.id = user_shift_timings.shift_id', 'FULL OUTER JOIN');
			$this->db->where('tbl_master_transaction.master_id', $this->session->userdata['id']);
		} else if ($this->session->userdata['role'] == 'Super Admin') {
			$this->db->join('user_shift_timings', 'user_shift_timings.id = tbl_master_transaction.shift_id', 'FULL OUTER JOIN');
			$this->db->join('tbl_shift', 'tbl_shift.id = user_shift_timings.shift_id', 'FULL OUTER JOIN');
			$this->db->or_where('tbl_ledger.is_master', '1');
			//$this->db->group_by("tbl_master_transaction.party_id");
			$this->db->where('(tbl_master_transaction.party_id, tbl_master_transaction.id) IN (SELECT tbl_master_transaction.party_id, MAX(tbl_master_transaction.id) FROM tbl_master_transaction GROUP BY tbl_master_transaction.party_id,tbl_master_transaction.shift_id)', NULL, FALSE);
			//$this->db->limit(1); 
		} else {
			//$this->db->join('tbl_shift', 'tbl_shift.id = tbl_master_transaction.shift_id','FULL OUTER JOIN');
			$this->db->join('user_shift_timings', 'user_shift_timings.id = tbl_master_transaction.shift_id', 'FULL OUTER JOIN');
			$this->db->join('tbl_shift', 'tbl_shift.id = user_shift_timings.shift_id', 'FULL OUTER JOIN');
			$data['created_by'] = (!empty($data['created_by'])) ? $data['created_by'] : $this->session->userdata['id'];
			$this->db->where('tbl_master_transaction.created_by', $data['created_by']);
		}




		if (isset($data['shift_name']) && !empty($data['shift_name'])) {
			$this->db->where('tbl_shift.id', $data['shift_name']);
		}
		if (isset($data['search_party']) && !empty($data['search_party'])) {
			$this->db->where('tbl_ledger.id', $data['search_party']);
		}
		/*if(isset($data['fromdate'])&& !empty($data['fromdate'])){$this->db->where('tbl_master_transaction.t_date >=',date('Y-m-d',strtotime($data['fromdate'])));
	}*/
		if (isset($data['todate']) && !empty($data['todate'])) {
			$this->db->where('tbl_master_transaction.t_date like ', '%' . date('Y-m-d', strtotime($data['todate'])) . '%');
		}
		//$this->db->where('tbl_master_transaction.t_date',date('Y-m-d',time()));
		$this->db->order_by("tbl_master_transaction.id", "desc");
		//$this->db->limit('10', '0');		
		//$this->db->order_by('id', 'desc');
		if (isset($params) && !empty($params)) {
			$this->db->limit($params['limit'], $params['offset']);
		}
		$query = $this->db->get();
		//echo '<pre>';echo $this->db->last_query(); die;
		return $query->result_array();
	}

	function view_transaction_filter_admin($data)
	{ //die;
		//$data['created_by'] = $this->session->userdata['id'];
		//$this->db->select('tbl_master_transaction.id,tbl_staff.staff_name,tbl_shift.open_date,tbl_shift.super_admin,tbl_shift.data_entry_operator,tbl_master_transaction.t_date,tbl_master_transaction.total_number_amount,tbl_master_transaction.created_date, tbl_master_transaction.party_id,tbl_shift.shift_name as shift_name,tbl_shift.id as shift_id,tbl_ledger.ledger_name,tbl_trans_numbers.created_date as createddate,tbl_trans_numbers.modified_date as modifieddate,tbl_trans_numbers.number as trnno,tbl_trans_numbers.amount as trn_amt');
		$this->db->select('tbl_master_transaction.id,tbl_master_transaction.show_to_admin, tbl_master_transaction.t_date,tbl_master_transaction.total_number_amount as ttamnt,tbl_shift.id as shiftid,tbl_ledger.id as ledgerid,tbl_trans_numbers.created_date as createddate,tbl_ledger.ledger_name,tbl_ledger.dara_commision as dcomm,
				tbl_ledger.hissa as dhissa,tbl_ledger.tppercentage as tppercentage,tbl_shift.shift_name as shift_name, tbl_shift.open_date,tbl_shift.super_admin,tbl_trans_numbers.number as trnno,tbl_trans_numbers.modified_date as modifieddate,tbl_trans_numbers.amount as trn_amt');
		$this->db->from('tbl_master_transaction');

		$this->db->join('tbl_trans_numbers', 'tbl_trans_numbers.master_id = tbl_master_transaction.id', 'FULL OUTER JOIN');

		$this->db->join('tbl_staff', 'tbl_staff.id = tbl_master_transaction.created_by', 'LEFT');

		$this->db->join('tbl_ledger', 'tbl_ledger.id = tbl_master_transaction.master_id', 'FULL OUTER JOIN');

		$this->db->or_where('tbl_ledger.is_master', '1');
		//$this->db->group_by("tbl_master_transaction.party_id");
		$this->db->join('user_shift_timings', 'user_shift_timings.id = tbl_master_transaction.shift_id', 'FULL OUTER JOIN');
		$this->db->join('tbl_shift', 'tbl_shift.id =user_shift_timings.shift_id', 'FULL OUTER JOIN');
		$this->db->where('(tbl_master_transaction.party_id, tbl_master_transaction.id) IN (SELECT tbl_master_transaction.party_id, MAX(tbl_master_transaction.id) FROM tbl_master_transaction GROUP BY tbl_master_transaction.party_id,tbl_master_transaction.shift_id)', NULL, FALSE);
		//$this->db->limit(1); 
		$this->db->where('tbl_master_transaction.show_to_admin', '1');




		if (isset($data['shift_name']) && !empty($data['shift_name'])) {
			$this->db->where('tbl_shift.id', $data['shift_name']);
		}
		if (isset($data['search_party']) && !empty($data['search_party'])) {
			$this->db->where('tbl_ledger.id', $data['search_party']);
		}
		/*if(isset($data['fromdate'])&& !empty($data['fromdate'])){$this->db->where('tbl_master_transaction.t_date >=',date('Y-m-d',strtotime($data['fromdate'])));
		}*/
		if (isset($data['todate']) && !empty($data['todate'])) {
			$this->db->where('tbl_master_transaction.t_date like ', '%' . date('Y-m-d', strtotime($data['todate'])) . '%');
		}
		//$this->db->where('tbl_master_transaction.t_date',date('Y-m-d',time()));
		$this->db->order_by("tbl_master_transaction.id", "desc");
		//$this->db->limit('10', '0');		
		//$this->db->order_by('id', 'desc');
		if (isset($params) && !empty($params)) {
			$this->db->limit($params['limit'], $params['offset']);
		}
		$query = $this->db->get();
		//echo $this->db->last_query(); die;
		return $query->result_array();
	}
	function get_custom_transactions_total_shift_party($pid, $date, $partyid)
	{
		$this->db->select('tbl_master_transaction.id,tbl_master_transaction.t_date,tbl_master_transaction.total_number_amount as ttamnt,tbl_shift.id as shiftid,tbl_ledger.id as ledgerid,tbl_ledger.ledger_name,tbl_ledger.dara_commision as dcomm,
				tbl_ledger.hissa as dhissa,tbl_ledger.tppercentage as tppercentage, tbl_trans_numbers.number as trnno,tbl_trans_numbers.amount as trn_amt');
		//$this->db->select('tbl_trans_cross.ander,tbl_trans_cross.bahar,tbl_trans_cross.cross_count,tbl_trans_cross.amount as trncrs_amt');
		//$this->db->select('tbl_random_f4.number,tbl_random_f4.amount,tbl_random_f4.total_amount as trnf4_tamt');
		//$this->db->select('tbl_trans_fromto.fromto_from,tbl_trans_fromto.fromto_to,tbl_trans_fromto.fromto_amount,tbl_trans_fromto.all_commission');
		//$this->db->select('tbl_random_f8.dara_f8,tbl_random_f8.dara_amount_f8,tbl_random_f8.akhar_bahar_f8,tbl_random_f8.amount_akahr_bahar_f8,tbl_random_f8.akahr_andar_f8,tbl_random_f8.amount_akahr_andar_f8,tbl_random_f8.total_amount ');
		$this->db->from('tbl_master_transaction');
		$this->db->join('tbl_trans_numbers', 'tbl_trans_numbers.master_id = tbl_master_transaction.id', 'FULL OUTER JOIN');
		//$this->db->join('tbl_random_f4', 'tbl_random_f4.trns_id = tbl_master_transaction.id','FULL OUTER JOIN');	
		//$this->db->join('tbl_random_f8', 'tbl_random_f8.master_id = tbl_master_transaction.id','FULL OUTER JOIN');	

		//$this->db->join('tbl_trans_cross', 'tbl_trans_cross.master_id = tbl_master_transaction.id','FULL OUTER JOIN');
		$this->db->join('tbl_ledger', 'tbl_ledger.id = tbl_master_transaction.party_id', 'FULL OUTER JOIN');
		$this->db->join('user_shift_timings', 'user_shift_timings.id = tbl_master_transaction.shift_id', 'FULL OUTER JOIN');
		$this->db->join('tbl_shift', 'tbl_shift.id = user_shift_timings.shift_id', 'FULL OUTER JOIN');
		//$this->db->join('tbl_shift', 'tbl_shift.id = tbl_master_transaction.shift_id','FULL OUTER JOIN');
		//$this->db->join('tbl_trans_fromto', 'tbl_trans_fromto.master_id = tbl_master_transaction.id','FULL OUTER JOIN');	
		$this->db->where('tbl_master_transaction.party_id', $partyid);
		$this->db->where('tbl_master_transaction.shift_id', $pid);
		$this->db->where('tbl_master_transaction.t_date', date('Y-m-d', strtotime($date)) . ' 00:00:00');
		$this->db->order_by("tbl_master_transaction.id", "desc");
		//$this->db->limit('10', '0');		
		//$this->db->order_by('id', 'desc');
		if (isset($params) && !empty($params)) {
			$this->db->limit($params['limit'], $params['offset']);
		}
		$query = $this->db->get();
		//echo $this->db->last_query(); die;
		return $query->result_array();
	}
	function view_transaction_filter_hisab($data)
	{ //die;
		$data['created_by'] = $this->session->userdata['id'];
		$this->db->select('tbl_master_transaction.id,tbl_staff.staff_name,tbl_shift.open_date,tbl_shift.super_admin,tbl_shift.data_entry_operator,tbl_master_transaction.t_date,tbl_master_transaction.total_number_amount,tbl_master_transaction.created_date, tbl_master_transaction.party_id,tbl_shift.shift_name as shift_name,tbl_shift.id as shift_id,tbl_ledger.ledger_name,tbl_trans_numbers.created_date as createddate,tbl_trans_numbers.modified_date as modifieddate,tbl_trans_numbers.number as trnno,tbl_trans_numbers.amount as trn_amt');
		$this->db->from('tbl_master_transaction');
		$this->db->join('tbl_shift', 'tbl_shift.id = tbl_master_transaction.shift_id', 'FULL OUTER JOIN');
		$this->db->join('tbl_trans_numbers', 'tbl_trans_numbers.master_id = tbl_master_transaction.id', 'FULL OUTER JOIN');
		$this->db->join('tbl_ledger', 'tbl_ledger.id = tbl_master_transaction.party_id', 'FULL OUTER JOIN');
		$this->db->join('tbl_agent', 'tbl_ledger.agent_id = tbl_agent.id', 'LEFT');
		$this->db->join('tbl_staff', 'tbl_staff.id = tbl_master_transaction.created_by', 'LEFT');
		// if($data['created_by']!='1'){
		// $this->db->where('tbl_master_transaction.created_by',$this->session->userid);
		// }
		if (isset($data['shift_name']) && !empty($data['shift_name'])) {
			$this->db->where('tbl_shift.id', $data['shift_name']);
		}
		if (isset($data['search_party']) && !empty($data['search_party'])) {
			$this->db->where('tbl_ledger.id', $data['search_party']);
		}
		/*if(isset($data['fromdate'])&& !empty($data['fromdate'])){$this->db->where('tbl_master_transaction.t_date >=',date('Y-m-d',strtotime($data['fromdate'])));
		}*/
		if (isset($data['todate']) && !empty($data['todate'])) {
			$this->db->where('tbl_master_transaction.t_date like ', '%' . date('Y-m-d', strtotime($data['todate'])) . '%');
		}
		if ($this->session->userdata['role'] == 'Master') {
			//echo '<pre>'; print_r($data); echo '</pre>'; die;
			// foreach($data['created_by'] as $val){
			// 	$this->db->or_where('tbl_master_transaction.created_by',$val);
			// 	$this->db->where('tbl_staff.updated_by',$this->session->userdata['id']);
			// 	$this->db->where('tbl_staff.id',$val);
			// }
			$this->db->where('tbl_master_transaction.master_id', $this->session->userdata['id']);
			$this->db->group_by("tbl_shift.id");
		} else if ($this->session->userdata['role'] == 'Super Admin') {
			$this->db->or_where('tbl_ledger.is_master', '1');
			//$this->db->group_by("tbl_master_transaction.party_id");
			$this->db->where('(tbl_master_transaction.party_id, tbl_master_transaction.id) IN (SELECT tbl_master_transaction.party_id, MAX(tbl_master_transaction.id) FROM tbl_master_transaction GROUP BY tbl_master_transaction.party_id)', NULL, FALSE);
			//$this->db->limit(1); 
		} else {
			$data['created_by'] = (!empty($data['created_by'])) ? $data['created_by'] : $this->session->userdata['id'];
			$this->db->where('tbl_master_transaction.created_by', $data['created_by']);
		}
		//$this->db->where('tbl_master_transaction.t_date',date('Y-m-d',time()));
		$this->db->order_by("tbl_master_transaction.id", "desc");
		//$this->db->limit('10', '0');		
		//$this->db->order_by('id', 'desc');
		if (isset($params) && !empty($params)) {
			$this->db->limit($params['limit'], $params['offset']);
		}
		$query = $this->db->get();
		//echo $this->db->last_query(); die;
		return $query->result_array();
	}
	/*function to check final same date ledger exist */
	function view_transaction_filter_master($data)
	{ //die;
		//echo '<pre>'; print_r($data); echo '</pre>'; die;
		//$data['created_by'] = $this->session->userdata['id'];
		if ($this->session->userdata['role'] == 'Master') {

			$this->db->select('tbl_master_transaction.id,tbl_staff.staff_name,tbl_shift.open_date,tbl_shift.super_admin,tbl_shift.data_entry_operator,tbl_master_transaction.t_date,tbl_master_transaction.total_number_amount,tbl_master_transaction.created_date, tbl_master_transaction.party_id,tbl_shift.shift_name as shift_name,tbl_shift.id as shift_id,tbl_ledger.ledger_name,tbl_trans_numbers.created_date as createddate,tbl_trans_numbers.modified_date as modifieddate,tbl_trans_numbers.number as trnno,tbl_trans_numbers.amount as trn_amt');
			$this->db->from('tbl_master_transaction');
			$this->db->join('tbl_shift', 'tbl_shift.id = tbl_master_transaction.shift_id', 'FULL OUTER JOIN');
			$this->db->join('tbl_trans_numbers', 'tbl_trans_numbers.master_id = tbl_master_transaction.id', 'FULL OUTER JOIN');
			$this->db->join('tbl_ledger', 'tbl_ledger.id = tbl_master_transaction.party_id', 'FULL OUTER JOIN');
			$this->db->join('tbl_agent', 'tbl_ledger.agent_id = tbl_agent.id', 'LEFT');
			$this->db->join('tbl_staff', 'tbl_staff.id = tbl_master_transaction.created_by', 'LEFT');
			if ($data['created_by'] != '1') {
				$this->db->where('tbl_master_transaction.created_by', $data['created_by']);
			} else {
				$this->db->where('tbl_master_transaction.party_id', $data['created_by']);
			}
			if (isset($data['shift_name']) && !empty($data['shift_name'])) {
				$this->db->where('tbl_shift.id', $data['shift_name']);
			}
			if (isset($data['search_party']) && !empty($data['search_party'])) {
				$this->db->where('tbl_ledger.updated_by', $data['search_party']);
			}
			/*if(isset($data['fromdate'])&& !empty($data['fromdate'])){$this->db->where('tbl_master_transaction.t_date >=',date('Y-m-d',strtotime($data['fromdate'])));
		}*/
			if (isset($data['todate']) && !empty($data['todate'])) {
				$this->db->where('tbl_master_transaction.t_date like ', '%' . date('Y-m-d', strtotime($data['todate'])) . '%');
			}
			//$this->db->where('tbl_master_transaction.t_date',date('Y-m-d',time()));
			$this->db->order_by("tbl_master_transaction.id", "desc");
			//$this->db->limit('10', '0');		
			//$this->db->order_by('id', 'desc');
			if (isset($params) && !empty($params)) {
				$this->db->limit($params['limit'], $params['offset']);
			}
			$query = $this->db->get();
			//echo $this->db->last_query(); die;
			return $query->result_array();
		} else {
			$this->db->select('tbl_master_transaction.id,tbl_staff.staff_name,tbl_shift.open_date,tbl_shift.super_admin,tbl_shift.data_entry_operator,tbl_master_transaction.t_date,tbl_master_transaction.total_number_amount,tbl_master_transaction.created_date, tbl_master_transaction.party_id,tbl_shift.shift_name as shift_name,tbl_shift.id as shift_id,tbl_ledger.ledger_name,tbl_trans_numbers.created_date as createddate,tbl_trans_numbers.modified_date as modifieddate,tbl_trans_numbers.number as trnno,tbl_trans_numbers.amount as trn_amt');
			$this->db->from('tbl_master_transaction');
			$this->db->join('tbl_shift', 'tbl_shift.id = tbl_master_transaction.shift_id', 'FULL OUTER JOIN');
			$this->db->join('tbl_trans_numbers', 'tbl_trans_numbers.master_id = tbl_master_transaction.id', 'FULL OUTER JOIN');
			$this->db->join('tbl_ledger', 'tbl_ledger.id = tbl_master_transaction.party_id', 'FULL OUTER JOIN');
			$this->db->join('tbl_agent', 'tbl_ledger.agent_id = tbl_agent.id', 'LEFT');
			$this->db->join('tbl_staff', 'tbl_staff.id = tbl_master_transaction.created_by', 'LEFT');
			if ($data['created_by'] != '1') {
				$this->db->where('tbl_master_transaction.created_by', $data['created_by']);
			} else {
				$this->db->where('tbl_ledger.updated_by', $data['created_by']);
			}
			if (isset($data['shift_name']) && !empty($data['shift_name'])) {
				$this->db->where('tbl_shift.id', $data['shift_name']);
			}
			if (isset($data['search_party']) && !empty($data['search_party'])) {
				$this->db->where('tbl_ledger.id', $data['search_party']);
			}
			/*if(isset($data['fromdate'])&& !empty($data['fromdate'])){$this->db->where('tbl_master_transaction.t_date >=',date('Y-m-d',strtotime($data['fromdate'])));
		}*/
			if (isset($data['todate']) && !empty($data['todate'])) {
				$this->db->where('tbl_master_transaction.t_date like ', '%' . date('Y-m-d', strtotime($data['todate'])) . '%');
			}
			//$this->db->where('tbl_master_transaction.t_date',date('Y-m-d',time()));
			$this->db->order_by("tbl_master_transaction.id", "desc");
			//$this->db->limit('10', '0');		
			//$this->db->order_by('id', 'desc');
			if (isset($params) && !empty($params)) {
				$this->db->limit($params['limit'], $params['offset']);
			}
			$query = $this->db->get();
			//echo $this->db->last_query(); die;
			return $query->result_array();
		}
	}

	function view_transaction_filter_calculate($data)
	{ //die;
		$data['created_by'] = $this->session->userdata['id'];
		$this->db->select('tbl_master_transaction.id,tbl_staff.staff_name,tbl_shift.open_date,tbl_shift.super_admin,tbl_shift.data_entry_operator,tbl_master_transaction.t_date,tbl_master_transaction.total_number_amount,tbl_master_transaction.created_date, tbl_master_transaction.party_id,tbl_shift.shift_name as shift_name,tbl_shift.id as shift_id,tbl_ledger.ledger_name,tbl_trans_numbers.created_date as createddate,tbl_trans_numbers.modified_date as modifieddate,tbl_trans_numbers.number as trnno,tbl_trans_numbers.amount as trn_amt');
		$this->db->from('tbl_master_transaction');
		$this->db->join('tbl_shift', 'tbl_shift.id = tbl_master_transaction.shift_id', 'FULL OUTER JOIN');
		$this->db->join('tbl_trans_numbers', 'tbl_trans_numbers.master_id = tbl_master_transaction.id', 'FULL OUTER JOIN');
		$this->db->join('tbl_ledger', 'tbl_ledger.id = tbl_master_transaction.party_id', 'FULL OUTER JOIN');
		$this->db->join('tbl_agent', 'tbl_ledger.agent_id = tbl_agent.id', 'LEFT');
		$this->db->join('tbl_staff', 'tbl_staff.id = tbl_master_transaction.created_by', 'LEFT');
		/* if($data['created_by']!='1'){
			  $this->db->where('tbl_master_transaction.created_by',$this->session->userid);
			  } */
		if (isset($data['shift_name']) && !empty($data['shift_name'])) {
			$this->db->where('tbl_shift.id', $data['shift_name']);
		}
		if (isset($data['search_party']) && !empty($data['search_party'])) {
			$this->db->where('tbl_ledger.id', $data['search_party']);
		}
		/*if(isset($data['fromdate'])&& !empty($data['fromdate'])){$this->db->where('tbl_master_transaction.t_date >=',date('Y-m-d',strtotime($data['fromdate'])));
		}*/
		if (isset($data['todate']) && !empty($data['todate'])) {
			$this->db->where('tbl_master_transaction.t_date =', date('Y-m-d', strtotime($data['todate'])));
		}
		//$this->db->where('tbl_master_transaction.t_date',date('Y-m-d',time()));
		$this->db->order_by("tbl_master_transaction.id", "desc");
		//$this->db->limit('10', '0');		
		//$this->db->order_by('id', 'desc');
		if (isset($params) && !empty($params)) {
			$this->db->limit($params['limit'], $params['offset']);
		}
		$query = $this->db->get();
		//echo $this->db->last_query(); die;
		//echo '<pre>'; print_r($query->result_array()); die;
		return $query->result_array();
	}

	function calctotalresult($id)
	{
		$data = $this->db->get_where('Tb_Date_shift_party_entry', array('id' => $id))->row_array();
		//echo '<pre>';print_r($data); die;
		$tdaraamount = $data[''];
	}
	function thirdpartydetails($party_id)
	{
		return $this->db->get_where('tbl_ledger', array('id' => $party_id))->row_array();
		//echo $this->db->last_query(); die;
	}
	function tnumberdetails($shift_id, $party_id, $date)
	{
		return $this->db->get_where('Tb_Date_shift_party_entry', array('ShiftId' => $shift_id, 'PartyId' => $party_id, 'Date' => $date))->row_array();
		//echo $this->db->last_query(); die;
	}
	/*
	 * function to add new tbl_master_transaction
	 */
	function update_tbl_only_transaction($master_id, $params)
	{ //$last_id = $this->db->insert_id(); 
		//print_r($params); print_r($last_id); die;
		$param['master_id'] = $master_id;
		$last_id = $params['last_id'];
		$param['number'] = $params['number'];
		$param['Amount'] = $params['amount'];
		unset($params['last_id']);
		unset($params['shift']);
		unset($params['party']);
		unset($params['date']);
		$this->db->where('id', $last_id);
		if ($this->db->update('tbl_trans_add', $params))
			echo json_encode($params);
		//die;

	}
	/*
	 * function to update tbl_transactions
	 */
	function update_tbl_transactions($id, $params)
	{
		$this->db->where('id', $id);
		return $this->db->update('tbl_master_transactions', $params);
	}

	/*
	 * function to update tbl_onlt_tb_trnsctions
	 */
	function update_Tb_Date_shift_party_entry($id, $params)
	{

		$this->db->where('id', $id);
		$this->db->update('Tb_Date_shift_party_entry', $params);
		return $id;
	}

	/*
	 * function to delete tbl_transactions
	 */
	function delete_tbl_transactions($id)
	{
		return $this->db->delete('tbl_master_transaction', array('id' => $id));
	}
	/*
	 * function to delete tbl_transactions
	 */
	function delete_hisab_transaction($odata, $tdata, $id)
	{
		$shift_id = $tdata['shift_id'];
		$party_id = $tdata['party_id'];
		//echo '<pre>'; print_r($odata);print_r($tdata); die;
		$data['Total_Number_amount'] = $odata[0]['Total_Number_amount'] - $tdata['total_number_amount'];
		$data['Total_Akhar_amount'] = $odata[0]['Total_Akhar_amount'] - $tdata['total_akhar_amount'];
		$data['Total_amount'] = $odata[0]['Total_amount'] - ($tdata['total_number_amount'] + $tdata['total_akhar_amount']);
		$t_date = date('Y-m-d', strtotime($tdata['t_date']));
		$del1 = $this->db->delete('tbl_master_transaction', array('id' => $id));
		$del2 = $this->db->delete('tbl_trans_numbers', array('master_id' => $id));
		$this->db->where('ShiftId', $shift_id);
		$this->db->where('PartyId', $party_id);
		$this->db->where('Date', date('d-m-Y', strtotime($t_date)));
		// Print the compiled update SQL query
		//echo $this->db->set($data)->get_compiled_update('Tb_Date_shift_party_entry'); die;
		//$params = ['status'=>'0'];
		//$del3 = $this->db->delete('Tb_Date_shift_party_entry', array('ShiftId'=> $shift_id,'PartyId'=> $party_id,'Date'=> date('d-m-Y',strtotime($t_date))));
		//$this->db->update('Tb_Date_shift_party_entry', $params);

		// Apply the conditions for the update
		//$this->db->where($params);
		// Update the table with the provided data
		if (!$this->db->update('Tb_Date_shift_party_entry', $data)) {
			$error = $this->db->error(); // Has keys 'code' and 'message'
			print_r($error); // Display the error
			echo 'Update failed';
		}
		if ($del1 && $del2) {
			return true;
		} else {
			return false;
		}
		//return $this->db->delete('Tb_Date_shift_party_entry',array('ShiftId'=>$shift_id,'PartyId'=>$party_id,'Date'=>date('d-m-Y',strtotime($t_date))));
		//echo $this->db->last_query(); die;
	}
}
