<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 defined('BASEPATH') OR exit('No direct script access allowed');
class Users_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user by username and password
     */
   public function login($username, $password)
    {
        $this->db->where('user_name', $username);
        $this->db->where('password', md5($password));
        $this->db->where('is_active', 1);
        $query = $this->db->get('tbl_user_login'); 

        if($query->num_rows() == 1) {
			$user = $query->row();
			
			$role = $this->get_role_name($user->user_role);
			//echo '<pre>'; print_r($role); echo '</pre>'; die;
			$logindata = [
             'userid' => $user->id,
			 'role'      => $role[0]['role_name'],
             'name'   => $user->user_name
         ];
		 $this->session
              ->set_userdata($logindata);
			return $query->row();
        }
		else{
		$this->db->where('user_name', $username);
        $this->db->where('password', $password);
        $this->db->where('is_active', 1);
        $query = $this->db->get('tbl_admin'); 

        if($query->num_rows() == 1) {
			$user = $query->row();
			
			$role = $this->get_role_name($user->user_role);
			//echo '<pre>'; print_r($role); echo '</pre>'; die;
			$logindata = [
             'userid' => $user->id,
			 'role'      => $role[0]['role_name'],
             'name'   => $user->user_name
         ];
		 $this->session
              ->set_userdata($logindata);
			return $query->row();
		}
		}

        return false;
    }
    public function is_username_taken($username, $user_id)
{
    $this->db->where('username', $username);
    $this->db->where('id !=', $user_id); // Exclude the current user's ID
    $query = $this->db->get('tbl_ledger');

    return $query->num_rows() > 0; // Return true if a match is found
}

         public function master_login($username, $password)
    {
        $this->db->where('username', $username);
        $this->db->where('password', $password);
        $this->db->where('status', 1);
        $query = $this->db->get('tbl_ledger'); 
        
        if($query->num_rows() == 1) {
			$user = $query->row();
			
			$role = 'Master';
			//echo '<pre>'; print_r($role); echo '</pre>'; die;
			$logindata = [
             'userid' => $user->id,
			 'role'      => (empty($user->is_master))?'Staff':'Master',
             'name'   => $user->username
         ];
         //echo '<pre>'; print_r($logindata); echo '</pre>'; die;
		 $this->session
              ->set_userdata($logindata);
			return $query->row();
        }

        return false;
    }

    public function staff_login($username, $password)
    {
        $this->db->where('user_name', $username);
        $this->db->where('password', $password);
        $this->db->where('is_active', 1);
        $query = $this->db->get('tbl_staff'); 
        
        if($query->num_rows() == 1) {
			$user = $query->row();
			
			$role = 'Staff';
			//echo '<pre>'; print_r($role); echo '</pre>'; die;
			$logindata = [
             'userid' => $user->id,
			 'role'      => 'Staff',
             'name'   => $user->user_name
         ];
         //echo '<pre>'; print_r($logindata); echo '</pre>'; die;
		 $this->session
              ->set_userdata($logindata);
			return $query->row();
        }
		// else{
		// $this->db->where('user_name', $username);
        // $this->db->where('password', $password);
        // $this->db->where('is_active', 1);
        // $query = $this->db->get('tbl_admin'); 

        // if($query->num_rows() == 1) {
		// 	$user = $query->row();
			
		// 	$role = $this->get_role_name($user->user_role);
		// 	//echo '<pre>'; print_r($role); echo '</pre>'; die;
		// 	$logindata = [
        //      'userid' => $user->id,
		// 	 'role'      => $role[0]['role_name'],
        //      'name'   => $user->user_name
        //  ];
		//  $this->session
        //       ->set_userdata($logindata);
		// 	return $query->row();
		// }
		// }

        return false;
    }
    function get_role_name($role_id='')
    { 
             return $this->db->get_where('tbl_user_roles',array('id'=>$role_id))->result_array();
			 //echo $this->db->last_query(); die;
      
    }
}
