<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
      parent::__construct();
	  $this->load->library('session');
        $this->load->helper('form');
        $this->load->library('form_validation');
        $this->load->model('users_model');
		$this->load->model('common_model');
		$this->load->model('tbl_ledger_model');
        $this->load->model('Tbl_transactions_model');
        $this->load->model('Tbl_shift_model');
        $this->load->model('CoinModel');
        $this->load->model('Tbl_openno_model');
    }
private function logged_in()
    {
        if( ! $this->session->userdata('authenticated')){
            redirect('users/login');
        } 
    }
	
	public function index()
    { 
        $data['title'] = "Login";
        
        $this->form_validation->set_rules('user_name', 'text', 'trim|required');
        $this->form_validation->set_rules('password', 'password', 'required');
        
        $this->form_validation->set_error_delimiters('<div class="error">', '</div>');
        
        if($this->form_validation->run() == false){
            $data['_view'] = 'login';
        $this->load->view('layouts/main_login',$data);
        } 
        else {
            $email = $this->security->xss_clean($this->input->post('user_name'));
            $password = $this->security->xss_clean($this->input->post('password'));
            
            $user = $this->users_model->login($email, $password);
            
            if($user){
                //print_r($user); die;
                if($user->user_name !='Webadmin'){
                $balance = $this->CoinModel->getUserBalance($user->id);
                $userdata = array(
                    'id' => $user->id,
                    'first_name' => $user->user_name,
                    'updated_by' => $user->updated_by,
                    'coin_balance' => $balance,
                    'authenticated' => TRUE
                );
            }
            else{
                $userdata = array(
                    'id' => $user->id,
                    'first_name' => $user->user_name,
                  
                    'authenticated' => TRUE
                );
            }
                
                $this->session->set_userdata($userdata);
                
                redirect('dashboard');
            }

            $user = $this->users_model->staff_login($email, $password);
            
            if($user){
                $userdata = array(
                    'id' => $user->id,
                    'first_name' => $user->user_name,
                    'updated_by' => $user->updated_by,
                    'authenticated' => TRUE
                );
                
                $this->session->set_userdata($userdata);
                
                redirect('dashboard_staff');
            }

           // else {
                $this->session->set_flashdata('message', 'Account Deactivated. Please contact administrator.');
                 $data['_view'] = 'login';
        $this->load->view('layouts/main_login',$data);
           //}
        }
    }

    public function master_login()
    {
        $data['title'] = "Login";
        
        $this->form_validation->set_rules('user_name', 'text', 'trim|required');
        $this->form_validation->set_rules('password', 'password', 'required');
        
        $this->form_validation->set_error_delimiters('<div class="error">', '</div>');
        
        if($this->form_validation->run() == false){
            $data['_view'] = 'login';
        $this->load->view('layouts/main_login',$data);
        } 
        else {
            $email = $this->security->xss_clean($this->input->post('user_name'));
            $password = $this->security->xss_clean($this->input->post('password'));
            
            $user = $this->users_model->master_login($email, $password);
            
            if($user){
                $balance = $this->CoinModel->getUserBalance($user->id);
                $userdata = array(
                    'id' => $user->id,
                    'first_name' => $user->username,
                    'updated_by' => $user->id,
                    'coin_balance' => $balance,
                    'authenticated' => TRUE
                );
                
                $this->session->set_userdata($userdata);
                
                redirect('dashboard');
            }
            else {
                $this->session->set_flashdata('message', 'Account Deactivated. Please contact administrator.');
                 $data['_view'] = 'login';
        $this->load->view('layouts/main_login',$data);
            }
        }
    }

    public function staff_login()
    {
        $data['title'] = "Login";
        
        $this->form_validation->set_rules('user_name', 'text', 'trim|required');
        $this->form_validation->set_rules('password', 'password', 'required');
        
        $this->form_validation->set_error_delimiters('<div class="error">', '</div>');
        
        if($this->form_validation->run() == false){
            $data['_view'] = 'login';
        $this->load->view('layouts/main_login',$data);
        } 
        else {
            $email = $this->security->xss_clean($this->input->post('user_name'));
            $password = $this->security->xss_clean($this->input->post('password'));
            
            $user = $this->users_model->staff_login($email, $password);
            
            if($user){
                $userdata = array(
                    'id' => $user->id,
                    'first_name' => $user->user_name,
                    'updated_by' => $user->updated_by,
                    'role' => 'Staff',
                    'authenticated' => TRUE
                );
                
                $this->session->set_userdata($userdata);
                
                redirect('dashboard');
                
            }
            else {
                $this->session->set_flashdata('message', 'Account Deactivated. Please contact administrator.');
                 $data['_view'] = 'login';
        $this->load->view('layouts/main_login',$data);
            }
        }
    }
    
    public function logout()
    {
        $this->session->sess_destroy();
        redirect('/');
    }
	
    function index1()
    { 
		$data['title'] = "Login";
		if($this->input->post('submit_login')=='login_submit')
		{
		$user_name=$this->input->post('user_name');
		$password=$this->input->post('password');
		$que=$this->db->query("select id from tbl_user_login where user_name='$user_name' and password=md5('$password')");
		$row = $que->num_rows();
		if(count($row)>0)
		{
		redirect('dashboard');
		}
		else
		{
		$data['error']="<h3 style='color:red'>Invalid userid or password !</h3>";
		}
		}
		
        $data['_view'] = 'login';
        $this->load->view('layouts/main_login',$data);
    }
	public function dashboard()
    {
		$data['ledger'] = $this->tbl_ledger_model->get_all_tbl_ledger_admin();
        $data['todate'] = date('Y-m-d', time());
			if ($this->session->userdata['id'] == 1) {
				$data['tbl_transactions'] = $this->Tbl_transactions_model->get_all_transactions_admin_may();
			} else {
				$data['tbl_transactions'] = $this->Tbl_transactions_model->view_transaction_filter($data);
			}
		//$data['shifts'] = $this->common_model->getallshift();
        
        $data['shifts'] = $this->Tbl_shift_model->get_all_tbl_shift($this->session->userdata['id']);
        $data['tbl_openno'] = $this->Tbl_openno_model->get_all_tbl_openno_admin_dashboard();
        if(isset($this->session->userdata['role']) && $this->session->userdata['role'] == 'Staff'){
            $data['_view'] = 'dashboardstaff';
            $this->load->view('layouts/mainold',$data);
        }
        else{
            $data['_view'] = 'dashboard';
            $this->load->view('layouts/main',$data);
        }
        
        
	}
	
	
}
