<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_kist extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_kist_model');
		$this->load->library('session');
    } 

    /*
     * Listing of tbl_kist
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tbl_kist/index?');
        $config['total_rows'] = $this->Tbl_kist_model->get_all_tbl_kist_count();
        $this->pagination->initialize($config);

        $data['tbl_kist'] = $this->Tbl_kist_model->get_all_tbl_kist($params);
        
        $data['_view'] = 'tbl_kist/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_kist
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('PartyId','PartyId','required|integer');
		$this->form_validation->set_rules('frdate','frdate','required');
		$this->form_validation->set_rules('todate','todate','required');
		$this->form_validation->set_rules('totalamt','totalamt','required');
		
		if($this->form_validation->run())     
        {   //echo '<pre>'; print_r($_POST); echo '</pre>'; die;
            $params = array(
				'PartyId' => $this->input->post('PartyId'),
				'frdate' => date('Y-m-d',strtotime($this->input->post('frdate'))),
				'todate' => date('Y-m-d',strtotime($this->input->post('todate'))),
				'totalamt' => $this->input->post('totalamt'),
				'days' => $this->input->post('days'),
				'kist' => $this->input->post('kist'),
            );
            
            $tbl_kist_id = $this->Tbl_kist_model->add_tbl_kist($params);
            redirect('kist');
        }
        else
        {
			$this->load->model('Tbl_ledger_model');
			$data['all_tbl_ledger'] = $this->Tbl_ledger_model->get_all_tbl_ledger_admin();
			//$data['all_tbl_ledger'] = $this->Tbl_ledger_model->get_all_tbl_ledger();
            $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tbl_kist/index?');
        $config['total_rows'] = $this->Tbl_kist_model->get_all_tbl_kist_count();
        $this->pagination->initialize($config);

        $data['tbl_kist'] = $this->Tbl_kist_model->get_all_tbl_kist_admin($params);
            $data['_view'] = 'tbl_kist/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_kist
     */
    function edit($id)
    {   
        // check if the tbl_kist exists before trying to edit it
        $data['tbl_kist'] = $this->Tbl_kist_model->get_tbl_kist($id);
       // echo '<pre>'; print_r($data['tbl_kist']); echo '</pre>'; //die;
        if(isset($data['tbl_kist']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('PartyId','PartyId','required|integer');
		$this->form_validation->set_rules('frdate','frdate','required');
		$this->form_validation->set_rules('todate','todate','required');
		$this->form_validation->set_rules('totalamt','totalamt','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
				'PartyId' => $this->input->post('PartyId'),
				'frdate' => date('Y-m-d',strtotime($this->input->post('frdate'))),
				'todate' => date('Y-m-d',strtotime($this->input->post('todate'))),
				'totalamt' => $this->input->post('totalamt'),
				'days' => $this->input->post('days'),
				'kist' => $this->input->post('kist'),
            );

                $this->Tbl_kist_model->update_tbl_kist($id,$params);            
                redirect('kist');
            }
            else
            {
				$this->load->model('Tbl_ledger_model');
				$data['all_tbl_ledger'] = $this->Tbl_ledger_model->get_all_tbl_ledger();
				$data['all_tbl_ledger'] = $this->Tbl_ledger_model->get_all_tbl_ledger();

                $data['_view'] = 'tbl_kist/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_kist you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_kist
     */
    function remove($id)
    {
        $tbl_kist = $this->Tbl_kist_model->get_tbl_kist($id);

        // check if the tbl_kist exists before trying to delete it
        if(isset($tbl_kist['id']))
        {
            $this->Tbl_kist_model->delete_tbl_kist($id);
            redirect('/kist');
        }
        else
            show_error('The tbl_kist you are trying to delete does not exist.');
    }
    
}
