<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_coin extends CI_Controller{
    public function __construct() {
        parent::__construct();
        $this->load->model('CoinModel');
        $this->load->library('session');
    }

    // View Allocation Page
    public function allocateCoins() {
        $role = $this->session->userdata('role'); // Fetch role from session

        if ($role === 'Super Admin') {
            $data['users'] = $this->CoinModel->getMasters(); // Get Masters for Super Admin
        } elseif ($role === 'Master') {
            $data['users'] = $this->CoinModel->getStaff(); // Get Staff for Master
        } else {
            show_error('Unauthorized access.', 403);
        }
       // Load the database library if not already loaded
$this->load->database();

$this->db->select('ct.id, ct.amount, ct.type, ct.created_at, ct.sender_id, ct.receiver_id, 
                   sender_ledger.ledger_name AS sender_name, 
                   receiver_ledger.ledger_name AS receiver_name');
$this->db->from('coin_transactions ct');
$this->db->join('tbl_ledger sender_ledger', 'ct.sender_id = sender_ledger.id', 'left');
$this->db->join('tbl_ledger receiver_ledger', 'ct.receiver_id = receiver_ledger.id', 'left');

$this->db->where('ct.shift_id', NULL); // Ensure only NULL shift_id records

$this->db->group_start(); // Start grouping conditions
$this->db->where('ct.sender_id', $this->session->userdata('id'));

// if ($this->session->userdata['role'] == 'Master') {
//     $this->db->or_where('ct.receiver_id', $this->session->userdata('id'));
// }
$this->db->group_end(); // End grouping conditions

$this->db->order_by('ct.id', 'desc');

$query = $this->db->get();

// Fetch the results as an array
$data['transactions'] = $query->result_array();

// Example: Printing the result
//echo '<pre>';print_r($transactions); die;
        //$this->load->view('coin/allocate_coins', $data);
        $data['_view'] = 'coin/allocate_coins';
        $this->load->view('layouts/main',$data);
    }
    

    // Process Allocation
    public function processAllocation() {
        $receiver_id = $this->input->post('receiver_id');
        $amount = $this->input->post('amount');
        $sender_id = $this->session->userdata('id');
        $role = $this->session->userdata('role');
        $transactiontype = $this->input->post('transactiontype');
        if($transactiontype == 'W'){
            $receiver_id = $this->session->userdata('id');
            $sender_id = $this->input->post('receiver_id');        
        }
        else{
            $receiver_id = $this->input->post('receiver_id');
            $sender_id = $this->session->userdata('id');
        }
       // echo $transactiontype.' '.$receiver_id.' '.$sender_id; die;
      
        if ($role === 'Super Admin' || $role === 'Master') {
            if ($this->CoinModel->allocateCoins($sender_id, $receiver_id, $amount)) {
                if($transactiontype == 'W'){
                    $this->session->set_flashdata('success', 'Coins withdraw successfully.');
                }
                else{
                    $this->session->set_flashdata('success', 'Coins allocated successfully.');
                }
                
            } else {
                $this->session->set_flashdata('error', 'Insufficient balance.');
            }
        } else {
            show_error('Unauthorized access.', 403);
        }
        //$this->session->set_flashdata('success', 'Coins allocated successfully!');
        //return true;
        redirect('ledger');
    }

    // View Balance
    public function viewBalance() {
        $user_id = $this->session->userdata('user_id');
        $data['balance'] = $this->CoinModel->getUserBalance($user_id);
        $this->load->view('coin/view_balance', $data);
    }
    
}
