<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_agent extends CI_Controller{
    function __construct()
    {
        parent::__construct();
		 $this->load->library('session');
        $this->load->model('Tbl_agent_model');
    } 

    /*
     * Listing of tbl_agent
     */
    function index()
    {
        $data['tbl_agent'] = $this->Tbl_agent_model->get_all_tbl_agent();
        
        $data['_view'] = 'tbl_agent/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_agent
     */
    function add()
    {   
        $this->load->library('form_validation');
		$data['error'] = '';
		$this->form_validation->set_rules('agent_name','Agent Name','max_length[255]');
		$this->form_validation->set_rules('main_agent_name','Main Agent Name','max_length[255]');
		$this->form_validation->set_rules('is_active','Is Active','integer');
		$this->form_validation->set_rules('updated_by','Updated By','integer');
		
		if($this->form_validation->run())     
        {   
	
		if($this->Tbl_agent_model->checkDuplicate($this->input->post('agent_name'),$this->session->userdata['id'])=='1'){
			$data['error']="Duplicate Entry Found.Please try with other name.";
		}
		else{
            $params = array(
				'agent_name' => $this->input->post('agent_name'),
				'main_agent_name' => $this->input->post('main_agent_name'),
				'is_active' => $this->input->post('is_active'),
				'updated_by' => $this->session->userdata['id'],
				//'updated_date' => date('d-m-Y',time()),
            );
            
            $tbl_agent_id = $this->Tbl_agent_model->add_tbl_agent($params);
            redirect('agent_master');
        }
		}
		
		 $data['tbl_agent'] = $this->Tbl_agent_model->get_all_tbl_admin();
	//echo '<pre>'; print_r($data['tbl_agent']); echo '</pre>';
            $data['_view'] = 'tbl_agent/add';
            $this->load->view('layouts/main',$data);
    }  

    /*
     * Editing a tbl_agent
     */
    function edit($id)
    {   
        // check if the tbl_agent exists before trying to edit it
        $data['tbl_agent'] = $this->Tbl_agent_model->get_tbl_agent($id);
        $data['error'] = '';
        if(isset($data['tbl_agent']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('agent_name','Agent Name','max_length[255]');
			$this->form_validation->set_rules('main_agent_name','Main Agent Name','max_length[255]');
			$this->form_validation->set_rules('is_active','Is Active','integer');
			$this->form_validation->set_rules('updated_by','Updated By','integer');
		
			if($this->form_validation->run())     
            {   
		if($this->Tbl_agent_model->checkDuplicate($this->input->post('agent_name'),$this->session->userdata['id'])=='1'){
			$data['error']="Duplicate Entry Found.Please try with other name.";
		}
		else{
                $params = array(
					'agent_name' => $this->input->post('agent_name'),
					'main_agent_name' => $this->input->post('main_agent_name'),
					'is_active' => $this->input->post('is_active'),
					'updated_by' => $this->session->userdata['id'],
					//'updated_date' => $this->input->post('updated_date'),
                );

                $this->Tbl_agent_model->update_tbl_agent($id,$params);            
                redirect('agent_master');
            }
			}
           // else
           // {
			    $data['tbl_agent'] = $this->Tbl_agent_model->get_all_tbl_agent();
                $data['_view'] = 'tbl_agent/edit';
                $this->load->view('layouts/main',$data);
           // }
        }
        else
            show_error('The tbl_agent you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_agent
     */
    function remove($id)
    {
        $tbl_agent = $this->Tbl_agent_model->get_tbl_agent($id);

        // check if the tbl_agent exists before trying to delete it
        if(isset($tbl_agent['id']))
        {
            $this->Tbl_agent_model->delete_tbl_agent($id);
            redirect('agent_master');
        }
        else
            show_error('The tbl_agent you are trying to delete does not exist.');
    }
    
}
