<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Tbl_admin extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_admin_model');
        $this->load->library('session');
    }

    /*
     * Listing of tbl_admin
     */
    function index()
    {
        $data['tbl_admin'] = $this->Tbl_admin_model->get_all_tbl_admin();

        $data['_view'] = 'tbl_admin/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new tbl_admin
     */
    function add()
    {
        $this->load->library('form_validation');
        $data['error'] = '';
        $this->form_validation->set_rules('admin_name', 'Admin Name', 'max_length[255]');
        $this->form_validation->set_rules('user_role', 'Role', 'max_length[255]');
        $this->form_validation->set_rules('w_mode', 'W Mode', 'max_length[255]');
        $this->form_validation->set_rules('username', 'Username', 'max_length[255]');
        $this->form_validation->set_rules('password', 'Password', 'max_length[255]');
        $this->form_validation->set_rules('cash_agent', 'Cash Agent', 'max_length[255]');
        $this->form_validation->set_rules('mobile', 'Mobile', 'integer');
        $this->form_validation->set_rules('updated_by', 'Updated By', 'integer');

        if ($this->form_validation->run()) { 
            if ($this->Tbl_admin_model->checkDuplicate($this->input->post('username'), $this->input->post('role')) == '1') {
                $data['error'] = "Username already exist for selected role.Please try with other username.";
            } else {     //echo 'tt'; die;			
                $params = array(
                    'password' => $this->input->post('password'),
                    'admin_name' => $this->input->post('admin_name'),
                    'user_role' => $this->input->post('role'),
                    'w_mode' => $this->input->post('w_mode'),
                    'user_name' => $this->input->post('username'),
                    'cash_agent' => $this->input->post('cash_agent'),
                    'mobile' => $this->input->post('mobile'),
                    'is_active' => $this->input->post('is_active'),
                    'is_locked' => $this->input->post('is_locked'),
                    'updated_by' => $this->session->userdata['id'],
                    //'updated_date' => $this->input->post('updated_date'),
                    'address' => $this->input->post('address'),
                );

                $tbl_admin_id = $this->Tbl_admin_model->add_tbl_admin($params);
                //echo $tbl_admin_id; die;
                redirect('/admin_master');
            }
        }
        //else
        // {            
        $data['tbl_admin'] = $this->Tbl_admin_model->get_all_tbl_admin();
        $data['_view'] = 'tbl_admin/add';
        $this->load->view('layouts/main', $data);
        // }
    }

    /*
     * Editing a tbl_admin
     */
    function edit($id)
    {
        // check if the tbl_admin exists before trying to edit it
        $data['tbl_admin'] = $this->Tbl_admin_model->get_tbl_admin($id);
        $data['error'] = '';
        if (isset($data['tbl_admin']['id'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('admin_name', 'Admin Name', 'max_length[255]');
            $this->form_validation->set_rules('user_role', 'Role', 'max_length[255]');
            $this->form_validation->set_rules('w_mode', 'W Mode', 'max_length[255]');
            $this->form_validation->set_rules('username', 'Username', 'max_length[255]');
            $this->form_validation->set_rules('password', 'Password', 'max_length[255]');
            $this->form_validation->set_rules('mobile', 'Mobile', 'integer');

            if ($this->form_validation->run()) {
                /*if($this->Tbl_admin_model->checkDuplicate($this->input->post('username'),$this->input->post('role'))=='1'){
				$data['error']="Username already exist for selected role.Please try with other username.";
			}	
		else{ */
                $params = array(
                    'password' => $this->input->post('password'),
                    'admin_name' => $this->input->post('admin_name'),
                    'user_role' => $this->input->post('role'),
                    'w_mode' => $this->input->post('w_mode'),
                    'user_name' => $this->input->post('username'),
                    'cash_agent' => $this->input->post('cash_agent'),
                    'mobile' => $this->input->post('mobile'),
                    'is_active' => (($this->input->post('is_active')=='on')?'1':'0'),
                    'is_locked' => (($this->input->post('is_locked')=='on')?'1':'0'),
                     'automatic_jantri' => (($this->input->post('automatic_jantri')=='on')?'1':'0'),
                    'updated_by' => $this->session->userdata['id'],
                    //'updated_date' => $this->input->post('updated_date'),
                    'address' => $this->input->post('address'),
                );
                
                $this->Tbl_admin_model->update_tbl_admin($id, $params);
                redirect('/admin_master');
                //}
            }
            //else
            //{
            $data['_view'] = 'tbl_admin/edit';
            $this->load->view('layouts/main', $data);
            //}
        } else
            show_error('The tbl_admin you are trying to edit does not exist.');
    }

    /*
     * Deleting tbl_admin
     */
    function remove($id)
    {
        $tbl_admin = $this->Tbl_admin_model->get_tbl_admin($id);

        // check if the tbl_admin exists before trying to delete it
        if (isset($tbl_admin['id'])) {
            $this->Tbl_admin_model->delete_tbl_admin($id);
            redirect('/admin_master');
        } else
            show_error('The tbl_admin you are trying to delete does not exist.');
    }
}
