<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_jantri_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_jantri by id
     */
    function get_tbl_jantri($id)
    {
        return $this->db->get_where('tbl_jantri',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all tbl_jantri count
     */
    function get_all_tbl_jantri_count()
    {
        $this->db->from('tbl_jantri');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tbl_jantri
     */
    function get_all_tbl_jantri($params = array())
    {
		 $this->db->select('tbl_jantri.*,tbl_user_login.user_name');
		$this->db->from('tbl_jantri');
		$this->db->join('tbl_user_login', 'tbl_user_login.id = tbl_jantri.updated_by');		
		
        //$this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
		$query = $this->db->get();
		//echo $this->db->last_query(); die;
        return $query->result_array();
    }

    /*
     * Get all tbl_jantri
     */
    function get_all_tbl_jantri_intotal($params = array())
    {  $admin_id = $this->session->userdata['id'];
		 $this->db->select('tbl_master_transaction.t_date, tbl_master_transaction.party_id,tbl_shift.shift_name as shift_name,tbl_shift.id as shift_id,tbl_ledger.ledger_name,tbl_jantri.*,tbl_admin.admin_name');
		$this->db->from('tbl_jantri');
        $this->db->join('tbl_master_transaction', 'tbl_master_transaction.id = tbl_jantri.trns_id');
        $this->db->join('tbl_shift', 'tbl_shift.id = tbl_master_transaction.shift_id','left');
		$this->db->join('tbl_ledger', 'tbl_ledger.id = tbl_master_transaction.party_id','left');
		//$this->db->join('tbl_user_login', 'tbl_user_login.id = tbl_master_transaction.created_by');		
		$this->db->join('tbl_admin', 'tbl_admin.id = tbl_shift.updated_by');
		$this->db->where('tbl_admin.id',$admin_id);
        //$this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
		$query = $this->db->get();
		//echo $this->db->last_query(); die;
        return $query->result_array();
    }

        
    /*
     * function to add new tbl_jantri
     */
    function add_tbl_jantri($params)
    {
        $this->db->insert('tbl_jantri',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_jantri
     */
    function update_tbl_jantri($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_jantri',$params);
    }
    
    /*
     * function to delete tbl_jantri
     */
    function delete_tbl_jantri($id)
    {
        return $this->db->delete('tbl_jantri',array('id'=>$id));
    }
	
	/*Function to check duplicate entry*/
	function checkDuplicate($val,$id)
    {
        return $this->db->get_where('tbl_jantri',array('updated_by'=>$id,'shift_name'=>strtolower($val)))->num_rows();
    }
}
