<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_agent_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_agent by id
     */
    function get_tbl_agent($id)
    {
        return $this->db->get_where('tbl_agent',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tbl_agent
     */
    function get_all_tbl_agent()
    {
        //$this->db->order_by('id', 'desc');
        $this->db->select('tbl_agent.*,tbl_ledger.ledger_name');
		$this->db->from('tbl_agent');
		$this->db->join('tbl_ledger', 'tbl_ledger.id = tbl_agent.updated_by');	
        $this->db->where('tbl_agent.updated_by', $this->session->userdata['id']);
		$query = $this->db->get();
        //echo $this->db->last_query(); die;
		return $query->result_array();
    }

    /*
     * Get all tbl_agent
     */
    function get_all_tbl_agent_master()
    {
        //$this->db->order_by('id', 'desc');
        $this->db->select('tbl_agent.*,tbl_user_login.user_name');
		$this->db->from('tbl_agent');
		$this->db->join('tbl_user_login', 'tbl_user_login.id = tbl_agent.updated_by');
		$query = $this->db->get();
		return $query->result_array();
    }
	
	/*
     * Get all tbl_agent
     */
    function get_all_tbl_admin()
    {
		$id= $this->session->userdata['id'];
        //$this->db->order_by('id', 'desc');
        $this->db->select('tbl_agent.*,tbl_ledger.ledger_name');
		$this->db->from('tbl_agent');
		$this->db->join('tbl_ledger', 'tbl_ledger.id = tbl_agent.updated_by');	
        $this->db->where('tbl_agent.updated_by', $this->session->userdata['id']);
		$query = $this->db->get();
        
		return $query->result_array();
    }
        
    /*
     * function to add new tbl_agent
     */
    function add_tbl_agent($params)
    {
        $this->db->insert('tbl_agent',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_agent
     */
    function update_tbl_agent($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_agent',$params);
    }
    
    /*
     * function to delete tbl_agent
     */
    function delete_tbl_agent($id)
    {
        return $this->db->delete('tbl_agent',array('id'=>$id));
    }
	/*Function to check duplicate entry*/
	function checkDuplicate($val,$id)
    {
        return $this->db->get_where('tbl_agent',array('updated_by'=>$id,'agent_name'=>strtolower($val)))->num_rows();
    }
}
