<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_shift_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /* 
     * Get tbl_shift by id
     */
    function get_tbl_shift($id)
    {
        return $this->db->get_where('tbl_shift',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all tbl_shift count
     */
    function get_all_tbl_shift_count()
    {
        $this->db->from('tbl_shift');
		$this->db->order_by('orderby', 'asc');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tbl_shift
     */
    function get_all_tbl_shift($params = array())
    { //print_r($this->session->userdata['userid']); die;
		 $this->db->select('tbl_shift.*,tbl_ledger.ledger_name');
		$this->db->from('tbl_shift');
		$this->db->join('tbl_ledger', 'tbl_ledger.id = tbl_shift.updated_by','left');
			if(isset($this->session->userdata['userid']) && $this->session->userdata['userid'] != '1'){
			if(!empty($params)){
		$this->db->where('tbl_shift.updated_by',$params);
        $this->db->or_where('tbl_shift.updated_by','1');	
			}			
			}
            else{
                $this->db->where('tbl_shift.updated_by','1');
            }
				if(isset($_SESSION['role'])&&$_SESSION['role']=='Staff'){
                    $this->db->or_where('tbl_shift.updated_by','1');
                }
        //$this->db->order_by('id', 'desc');
        
		$query = $this->db->get();
        //echo $this->db->last_query(); die;
        return $query->result_array();
    }
        /*
     * Get all tbl_shift
     */
    function get_all_tbl_shift_admin($params = array())
    { //print_r($params); die;
	$admin_id = $this->session->userdata['id'];
		 $this->db->select('tbl_shift.*');
		$this->db->from('tbl_shift');
		//$this->db->join('tbl_ledger', 'tbl_ledger.id = tbl_shift.updated_by');
			//if(!empty($params)){
		$this->db->where('tbl_shift.updated_by',$admin_id);	
			//}
			//$this->db->where('tbl_ledger.id',$admin_id);
        //$this->db->order_by('id', 'desc');
        if($admin_id != 1){
			$this->db->or_where('tbl_shift.updated_by','1');
		}
		$query = $this->db->get();
		//echo $this->db->last_query(); die;
        return $query->result_array();
    } 
    /*
     * function to add new tbl_shift
     */
    function add_tbl_shift($params)
    {
        $this->db->insert('tbl_shift',$params);
        return $this->db->insert_id();
    }

    /*function to add tbl user shift*/
    function add_tbl_shift_time($shift_id,$params)
    { 
        $param['master_id'] = $params['updated_by'];
        $param['shift_id'] = $shift_id;
        $param['start_time'] = date("H:i:s", strtotime($params['super_admin']));
        $param['app_time'] = date("H:i:s", strtotime($params['app_time']));
        $param['data_entry_operator'] = date("H:i:s", strtotime($params['data_entry_operator']));
        $this->db->insert('user_shift_timings',$param);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_shift
     */
    function update_tbl_shift($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_shift',$params);
    }
    
    /*
     * function to delete tbl_shift
     */
    function delete_tbl_shift($id)
    {
        return $this->db->delete('tbl_shift',array('id'=>$id));
    }
	
	/*Function to check duplicate entry*/
	function checkDuplicate($val,$id)
    {
        return $this->db->get_where('tbl_shift',array('updated_by'=>$id,'shift_name'=>strtolower($val)))->num_rows();
    }

    public function get_access_time($user_id) {
        $this->db->select('access_times.*');
        $this->db->from('users');
        $this->db->join('admins as sub_admin', 'users.sub_admin_id = sub_admin.id', 'left');
        $this->db->join('access_times', 'access_times.admin_id = COALESCE(sub_admin.id, (SELECT id FROM admins WHERE role = "super_admin" LIMIT 1))', 'left');
        $this->db->where('users.id', $user_id);
        $query = $this->db->get();
        return $query->row();
    }

    public function get_master_shifts(){
        $this->db->from('tbl_shift');
		//$this->db->join('tbl_ as sub_admin', 'users.sub_admin_id = sub_admin.id', 'left');
        $this->db->order_by('orderby', 'asc');
        $this->db->where('updated_by', '1');
        $this->db->or_where('updated_by', $this->session->userdata['userid']);
        $this->db->where('is_active', '1');
        $this->db->where('open_date >=', date('Y-m-d'));
        $query = $this->db->get();
        return $query->row();
    }
    public function get_ledger_shifts($id){
        $this->db->select('user_shift_timings.*,tbl_shift.shift_name');
        $this->db->from('user_shift_timings');
        $this->db->join('tbl_shift', 'user_shift_timings.shift_id = tbl_shift.id', 'left');
		$this->db->order_by('user_shift_timings.id', 'asc');
        $this->db->where('user_shift_timings.master_id', '1');
        $this->db->or_where('user_shift_timings.master_id', $id);
        $this->db->where('tbl_shift.is_active', '1');
        $this->db->where('tbl_shift.open_date >=', date('Y-m-d'));
        $query = $this->db->get();
        return $query->result_array();
    }
}
